### ISSUE TITLE
GetContext(siteURL) method  need 1-4 seconds, it is too slow

### ISSUE THREAD

**Issue by Tony518** [pnp/pnpframework#101]
Hi, 
I use the PnpFramework 1.0.0 version, it run in .net core 3.1
some code below.
`AuthenticationManager authMgr = new AuthenticationManager("***", userName,password);
            try
            {
                using (var ctx = authMgr.GetContext(siteURL))
                {
                       //do something
                 }
             }`
I debug the code, the authMgr.GetContext will consume 1-3 seconds every time.
Is there some ways to optimizate the performance of GetContext?
Thanks for any help.

**Comment by jansenbe** [comment]
Yes, don't instantiate a new AuthenticationManager class each time as that's the one that implements the auth caching via MSAL. Second thing you can do is once you've a context created use the Clone() method to create a context for another site, if no other site needed there typically is not need to recreate the context each time.

**Comment by Tony518** [comment]
Hi jansenbe,
Thanks for your reply, my application is a webapi. 
If I only new the context when application start, and then always clone or reuse this context, will this context expire? if expire, how to known if the context has been expired?

**Comment by jansenbe** [comment]
The context will never expire, we under the covers (via AuthenticationManager) use MSAL for authentication and library handles token caching, it will automatically request a new access token when the current one is about to expire, so as a developer you do not need to worry about this.

**Comment by Tony518** [comment]
ok, thanks.
So I only need to declare a Singleton clientcontext object, and only assign it when application start? 
and then we directly use the clientcontext in the application everywhere?
If so, it will be perfect.

**Comment by jansenbe** [comment]
Yes that can work, assuming you use AuthenticationManager to create the initial ClientContext. Given you're running in a web API I assume you're using app-only?

**Comment by Tony518** [comment]
> Given you're running in a web API I assume you're using app-only?
I'm using the clientId,username and password to initial clientcontext, is it ok?
`AuthenticationManager authMgr = new AuthenticationManager("clientId", userName,password);`

**Comment by jansenbe** [comment]
Sure, that works as well

**Comment by jansenbe** [comment]
Closing this issue since the original question has been answered.

**Comment by Tony518** [comment]
Ok,  thanks very much. it did help me.

**Comment by kongmengfei** [comment]
'
