### ISSUE TITLE
Invoke-PnPSiteTemplate: The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by garrytrinder** [pnp/pnpframework#1037]
Attempting to apply the [Product support provisioning template](https://github.com/SharePoint/sp-dev-provisioning-templates/blob/master/tenant/productsupport/source/template.xml) to a new SharePoint Team site using PnP PowerShell 2.5.0 (latest) results in the below error:

![image](https://github.com/pnp/pnpframework/assets/11563347/8b682f08-74dd-4898-ab2f-a771920e7d01)

The `product_support_logo.jpg` file is present in the Site Assets library.

![image](https://github.com/pnp/pnpframework/assets/11563347/45539822-6451-4dfe-87ba-f20daaa88cf2)

However the path in the error looks like malformed.

`E:\template\https:\tenant.sharepoint.com\sites\ProvisioningTest\SiteAssets\productsupport_logo.jpg`

**Comment by garrytrinder** [comment]
Closing issue, I needed to use the `productsupport.pnp` template file with `Invoke-PnPTenantTemplate` cmdlet instead.

**Comment by gillessylvestre** [comment]
Can you elaborate please?

**Comment by garrytrinder** [comment]
> Can you elaborate please?

The error was thrown when I passed the `.xml` template to the cmdlet, however I should have passed the `.pnp` template file instead.
