### ISSUE TITLE
"Welcome Page View" not being set when applying a template

### ISSUE THREAD

**Issue by diver7** [pnp/pnpframework#105]
I have a document library that has multiple custom content types. For one of those content types, which is a document set, I have a View that I want it to default to. When I go to the Document library settings and click on the content type to get to the List Content Type settings, then click on the "Document Set Settings", I can set the "Welcome Page View" setting to the view I want to default.

If I now export a template (Get-PnPSiteTemplate) from this site and apply it (Invoke-PnPSiteTemplate) to another site the "Welcome Page View" is not set correctly. It is set to the Default view for the document library and not the specific view I had set on the list content type.

Seems to be a bug with the templates or is there another way to set this setting correctly?

I'm using PnP.Powershell version 1.1.0

**Comment by diver7** [comment]
@jansenbe,
Any update on this issue?

**Comment by NickSchweitzer** [comment]
I work with the submitter on this issue - What is the SLA for response on issues like this? If there needs to be more information provided, can someone please respond with that? We are roadblocked on this issue.

**Comment by jansenbe** [comment]
@NickSchweitzer , @diver7 ,
There's no SLA on PnP open source as it's largely run via community contributions from non-MSFT and MSFT folks. We do our best to stay on top of things, providing a clean repro, ideally with a suggested fix (a PR) will for sure speed up the handling of the issue.

**Comment by prawnz** [comment]
I have the same question raised to me as well.. Clicking by hand manually is not feasible.. Any guidance?

**Comment by diver7** [comment]
@prawnz Unfortunately I don't have any good news on this subject. We have been working with Microsoft on this issue and have not come up with a solution yet. It appears that the underlying APIs for SPO do not have any way to update this setting and that is why it is not in the PnP library either. Our contact at Microsoft is trying to talk to the Product Group to see if there is any way to do this or if it is in the roadmap for the API.

**Comment by diver7** [comment]
> > talk to the Product Group to see if there is any way to do this or if it is in the roadmap for the API.
> 
> Any update on this?

@rens8 Sorry but we never got anywhere on this with Microsoft. There was no way to do it at the time and I haven't seen any updates since then suggesting that it was coming.
