### ISSUE TITLE
Page instances created from page templates showing wrong description

### ISSUE THREAD

**Issue by derhallim** [pnp/pnpframework#106]
Hello, I'm using this template: [https://gist.github.com/derhallim/e47c4f02642bd7f076c5970aa9000e95](https://gist.github.com/derhallim/e47c4f02642bd7f076c5970aa9000e95) . I generated this template after modifying the site in browser and generating the template using PnP.PowerShell v1.1.0, but I'm having issues applying the template to any new sites. These are the steps am doing to produce the issue: 

1) Invoke-PnPSiteTemplate -Path ./TemplateInGist.xml
2) Create a new page in the site using the template "Two Column Layout" that is deployed in the template. 
![image](https://user-images.githubusercontent.com/7239963/105273633-b289c880-5b69-11eb-9961-4e69461dd410.png)
3) Change the default text in the page, add anything.
4) Publish page and post as News. 
5) Add a News WebPart on the homepage. 
  
Actual Result: 
  The News WebPart is going to show the old description in the page template. That is: "About this page?​​​​​​​This page includes two columns of text, with related articles at..."

Expected Result: 
 News WebPart should show the text added by the user, not the page template text.

**Comment by jansenbe** [comment]
Hi @derhallim ,

I've applied a custom page template via a provisioning template and when the user wants to create a new page based upon this template they see the description in the custom template:

![image](https://user-images.githubusercontent.com/7451219/105350487-89aa1780-5beb-11eb-9c86-2613472e1536.png)

When they've created the page they've the option to set a new page description

![image](https://user-images.githubusercontent.com/7451219/105350391-61221d80-5beb-11eb-9d1c-bae2d77ddd6b.png)

Which will then show up in the news part, identical to when using one of the OOB templates:

![image](https://user-images.githubusercontent.com/7451219/105350639-c1b15a80-5beb-11eb-9737-a6d4662f4828.png)

However, when not setting any description at all the OOB template "finds" a description by taking the first piece of text while done from the custom template this does not seem to happen. 

![image](https://user-images.githubusercontent.com/7451219/105351255-99762b80-5bec-11eb-94bd-44f2b2b99ef0.png)

Is that the main issue you're having?

**Comment by jansenbe** [comment]
Did some more testing and have found out that we need to set the isDefaultDescription property to true in the pageSettingsSlice when we save a page as template. With that property set the description will again be populated automatically. I'll make the needed changes for this.

**Comment by derhallim** [comment]
Awesome! Thanks a lot @jansenbe!

**Comment by derhallim** [comment]
@jansenbe I just got a new version of `PnP.PowerShell`, ran `Get-PnPSiteTemplate`, and applied it somewhere else, it didn't have any effect. Still, the new pages are having the same issue. I have `PnP.PowerShell V1.2.0` .. is this the right version we have to use for this issue?

**Comment by derhallim** [comment]
It's working now with the nightly release. Thanks @jansenbe 
One question, is the change applied in the generated xml itself? I'm not seeing anything related to IsDefaultDescription in the generated xml, how was it set?

**Comment by jansenbe** [comment]
no, it's inside our code: no changes needed for the xml templates
