### ISSUE TITLE
 Microsoft.AspNetCore.StaticFiles 2.2.0 is deprecated and will lead to a lot of critical security vulnerability warnings (NU1904)

### ISSUE THREAD

**Issue by gszdev** [pnp/pnpframework#1088]
Is is possible to remove the dependency to the depracted nuget package '[Microsoft.AspNetCore.StaticFiles](https://www.nuget.org/packages/microsoft.aspnetcore.staticfiles/)' (AspNetCore 2.2, ...)?
And I assume that a FrameworkReference to Microsoft.AspNetCore.App is not wanted for sure.

A least with .NET 9 it will lead to critical security vulnerability warnings (NU1904)

A simple copy of [FileExtensionContentTypeProvider.cs](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/StaticFiles/src/FileExtensionContentTypeProvider.cs) should be enough to repace the usage in ObjectTeams.cs [new FileExtensionContentTypeProvider().TryGetContentType(photoPath, out contentType);](https://github.com/pnp/pnpframework/blob/2b2e0dcd174f9adf6dd3fbf718fc50e3798abd20/src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs#L1536
)
Or use the MimTypeMap like from PnP.Core [PnP.Core/Utilities/MimeTypeMap.cs](https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core/Utilities/MimeTypeMap.cs)

But I don't know wether the licensing allows it.

FileExtensionContentTypeProvider.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

Is PnP.Framework part auf the .NET Foundation?

**Comment by jansenbe** [comment]
@gszdev : I've removed this dependency (copied over the one class we needed from this old deprecated assembly).
