### ISSUE TITLE
Incorporating this into SPMT or equivalent experience

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpframework#112]
#### Category

[ ] Bug
[X] Enhancement

#### Expected or Desired Behavior

Include the modernization tooling as part of SPMT or Standalone tooling. This would provide a UI like experience to converting the pages - for those that are less familiar with PowerShell or ASP.NET. 

I might do some investigating over the demand for this.

**Comment by jansenbe** [comment]
Closing this as this is an MSFT internal ask and not something this project can realize. The idea has been discussed, but no short term plans at this moment.
