### ISSUE TITLE
Failed to set ContentType on ClientSidePage

### ISSUE THREAD

**Issue by czullu** [pnp/pnpframework#117]
@jansenbe 
The Error while set ContentType on ClientSidePage happens in ObjectClientSidePages in here  

```
           // Update page content type
            bool isDirty = false;
            if (!string.IsNullOrEmpty(clientSidePage.ContentTypeID))
            {
                //page.PageListItem[ContentTypeIdField] = clientSidePage.ContentTypeID;
                //page.PageListItem.UpdateOverwriteVersion();
                //web.Context.Load(page.PageListItem);
                fileAfterSave.ListItemAllFields[ContentTypeIdField] = clientSidePage.ContentTypeID;
                fileAfterSave.ListItemAllFields.UpdateOverwriteVersion();
                web.Context.Load(fileAfterSave.ListItemAllFields);
                isDirty = true;
            }
```

Checking both values before assign shows that the page has the ContentTypeId from the Lib while the Template has it from the Web.
fileAfterSave.ListItemAllFields[ContentTypeIdField]
0x0101009D1CB255DA76424F860D91F20E6C411800BD421750B0C84F43BC71B37A21DA5118

clientSidePage.ContentTypeID;
0x0101009D1CB255DA76424F860D91F20E6C4118

Error i get as ServerException: "Additions to this Web site have been blocked.\n\nPlease contact the administrator to resolve this problem."

Work on a fix to get List-CT based on clientSidePage.ContentTypeID - then compare and if different update. If fix is ok - i will submit.

**Comment by jansenbe** [comment]
@czullu : would be great if you can submit a fix for this.

**Comment by jansenbe** [comment]
@czullu : you also get this error is the page was checked in...maybe something to cross check

**Comment by czullu** [comment]
> @czullu : you also get this error is the page was checked in...maybe something to cross check
Yes the Page is checked-in - it happens on default home.aspx after site creation.

**Comment by jansenbe** [comment]
Closing issue now that PR has been merged
