### ISSUE TITLE
Where Can I find minimal Documentation

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpframework#12]
Where Can I find minimal Documentation is it based on something else to get started?
I want to use this framework going forward but don't know even how to get a site list items files etc..

**Comment by jansenbe** [comment]
Hi @Ofer-Gal ,

There's a ton of videos on SharePoint and Office 365 development on our [youtube channel](https://www.youtube.com/channel/UCV_6HOhwxYLXAGd-JOqKPoQ), there's also a [getting started series on development](https://www.youtube.com/playlist?list=PLR9nK3mnD-OV6WhWHOMAvW-T_EBGKIs3u). If you're interested in the provisioning engine features then check out https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-remote-provisioning.

There's not a lot of written documentation for PnP Framework, for our new [PnP Core SDK](https://pnp.github.io/pnpcore/) we're trying to do a better job at that.

**Comment by waaromikniet** [comment]
I want to investigate what our team needs to do to move to this new library.

We use the old provisioning engine (using ref to PnP-Sites-Core in our project) in our own created console application. We call the method ApplyProvisioningTemplate from the webextensions class. Is this basic functionality still available in the new PnPFramework? Or in the PnP Core DSK?

Are the code samples available on shot term how to use this new framework?

**Comment by jansenbe** [comment]
Aside of the auth code (which was rewritten) most of the features are there and work exactly the same. So when transferring your existing code to use PnP Framework you should not have too many issues. If there's something blocked then please reach out (as you've done in other issues already).

**Comment by jansenbe** [comment]
Closing as questions are answered
