### ISSUE TITLE
Question - Forbidden error when trying to OpenBinaryStream

### ISSUE THREAD

**Issue by DenisRouge** [pnp/pnpframework#124]
Hello,

2 weeks ago I asked about how to reproduce Weblogin Method that was in the old PnPLivrary (Issue #79).
You send us a workaround using some classes from PnP Powershell.
I'm trying to load a file using OpenBinaryStream but when we access to the file we received an error "Forbidden" 

Have you an idea of what can can be done in order to make it work?

Thank you
```
using ( var ctx = GetWebLoginClientContext( "https://my.sharepoint.com", true ) )
{
	var fi = ctx.Web.GetFileByServerRelativeUrl( "/teams/Demo/Test.xlsx" );

	ctx.Load( fi );
	ctx.ExecuteQuery(); // System.Net.WebException: The remote server returned an error: (403) Forbidden.

	fi.OpenBinaryStream();
	ctx.ExecuteQuery();
}
```

**Comment by jansenbe** [comment]
Do other operations work, eg getting the title of the current web? If not then there might be something wrong with the GetWebLoginClientContext implementation. Did downloading files using weblogin work with the old pnp-sites-core library?

**Comment by jansenbe** [comment]
Just used the -UseWebLogin option in PS and then used `Get-PnPFile -Url /sites/prov-1/graph/document.docx -Path d:\temp -AsFile`...this works. See https://github.com/pnp/powershell/blob/4e8bc03ed3976c4bccb826da1f0892777f11fc6d/src/Commands/Files/GetFile.cs#L132. So seems as the approach you're using should be possible to get working

**Comment by DenisRouge** [comment]
With neither old PnPCore or the new WebloginContext, context.Web.Title is initialized. 
I tried to do the same (GetFile, Load and ExecuteQuery) with the old livrary but I also received an Access Denied Error.
I have the same error using PnPPowershell the command you send me. 
```
Connect-PnPOnline -Url https://My.sharepoint.com -UseWebLogin
Get-PnPFile  -Url "/teams/Demo/Demo.xlsx"  -AsFile -Path D:\Temp
```

**Comment by jansenbe** [comment]
Well then it seems that web login cannot handle your auth scenario...just to refresh my memory, were you having an on-premises ADFS that's connected to Azure AD? The nightly PowerShell  builds now also have an alternative method using the `-Interactive` parameter...can you give that a try as well? If that works you could try to reuse that approach in your code base. We've added this option after I've recommended you to copy the weblogin bits from PS.

@PaoloPia / @erwinvanhunen : any additional thoughts?

**Comment by DenisRouge** [comment]
We try to connect to Azure AD with a MFA using SPO and to read a file from this sharepoint. We don't have direct control over the sharepoint site we connect so we don't have an application Id.
I'm sorry but I don't understand what you want me to doabout the nightly powershell build.

**Comment by jansenbe** [comment]
@DenisRouge :
If you don't have an application id then -Interactive won't be an option, only way around then is using the "old" weblogin approach...which seems to fail for you in both PS and PnP Framework. Would it be possible to collect a Fiddler trace of a full login up to failure cycle and share that with me via bjansen@microsoft.com? This way I can maybe better understand what happens.

**Comment by jansenbe** [comment]
Hi @DenisRouge : Looking at the fiddler trace I see this:
![image](https://user-images.githubusercontent.com/7451219/106046010-ff2d5080-60e1-11eb-8808-aeef9ab60ff3.png)

There are 2 calls to get the request digest (the contextInfo one is expected, the other not) and when the CSOM call is made a double request digest is passed in:
`X-RequestDigest: 0xD93A9D6CE7D0B17E6B0F33A0C48AC5B0CCADFBB24036DDF2EFAEF39D98AE54ABC8B2674A21C4D8EC76CFF34DBB336EB9C529C02947B05C2A6AF6D7D39D429365,27 Jan 2021 15:34:07 -0000,0xD93A9D6CE7D0B17E6B0F33A0C48AC5B0CCADFBB24036DDF2EFAEF39D98AE54ABC8B2674A21C4D8EC76CFF34DBB336EB9C529C02947B05C2A6AF6D7D39D429365,27 Jan 2021 15:34:07 -0000`

So this makes me think that in the copied browser helper code something is not going as planned. Would recommend debugging that piece of code and ensure you only call GetRequestDigestAsync once (don't call GetOnPremisesRequestDigestInfoAsync as that's meant for on-prem usage) and check the places where `e.WebRequestExecutor.WebRequest.Headers.Add("X-RequestDigest"` is used that you specify a correct value (so not a double value you're doing today).

**Comment by jansenbe** [comment]
Hi @DenisRouge ,

Are you unblocked? If so, let's close this issue

**Comment by DenisRouge** [comment]
I will investigate about these 2 calls and keep you informed.

**Comment by DenisRouge** [comment]
GetRequestDigestAsync was already called once. I made a patch in order to not add X-RequestDigest to the header two times but it's still not working (Access denied. You do not have permission to perform this action or access this resource).  I can send you the updated code with the fiddler code if needed.

**Comment by jansenbe** [comment]
Yes, send updated Fiddler so can I have a look...

**Comment by jansenbe** [comment]
Fiddler was shared with custom code that, after fixing, works in my lab. Also worked to load a web title for @DenisRouge , so closing this issue here
