### ISSUE TITLE
Question about issue logged in PnP Sites Core for Add-PnPNavigationNode

### ISSUE THREAD

**Issue by MedinaFab** [pnp/pnpframework#129]
There was an issue [AddNavigationNode to Footer](https://github.com/pnp/PnP-Sites-Core/issues/2740) and I thought it was close to being resolved. With all these changes, am I NOT suppose to use `Add-PnPNavigationNode` anymore?

**Comment by jansenbe** [comment]
@MedinaFab : This change was merged, so give it a try with the [new PowerShell version](https://pnp.github.io/powershell/articles/installation.html) and create a new issue if things don't work for you specifying the exact steps and in case of an error the output in from `Get-PnPException`

**Comment by Chaotix** [comment]
This issue still exists.
Will it ever be looked at?

**Comment by Sharepoint2k22** [comment]
I'm having the same issue in a customer tenant (but not in another dev tenant using exactly the same command), that is:

Add-PnPNavigationNode -Title "Navigation Test" -Location Footer -Url "http://linkless.header/"

 This is what come back from get-PnPException:

Message          : Unable to define Navigation Node collection to add the node to
Stacktrace       :    at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord() in
                   c:\build\src\Commands\Base\PnPConnectedCmdlet.cs:line 101
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in
                   c:\build\src\Commands\Base\PnPSharePointCmdlet.cs:line 121
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 1

Any help would be most appreciated.
