### ISSUE TITLE
On-Behalf-Of authorization in AuthenticationManager, flexible Authentication Authority

### ISSUE THREAD

**Issue by titns** [pnp/pnpframework#13]
I am trying to implement Web API using the library via AzureAD, Enterprise application as Authentication mechanism, Pnp.Framework as backend and AadHttpClient javascript as front-end. This has led me to an authentication issue:

The token passed from the client-side to the back-end is not recognized for use in `AuthenticationManager.GetAccessTokenContext(siteUrl, token)`. It returns 401 Unauthorized. As a workaround I wanted to use OAuth OBO mechanism, but the library lacks client context type of `ClientContextType.AzureADOnBehalfOf` (or similar to) which would use the token retrieved from the client in a call to acquire a new token for SPO. This could be done in a call `confidentialClientApplication.AcquireTokenOnBehalfOf(scopes, new UserAssertion(token))`. Ofcourse, the library also lacks a constructor which would create `AuthenticationManager` with clientid and secret - `ConfidentialClientApplicationBUilder.Create(clientId).WithClientSecret(clientSecret);`

A final note, at the moment Enterprise Applications can be registered as single-tenant or multi-tenant, but the Pnp.Framework strictly requires multi-tenant applications, because it has hardcoded authority ending in `/organizations`, which is not allowed to be used by single-tenant applications after year 2018. On the other hand, it is easy enough to just make the application multi-tenant.

I am not sure if I am doing something wrong (e.g. incorrectly using jwt token of AadHttpClient) or if the library (sh-)could be extended to allow more flexible approach, so any feedback would be appreciated.

**Comment by jansenbe** [comment]
Hi @titns ,

Thanks for the feedback. 

About OnBehalfOf: we indeed don't have that supported in the current PnP Framework authentication manager. In our new PnP Core SDK we however already do support that, depending on your needs that might be a solution for you? Code: https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Auth/Confidential/OnBehalfOfAuthenticationProvider.cs, relevant test cases: https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Auth.Test/Providers/OnBehalfOfAuthenticationProviderTests.cs 

Added @PaoloPia and @erwinvanhunen for your feedback on the "/organizations"

**Comment by titns** [comment]
Ahh, yes, I see it there, thank you. Although the core SDK is not sufficient for SPO current needs and PnP framework seems more suitable due to the set of extensions and explicit work with SPO CSOM. If the idea of OBO auth is not against PnP framework, I could try to provide the PR following the current coding practices (as much as I can). Otherwise, for now I will wait and keep my copy of the repository with the changes.

**Comment by jansenbe** [comment]
We'd welcome a PR 👏

**Comment by jansenbe** [comment]
Closing this now that #17 was merged. Thanks a ton @titns 👏
