### ISSUE TITLE
Unable to remove default Document content type

### ISSUE THREAD

**Issue by derhallim** [pnp/pnpframework#134]
[x] Bug

I have the following xml to provision the document library: [https://gist.github.com/derhallim/b59fed8ee6a3bddbb685607c67200f3e](https://gist.github.com/derhallim/b59fed8ee6a3bddbb685607c67200f3e). 

**Current Behavior:** 
By omitting the default document content type as shown in the xml snippet, I see two document content types available in the library, my custom doc content type and the default document content type. Result shown below: 
![image](https://user-images.githubusercontent.com/7239963/105894885-c6f31880-5fe2-11eb-8c71-6f1a6d58a3a0.png)

**Expected Behavior:** 
When omitting the default document content type and adding a custom one, that custom content type should be the only content type available in the library.

**Comment by jansenbe** [comment]
@derhallim : You need to leave the default content types in but set the Remove attribute on them to true.

**Comment by jansenbe** [comment]
Did this work for you @derhallim, if so please let me know so the issue can be closed

**Comment by derhallim** [comment]
@jansenbe I just tried it out. It didn't have an effect. I still see the Document content type in the library.

**Comment by jansenbe** [comment]
Please share a simple repro template

**Comment by derhallim** [comment]
@jansenbe here it is: [https://gist.github.com/derhallim/4ae9e335022de87a3da9e9ceaca36334](https://gist.github.com/derhallim/4ae9e335022de87a3da9e9ceaca36334)

**Comment by jansenbe** [comment]
You need to use this : `<pnp:ContentTypeBinding ContentTypeID="0x0101" Remove="true" />` , the content type with ID 0x0101 is not the default content type in the default document library

**Comment by derhallim** [comment]
Can't believe I left that in there. Thanks @jansenbe
