### ISSUE TITLE
ConvertTo-PnPPage: author not being set in page header

### ISSUE THREAD

**Issue by leupenb** [pnp/pnpframework#136]
Hi,

I'm running the following command which does not add the author in the page header (i'm running on version 1.2.6.0):

`ConvertTo-PnPPage -SetAuthorInPageHeader -PublishingPage -Identity 'page.aspx' -Overwrite -TargetWebUrl $targetUrl -CopyPageMetadata -PageLayoutMapping "<custompagelayoutmapping>"`

Without the -PageLayoutMapping parameter it doesn't either.

I have the following in my page layout mapping (at the top):
`<PageLayouts>
    <PageLayout Name="Nieuws-normaal" AssociatedContentType="" PageLayoutTemplate="TwoColumnsWithSidebarRight" PageHeader="Custom"  >
	<SectionEmphasis VerticalColumnEmphasis="None">
        <Section Row="1" Emphasis="Neutral" />
      </SectionEmphasis>
      <Header Type="FullWidthImage" Alignment="Left" ShowPublishedDate="true">
        <Field Name="PublishingRollupImage" HeaderProperty="ImageServerRelativeUrl" Functions="ToImageUrl({PublishingRollupImage})" />
        <Field Name="ArticleByLine" HeaderProperty="TopicHeader" Functions="" />
        <Field Name="PublishingContact" HeaderProperty="Authors" Functions="ToAuthors({PublishingContact})" />
      </Header>`

It doesn't make a difference when I change the PageHeader to 'Default'.

I have tested the above with the 'SharePointPnPPowerShellOnline' module where it does work as expected.

Might this be a bug?

**Comment by jansenbe** [comment]
Thanks for reporting this @leupenb , seems like a bug. I'll see if I can reproduce it from my side.

**Comment by jansenbe** [comment]
@leupenb: Issue has been reproduced and fixed (was a caching problem). Will be part of tomorrow's nightly, thanks for the testing and keep the feedback coming.

**Comment by leupenb** [comment]
@jansenbe great, thanks!

**Comment by leupenb** [comment]
Bug is fixed!
