### ISSUE TITLE
Exception not cached when trying to add existing member or owner to a unified group

### ISSUE THREAD

**Issue by magarma** [pnp/pnpframework#140]
#Hi,
I'm trying to update a unified group with an existing user or owner, the Graph request is giving an error...

```
POST https://graph.microsoft.com/v1.0/groups/5d08888a-d9e3-44e9-8371-46f4d774ed72/owners/$ref HTTP/1.1
Host: graph.microsoft.com
User-Agent: NONISV|SharePointPnP|PnPCore/1.1.0.0
...
{"@odata.id":"https://graph.microsoft.com/v1.0/directoryObjects/56bc8f87-b25e-463d-88ef-1a243acccebd"}
```

and the response...

```
HTTP/1.1 400 Bad Request
Cache-Control: private
Content-Type: application/json
...
{
  "error": {
    "code": "Request_BadRequest",
    "message": "One or more added object references already exist for the following modified properties: 'owners'.",
    "innerError": {
      "date": "2021-01-27T18:01:47",
      "request-id": "1064c860-10b6-4c37-827b-00196731c901",
      "client-request-id": "1064c860-10b6-4c37-827b-00196731c901"
    }
  }
}
```

The code is failing when checking the exception to ignore that case, it is checking InnerException, what it comes null instead of checking directly the property Message...

![image](https://user-images.githubusercontent.com/8925463/106105183-d9389800-6143-11eb-9e8c-ab71bc254fa8.png)

image
![image](https://user-images.githubusercontent.com/8925463/106105207-e35a9680-6143-11eb-8109-f2455a6965b1.png)

I'll send a PR for catching properly the error.
#139

**Comment by jansenbe** [comment]
Closing as the fix has been merged. Thx @magarma !
