### ISSUE TITLE
Add-PnPNavigationNode Navigation Node Collection is null

### ISSUE THREAD

**Issue by MedinaFab** [pnp/pnpframework#141]
I have installed new PowerShell version (after a painful experience since older version didn't want to uninstall), as per advised pnp/pnpframework#129. I tried this command but still failed. Copying @jansenbe. Thanks in advance for your help. Really thankful for PNP! 😃

`Add-PnPNavigationNode -Title "Privacy Policy" -Url "http://www.company.com/privacy/" -Location "Footer"`

Error obtained:
`Add-PnPNavigationNode: Navigation Node Collection is null`

Get-PnPException
`
Message          : Navigation Node Collection is null
Stacktrace       :    at PnP.PowerShell.Commands.Branding.AddNavigationNode.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
ScriptLineNumber : 1`

**Comment by MedinaFab** [comment]
Hello. Any update?

**Comment by gabbsmo** [comment]
So far I have only seen this in previously created communication sites. Fresh sites in any tenant I tried seem to work as expected.
