### ISSUE TITLE
ConvertTo-PnPPage : Index was out of range. Must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by mattgilchrist7** [pnp/pnpframework#144]
Hi there,

I'm receiving this error when trying to modernize a Classic SharePoint site. 

#### Problem Area

Modernization of site with: ConvertTo-PnPPage -Identity Home.aspx -Overwrite

#### Expected or Desired Behavior

Modernize Classic Sharepoint site

#### Observed Behavior

![image](https://user-images.githubusercontent.com/50526689/106288092-2ab75480-6222-11eb-8b6f-ef2337ea87e2.png)

#### Steps to Reproduce

Connect-PnPOnline -Url https://mysite.sharepoint.com -UseWebLogin

ConvertTo-PnPPage -Identity Home.aspx -Overwrite

#### Submission Guidelines

Get-PnPException

Message          : Index was out of range. Must be non-negative and less than the size of the collection.
                   Parameter name: index
Stacktrace       :    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource
                   resource)
                      at System.Collections.Generic.List`1.get_Item(Int32 index)
                      at PnP.Framework.Modernization.Transform.ContentTransformator.LastColumnOrder(Int32 row, Int32 col)
                      at PnP.Framework.Modernization.Transform.ContentTransformator.Transform(List`1 webParts)
                      at PnP.Framework.Modernization.Transform.PageTransformator.Transform(PageTransformationInformation
                   pageTransformationInformation)
                      at PnP.PowerShell.Commands.Pages.ConvertToClientSidePage.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
ScriptLineNumber : 1

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.2.7      PnP.PowerShell                      {Add-PnPAlert, Add-PnPApp, Add-PnPApplicationCustomizer, Add-PnPCon...

Any thoughts or advice would be very helpful.

Thanks!

**Comment by jansenbe** [comment]
@mattgilchrist7 : this typically happens whenever page transformation cannot detect the used layout of the home page, sometimes  folks manually edited the home page html making it impossible to detect the layout anymore. Can you grab the wiki page content and share it. Use below PS snippet to get to the content:

```PowerShell
# Check the id of your home.aspx page first
$p = Get-PnPListItem -List sitepages -Id 1
# copy contents into clipboard
$p.FieldValues["WikiField"] | clip
```

**Comment by mattgilchrist7** [comment]
Okay here's the contents on my clipboard. This make sense, I believe there are a few things that have been manually edited by the previous developer.

<div class="ExternalClassC629B62294164656AD4F405329F38739"><table id="layoutsTable" style="width&#58;100%;"><tbody><tr style="vertical-align&#58;top;"><td colspan="2"><div class="ms-rte-layoutszone-outer" style="width&#58;100%;"><div class="ms-rte-layoutszone-inner"><strong style="font-family&#58;&quot;segoe ui semilight&quot;, &quot;segoe ui&quot;, segoe, tahoma, helvetica, arial, sans-serif;font-size&#58;18pt;">​​​​​​​​Welcome to the Eastern Composites&#160;</strong><nobr class="ms-rteFontSize-4" style="font-family&#58;&quot;segoe ui semilight&quot;, &quot;segoe ui&quot;, segoe, tahoma, helvetica, arial, sans-serif;"><strong>SharePoint ​​Management System​​</strong></nobr><span style="font-family&#58;&quot;segoe ui semilight&quot;, &quot;segoe ui&quot;, segoe, tahoma, helvetica, arial, sans-serif;font-size&#58;1em;">​​</span><br></div></div></td></tr><tr style="vertical-align&#58;top;"><td style="width&#58;49.95%;"><div class="ms-rte-layoutszone-outer" style="width&#58;100%;"><div class="ms-rte-layoutszone-inner"><div><div align="left">​Here you will find everything you need as per the ECS HSEQ Management System such as&#58; <br></div><ul><li>Policies
</li><li>Procedures
</li><li>Work Instructions
</li><li>Form Templates</li></ul><p align="left">This portal also contains links to various Quality Management
Tools such as&#58;<br></p><ul><li>Continual Improvement
</li><li>Approved Suppliers
</li><li>Audits
</li><li>Meetings
</li><li>Equipment Management
</li><li>and more!!!<br></li></ul></div></div></div></td><td class="ms-wiki-columnSpacing" style="width&#58;49.95%;"><div class="ms-rte-layoutszone-outer" style="width&#58;100%;"><div class="ms-rte-layoutszone-inner">​​​​​​​<div class="ms-rtestate-read ms-rte-wpbox"><div class="ms-rtestate-notify  ms-rtestate-read f0a967df-b94b-4b7a-8213-6aa2598f84d8" id="div_f0a967df-b94b-4b7a-8213-6aa2598f84d8" unselectable="on"></div><div id="vid_f0a967df-b94b-4b7a-8213-6aa2598f84d8" unselectable="on" style="display&#58;none;"></div></div>​<br><br><br></div></div></td></tr></tbody></table><span id="layoutsData" style="display&#58;none;">true,false,2</span><div class="ExternalClass1E3C29215D6F461AB4992BF2F05D7E8B">
                <table id="layoutsTable" style="width&#58;100%;"><tbody><tr style="vertical-align&#58;top;"><td style="width&#58;100%;"><div class="ms-rte-layoutszone-outer" style="width&#58;100%;"><div class="ms-rte-layoutszone-inner"><p>​​<br></p></div></div></td></tr></tbody></table>
    <span id="layoutsData" style="display&#58;none;">false,false,1</span></div></div>

**Comment by jansenbe** [comment]
@mattgilchrist7 : Can you paste the content in code block...above strips all the HTML...which is what I need to see. You create a code block by enclosing the html in three back ticks (```)

**Comment by mattgilchrist7** [comment]
Of course, here you go. 
```
<div class="ExternalClassC629B62294164656AD4F405329F38739"><table id="layoutsTable" style="width&#58;100%;"><tbody><tr style="vertical-align&#58;top;"><td colspan="2"><div class="ms-rte-layoutszone-outer" style="width&#58;100%;"><div class="ms-rte-layoutszone-inner"><strong style="font-family&#58;&quot;segoe ui semilight&quot;, &quot;segoe ui&quot;, segoe, tahoma, helvetica, arial, sans-serif;font-size&#58;18pt;">????????Welcome to the Eastern Composites&#160;</strong><nobr class="ms-rteFontSize-4" style="font-family&#58;&quot;segoe ui semilight&quot;, &quot;segoe ui&quot;, segoe, tahoma, helvetica, arial, sans-serif;"><strong>SharePoint ??Management System??</strong></nobr><span style="font-family&#58;&quot;segoe ui semilight&quot;, &quot;segoe ui&quot;, segoe, tahoma, helvetica, arial, sans-serif;font-size&#58;1em;">??</span><br></div></div></td></tr><tr style="vertical-align&#58;top;"><td style="width&#58;49.95%;"><div class="ms-rte-layoutszone-outer" style="width&#58;100%;"><div class="ms-rte-layoutszone-inner"><div><div align="left">?Here you will find everything you need as per the ECS HSEQ Management System such as&#58; <br></div><ul><li>Policies 
</li><li>Procedures 
</li><li>Work Instructions 
</li><li>Form Templates</li></ul><p align="left">This portal also contains links to various Quality Management 
Tools such as&#58;<br></p><ul><li>Continual Improvement 
</li><li>Approved Suppliers 
</li><li>Audits 
</li><li>Meetings 
</li><li>Equipment Management 
</li><li>and more!!!<br></li></ul></div></div></div></td><td class="ms-wiki-columnSpacing" style="width&#58;49.95%;"><div class="ms-rte-layoutszone-outer" style="width&#58;100%;"><div class="ms-rte-layoutszone-inner">???????<div class="ms-rtestate-read ms-rte-wpbox"><div class="ms-rtestate-notify  ms-rtestate-read f0a967df-b94b-4b7a-8213-6aa2598f84d8" id="div_f0a967df-b94b-4b7a-8213-6aa2598f84d8" unselectable="on"></div><div id="vid_f0a967df-b94b-4b7a-8213-6aa2598f84d8" unselectable="on" style="display&#58;none;"></div></div>?<br><br><br></div></div></td></tr></tbody></table><span id="layoutsData" style="display&#58;none;">true,false,2</span><div class="ExternalClass1E3C29215D6F461AB4992BF2F05D7E8B">
                <table id="layoutsTable" style="width&#58;100%;"><tbody><tr style="vertical-align&#58;top;"><td style="width&#58;100%;"><div class="ms-rte-layoutszone-outer" style="width&#58;100%;"><div class="ms-rte-layoutszone-inner"><p>??<br></p></div></div></td></tr></tbody></table>
    <span id="layoutsData" style="display&#58;none;">false,false,1</span></div></div>
```

**Comment by jansenbe** [comment]
Checking the HTML I see there are two layoutsData spans, page transformation takes the first one assuming a "2 column with header" layout, while it seems you're using a single column layout. Can you drop the first layoutsData span from the page and try again?

![image](https://user-images.githubusercontent.com/7451219/106308997-cae09e00-6261-11eb-9ee6-908cad651914.png)

To do that put the page in edit mode and pick the correct layout.
![image](https://user-images.githubusercontent.com/7451219/106309192-109d6680-6262-11eb-91d0-01d09d191bca.png)

Cross check the raw html updated, if not you can always edit using PnP PowerShell:

```PowerShell
$updatedHtml = Get-ClipBoard -raw
$p.FieldValues["WikiField"] = $updatedHtml
$p.SystemUpdate()
Invoke-PnPQuery
```

**Comment by mattgilchrist7** [comment]
@jansenbe The site should be a two column layout with a header. I've made the changes in the $updatedHtml to try and reflect that here's the result.
``` 
<div class="ExternalClassC629B62294164656AD4F405329F38739"><table id="layoutsTable" style="width&#58;100%;"><tbody><tr style="vertical-align&#58;top;"><td colspan="2"><div class="ms-rte-layoutszone-outer" style="width&#58;100%;"><div class="ms-rte-layoutszone-inner"><strong style="font-family&#58;&quot;segoe ui semilight&quot;, &quot;segoe ui&quot;, segoe, tahoma, helvetica, arial, sans-serif;font-size&#58;18pt;">?????????????Welcome to the Eastern Composites&#160;</strong><nobr class="ms-rteFontSize-4" style="font-family&#58;&quot;segoe ui semilight&quot;, &quot;segoe ui&quot;, segoe, tahoma, helvetica, arial, sans-serif;"><strong>SharePoint ??Management System??</strong></nobr><span style="font-family&#58;&quot;segoe ui semilight&quot;, &quot;segoe ui&quot;, segoe, tahoma, helvetica, arial, sans-serif;font-size&#58;1em;">??</span><br></div></div></td></tr><tr style="vertical-align&#58;top;"><td style="width&#58;49.95%;"><div class="ms-rte-layoutszone-outer" style="width&#58;100%;"><div class="ms-rte-layoutszone-inner"><div><div align="left">?Here you will find everything you need as per the ECS HSEQ Management System such as&#58; <br></div><ul><li>Policies 
</li><li>Procedures 
</li><li>Work Instructions 
</li><li>Form Templates</li></ul><p align="left">This portal also contains links to various Quality Management 
Tools such as&#58;<br></p><ul><li>Continual Improvement 
</li><li>Approved Suppliers 
</li><li>Audits 
</li><li>Meetings 
</li><li>Equipment Management 
</li><li>and more!!!<br></li></ul></div></div></div></td><td class="ms-wiki-columnSpacing" style="width&#58;49.95%;"><div class="ms-rte-layoutszone-outer" style="width&#58;100%;"><div class="ms-rte-layoutszone-inner">???????<div class="ms-rtestate-read ms-rte-wpbox"><div class="ms-rtestate-read f0a967df-b94b-4b7a-8213-6aa2598f84d8" id="div_f0a967df-b94b-4b7a-8213-6aa2598f84d8"></div><div style="display&#58;none;" id="vid_f0a967df-b94b-4b7a-8213-6aa2598f84d8"></div></div>

?<br><br><br><br><br></div></div></td></tr></tbody></table><span id="layoutsData" style="display&#58;none;">true,false,2</span><div class="ExternalClass1E3C29215D6F461AB4992BF2F05D7E8B">
                <table id="layoutsTable" style="width&#58;100%;"><tbody><tr style="vertical-align&#58;top;"><td style="width&#58;100%;"><div class="ms-rte-layoutszone-outer" style="width&#58;100%;"><div class="ms-rte-layoutszone-inner"><p>??<br></p></div></div></td></tr></tbody></table>
    </div></div>
```

**Comment by jansenbe** [comment]
but does the transformation now work?

**Comment by mattgilchrist7** [comment]
Unfortunately no,
```
ConvertTo-PnPPage -Identity Home.aspx -Overwrite
ConvertTo-PnPPage : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
At line:1 char:1
+ ConvertTo-PnPPage -Identity Home.aspx -Overwrite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPPage], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.ConvertToClientSidePage
```

```
Get-PnPException


Message          : Index was out of range. Must be non-negative and less than the size of the collection.
                   Parameter name: index
Stacktrace       :    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource
                   resource)
                      at System.Collections.Generic.List`1.get_Item(Int32 index)
                      at PnP.Framework.Modernization.Transform.ContentTransformator.LastColumnOrder(Int32 row, Int32 col)
                      at PnP.Framework.Modernization.Transform.ContentTransformator.Transform(List`1 webParts)
                      at PnP.Framework.Modernization.Transform.PageTransformator.Transform(PageTransformationInformation
                   pageTransformationInformation)
                      at PnP.PowerShell.Commands.Pages.ConvertToClientSidePage.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
ScriptLineNumber : 1
```

Please let me know what other information I can provide.

**Comment by jansenbe** [comment]
@mattgilchrist7 : I've tested this and found a way to solve this by:

- removing the first `<span id="layoutsData"` element
- update the other one (at the end of the html file) to be like this: `<span id="layoutsData" style="display&#58;none;">true,true,2</span>` -> this indicates that a 2 column with header and footer must be used, which is what you're using on that page. The 'original' two `<span id="layoutsData"` entries both were wrong.

To update the html value use below (my original approach did not update the list item):

```powershell
$content = Get-Clipboard -Raw
Set-PnPListItem -List sitepages -Identity 1 -Values @{"WikiField"=$content}
```

**Comment by jansenbe** [comment]
@mattgilchrist7 : do you have many of these 'wrong' pages or just a few?

**Comment by mattgilchrist7** [comment]
@jansenbe Thanks, the second round of changes resulted in a successful transformation of the homepage. 

I haven't found any more with this error yet. My trouble now stems from trying to modernize sites that are not under the /SitePages/ url. They appear as a subsite under the Site Contents, but the url is: https://mysite.sharepoint.com/bdl/default.aspx

There are also classic sites that reside in the Site Assets library, which is odd and causing the same error. Here's an example of these urls: https://mysite.sharepoint.com/CI/SiteAssets/Supplier%20Management%20System.aspx Do you have a recommend way to move these sites or append the URLs so that they are recognized by the modernization tool? Or should I be targeting them in a slightly different way?

```
ConvertTo-PnPPage : Page 'default.aspx' does not exist
At line:1 char:1
+ ConvertTo-PnPPage -Identity default.aspx -Overwrite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPPage], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.ConvertToClientSidePage
```
```
Get-PnPException


Message          : Page 'default.aspx' does not exist
Stacktrace       :    at PnP.PowerShell.Commands.Pages.ConvertToClientSidePage.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
ScriptLineNumber : 1
```

Thanks,

**Comment by jansenbe** [comment]
@mattgilchrist7 : if the pages live outside of the site's pages library they so called "web part pages", these can live in a document library or even directly in the site outside of a library. Page Transformation does support you to transform these pages, note that the created modern page always lives in the site pages library as modern pages cannot live elsewhere. By default the modern equivalent is created inside a folder named like the source library (to avoid naming conflicts when pages from different locations are created as modern page in a central location).

If the page lives in another library use the `-Library bdl` parameter. If the page happens to live inside a folder in a library you can also add `-Folder subfolder` to indicate the folder the transformation needs to look inside. In the rare event that the page was created outside of the library you can specify `<root>` as folder name. See https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-powershell to learn more.

Looking at your urls:
- https://mysite.sharepoint.com/bdl/default.aspx: if there's no subsite called "bdl" under the mysite host then the page lives in a library named "bdl". If there's a sub site then the page lives in the "<root>" of that sub site
- https://mysite.sharepoint.com/CI/SiteAssets/Supplier%20Management%20System.aspx: this clearly is a web part page living in the site's SiteAssets library

**Comment by mattgilchrist7** [comment]
@jansenbe : Thank you for the clarification about the 'web part pages'! I was able to modernize all of the pages that resided in the SiteAssets library. Several of my pages reside under Site Contents > Subsites, which according to the sitemanager, exist directly in the site and outside of any library.


![image](https://user-images.githubusercontent.com/50526689/106619876-97489100-654b-11eb-9a44-561bb5af7b22.png)

How should I target these pages?

```
Connect-PnPOnline -Url https://mysite.sharepoint.com/bdl -UseWebLogin
```
Results in:
```
ConvertTo-PnPPage : Page 'default.aspx' does not exist
At line:1 char:1
+ ConvertTo-PnPPage -Identity default.aspx -Overwrite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPPage], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.ConvertToClientSidePage
```
```
Get-PnPException


Message          : Page 'default.aspx' does not exist
Stacktrace       :    at PnP.PowerShell.Commands.Pages.ConvertToClientSidePage.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
ScriptLineNumber : 1
```

Thanks,

**Comment by jansenbe** [comment]
You first need to connect to the sub site  "Connect-PnPOnline -Url https://mysite.sharepoint.com/subsite -UseWebLogin` and then apply the same logic as before, if the page lives in a library inside the sub site specify the library and so on...

**Comment by jansenbe** [comment]
@mattgilchrist7 : I'll close this issue as the original problem was fixed and now it's more of a Q&A. If you still have questions then please open a new discussion (for questions) or issue (if you think it's a bug).
