### ISSUE TITLE
Missing method "Load" on ClientSidePage object

### ISSUE THREAD

**Issue by Jke-A** [pnp/pnpframework#145]
Hi,

I am currently converting a project from OfficeDev.PnP.Core to PnP.Framework and have not found a way to get webparts from a modern page. Previously we could use ClientSidePage.Load() but it seems to be missing in PnP.Framework? Am I missing a reference or has it not been implemented yet?

![ClientSidePage](https://user-images.githubusercontent.com/31936693/106299340-543da380-6255-11eb-9fe1-76177e19022f.png)

Thanks,
Joachim

**Comment by jansenbe** [comment]
The modern pages API is exposed via PnP Core SDK, meaning PnP Framework internally uses the PnP Core SDK implementation (as we only wanted to maintain a single code base).  Loading a page can be done using `clientContext.Web.LoadClientSidePage("pagename")` and you'll get back an [IPage object](https://pnp.github.io/pnpcore/api/PnP.Core.Model.SharePoint.IPage.html). See https://pnp.github.io/pnpcore/using-the-sdk/pages-intro.html on how to further code with the IPage object.

**Comment by Jke-A** [comment]
Great - thank you!
