### ISSUE TITLE
Groupify option when creating a site of type TeamSiteNoGroup

### ISSUE THREAD

**Issue by magarma** [pnp/pnpframework#146]
Hi,
I'm trying to create a site of type "TeamSiteNoGroup" and then create a group associated to it with the flag Groupify=true.

```
<pnp:SiteCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                                xsi:type="**pnp:TeamSiteNoGroup**" 
                                ProvisioningId="TEST" 
                                Title="{parameter:SiteTitle}" 
                                Alias="{parameter:SiteAlias}" 
                                Url="{parameter:SiteCollectionUrl}"
                                **Groupify="true"**
                                IsPublic="true" 
                                IsHubSite="false" 
                                Owner="{parameter:UPNOwner}" 
                                Description="">
```

I'm having some issues working with it:
* If I use an AppOnly token, with permissions on SharePoint ("TermStore.ReadWrite.All", "Sites.FullControl.All"), the code is doing a request to the endpoinf of SharePoint  /_vti_bin/client.svc/ProcessQuery and I'm receiving a permissions error

```
[
{
"SchemaVersion":"15.0.0.0","LibraryVersion":"16.0.20913.12007","ErrorInfo":{
"ErrorMessage":"{\"odata.error\":{\"code\":\"Authorization_RequestDenied\",\"message\":{\"lang\":\"en\",\"value\":\"Insufficient privileges to complete the operation.\"},\"requestId\":\"61f719e2-7022-4d24-baf8-0c7944e3169e\",\"date\":\"2021-01-29T16:13:25\"}}","ErrorValue":null,"TraceCorrelationId":"8811a69f-d08d-2000-7d71-e54b21aa11c0","ErrorCode":-1,"ErrorTypeName":"System.Data.Services.Client.DataServiceClientException"
},"TraceCorrelationId":"8811a69f-d08d-2000-7d71-e54b21aa11c0"
}
]
```

Is this supported? 
Maybe with AppOnly token we should avoid that step or try to follow another approach if it was possible.

**Comment by jansenbe** [comment]
Might be related to #138

**Comment by gautamdsheth** [comment]
I guess to use groupify , you also need to provide Group.Create or Group.ReadWrite.All permissions since we are dealing with M365 groups. Can you add that permission and check ?

**Comment by magarma** [comment]
Hi, 
Just to clarify...
The code is calling to the SharePoint endpoint "/_vti_bin/client.svc/ProcessQuery".
We are using an app in Azure with certificate.
Right now we have these permissions...
![image](https://user-images.githubusercontent.com/8925463/106379712-3041a580-63ae-11eb-8ec0-0f6e3c204213.png)

There are no more for groups or something like that in the SharePoint API...
May we consider to check in the code if is an AppOnly token and create the group differently, maybe through graph?

Thanks
