### ISSUE TITLE
Cleanup use of HttpClient to prevent port exhaustion scenarios on large scale cloud usage

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpframework#15]
See https://github.com/pnp/PnP-Sites-Core/pull/2774 for reference

**Comment by apringle** [comment]
👍  I think this is only blocker I have migrating our large scale cloud project. @jansenbe Is this expected to be in any particular upcoming release? Thanks for all your hard work on this project!

**Comment by jansenbe** [comment]
Not yet planned for specifically, but good that you mention you need it. You would only be impact on really large scale scenarios, so maybe the current bits do work for you? Anyhow, in PnP Framework things are already better compared to PnP Sites Core, but some investigation/fixing still needs to happen to get even better

**Comment by SchauDK** [comment]
Anything you can do to push this is appreciated. It is a huge issue for us.
It is not something we can just to a PR from our side to fix.

**Comment by jansenbe** [comment]
I'll see what I can do...

**Comment by jansenbe** [comment]
@SchauDK  / @apringle : can you please test with the latest drop (1.1.12 or higher) and see if this improves the scenario for you.

**Comment by jansenbe** [comment]
Closing this issue, if you're still experiencing issues with this then please raise a new issue. We plan to release a new official version by end of the week that will contain these features, similar updates have been made to PnP PowerShell as well.
