### ISSUE TITLE
[BUG] Get-PnPAADUser Mail Property

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/pnpframework#150]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
`Get-PnPAADUser` shoud return `mail` property

### Actual behavior 
`Get-PnPAADUser -Filter "DisplayName eq 'Yuriy Samorodov'"` will not return `mail`
![image](https://user-images.githubusercontent.com/5260172/106571918-d32e2700-6548-11eb-9d24-9482c65c9004.png)

### Steps to reproduce behavior
```
$props = @{
    Url = $Url
    Thumbprint = $CertThumbprint
    ClientId = $ClientId
    Tenant = $TenantId
}
Connect-PnPOnline @props
Get-PnPAADUser -Filter "DisplayName eq 'UserName'" -Select DisplayName, mail
```

### What is the version of the Cmdlet module you are running?
```
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   1.2.5      nightly    PnP.PowerShell                      {Add-PnPAlert, Add-PnPApp, Add-PnPApplicationCustoΓÇª
```

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
It has been fixed and the fix will be available in the next nightly build of the PnP.Framework and PnP PowerShell as of tomorrow.

**Comment by YuriySamorodov** [comment]
Thanks @erwinvanhunen 
One of the reasons I switched so quickly from SPOOnline module to PnP.PowerShell is you great support!
