### ISSUE TITLE
Unable to hide fields in content type on list level. 

### ISSUE THREAD

**Issue by derhallim** [pnp/pnpframework#159]
I'm trying to deploy a content type and have a column be hidden inside the library. However after the deployment the column is hidden on the content type on the site level, but not on the content type on the list level. 

Here's the code am using: [https://gist.github.com/derhallim/ebdeb89971033a4921f6bf0375b3ea18](https://gist.github.com/derhallim/ebdeb89971033a4921f6bf0375b3ea18). 

The column am trying to hide is called Department and its of type of type Managed Metadata. Is it something wrong on my end or a possible bug?

**Comment by jansenbe** [comment]
Hi @derhallim ,

You do add the the via a fieldref via the content type as hidden....but later on you add the same field again as fieldref to the list, not hidden this time. I think you should only add fieldrefs to the list which are not provided by the content type ... or alternatively also add the hidden attribute to the list fieldrefs (the one at the end of your sample).

**Comment by derhallim** [comment]
@jansenbe It worked for me by adding fieldrefs to the list the same way I did with the content type and marking them as hidden there as well.

**Comment by derhallim** [comment]
Hi @jansenbe so I found out that setting the fieldref on the list as hidden, will hide the field completely even in the views. Removing the fieldref hidden on the list and just keeping it hidden on the content type will still show it in forms. Removing the fieldref completely and just reference the fields in the content type will also show the fields in the form. So the only way to hide the fields for me in forms is to set fieldrefs to hidden on the list but it hides them in views. 

Here's a gist of my template: https://gist.github.com/derhallim/fadee2d709ca02833a75b8d1a2763bff
