### ISSUE TITLE
Modern Page Transformation not working on root site

### ISSUE THREAD

**Issue by Thien73** [pnp/pnpframework#168]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Page is not looking correct after transformation

#### Expected or Desired Behavior

When the transformation is run on a root site collection(modern ). I expect the page images to be transferred over to the destination pages during the transformation.

#### Observed Behavior

The page images from the source are not being transferred over to the destination pages. It leaves an empty placeholder. The images are not copied into the site assets folder.

#### Steps to Reproduce

1) connect to sp2013
2) connect to sponline
3) run the command: ConvertTo-PNPclientSidePage with the source and target connections

In the log we see the message: operation : Asset Transfer 
Message: Asset was not Transferred . Asset :/ PublishingImages/enable business.jpg
PnpPowerShell version:  3.28.2012.0

If we run the same script on a non root site then the images and text are transferred correctly.
non root site:(https://abc.sharepoint.com/sites/communicationsite)

**Comment by jansenbe** [comment]
@Thien73 : can you run a page transformation from a publishing page in the root site collection of the on-premises web app using verbose logging and then share that log (after anonymizing it)

**Comment by Thien73** [comment]
bert,
here is the log.
[1:41 PM] Unknown User
      TA, Thien (Cognizant) joined the meeting.
    ​[2:08 PM] Sanjeeva Murthy, Pranesh Kyeshwara (Infrastructure)
    
# Modernization Summary Report
Date | Duration | Source Page | Target Page Url | Status
------------- | ------------- | ------------- | ------------- | -------------
02/10/2021 5:01:54 PM | 00:00:08 | [/Pages/Do.aspx](/Pages/Do.aspx) | [/SitePages/Do.aspx](/SitePages/Do.aspx) | Successful with 8 warnings and 0 non-critical errors
## Warnings during transformation
Date | Source Page | Operation | Message
------------- | ------------- | ------------- | -------------
02/10/2021 5:01:57 PM | /Pages/Do.aspx | Publishing Page analyzer | Could not retrieve field value from mapping, the contents were empty
02/10/2021 5:01:57 PM | /Pages/Do.aspx | Publishing Page analyzer | Could not retrieve field value from mapping, the contents were empty
02/10/2021 5:01:58 PM | /Pages/Do.aspx | Content Transform | Not Supported, Non Exportable or Unidentified Web Part
02/10/2021 5:01:58 PM | /Pages/Do.aspx | Content Transform | Not Supported, Non Exportable or Unidentified Web Part
02/10/2021 5:01:58 PM | /Pages/Do.aspx | Content Transform | Not Supported, Non Exportable or Unidentified Web Part
02/10/2021 5:01:58 PM | /Pages/Do.aspx | Content Transform | Not Supported, Non Exportable or Unidentified Web Part
02/10/2021 5:01:58 PM | /Pages/Do.aspx | Web Part Mapping | Skipping this web part's transformation - cross site not supported
02/10/2021 5:01:58 PM | /Pages/Do.aspx | Asset Transfer | Asset was not transferred. Asset: /PublishingImages/TestImage_0003_Layer%2013.jpg
# Individual Page details
## Transformation Details: /Pages/Do.aspx
- Report date: 02/10/2021 5:01:54 PM
- Transform duration: 00:00:08
- Transforming from site:
- Cross-Site transfer mode to site:
- Transforming page: /Pages/Do.aspx
- Source SharePoint version: 2013 (15.0.0.5241)
- Mode: Publishing Page Transformation Mode
- Transformed Page: /SitePages/Do.aspx
### Page Transformation Settings
Property | Setting
------------- | -------------
Engine version | 1.0.2012.0
Overwrite | True
Target Page Name |
Target Page Folder |
Target Page Folder Overrides Default Folder | False
Keep Page Specific Permissions | True
Remove Empty Sections And Columns | True
Handle Wiki Images And Videos | True
Add Table List Image As Image Web Part | True
Keep Page Creation Modification Information | False
Publish Created Page | True
Post As News | False
Disable Page Comments | False
Skip Url Rewrite | False
Skip Default Url Rewrite | False
Url Mapping File |
Term Mapping File |
Skip Term Store Mapping | False
Skip User Mapping | False
User Mapping File |
L D A P Connection String |
Skip Telemetry | False
### Transformation Operation Details
Date | Operation | Actions Performed
------------- | ------------- | -------------
02/10/2021 5:01:54 PM | _Input Validation_ | _Validation checks complete_
02/10/2021 5:01:54 PM | _SharePoint Connection_ | _Loading client context objects_
02/10/2021 5:01:55 PM | _SharePoint Connection_ | _Loading target client context object_
02/10/2021 5:01:55 PM | _Page Creation_ | _Detect if the page is living inside a folder_
02/10/2021 5:01:55 PM | Page Creation | In Cross-Site transform mode the original source file name is used
02/10/2021 5:01:55 PM | _Page Creation_ | _Just try to load the page in the fastest possible manner, we only want to see if the page exists or not_
02/10/2021 5:01:56 PM | Page Creation | The page already exists in target location
02/10/2021 5:01:56 PM | Page Creation | Modern page created
02/10/2021 5:01:56 PM | Article page handling | Transforming source page as Article page
02/10/2021 5:01:56 PM | Article page handling | Recognized source page as a Publishing Page - Analyzing web parts and page layouts
02/10/2021 5:01:56 PM | Page Layout Manager | Page uses hig-newsarticle as page layout, no mapping was provided so auto generating a mapping
02/10/2021 5:01:56 PM | Page Layout Manager | Page uses hig-newsarticle as page layout, mapping that will be used is hig-newsarticle
02/10/2021 5:01:57 PM | **Publishing Page analyzer** | **Could not retrieve field value from mapping, the contents were empty**
02/10/2021 5:01:57 PM | **Publishing Page analyzer** | **Could not retrieve field value from mapping, the contents were empty**
02/10/2021 5:01:57 PM | Content Transform | Calling Web Services to Extract Web Parts from Page
02/10/2021 5:01:58 PM | Content Transform | Retrieving Web Part using Workaround from Page for Transform WebPartId: bbc68e31-0896-4fc1-bc9f-d20c2bfd939a
02/10/2021 5:01:58 PM | Content Transform | Retrieving Web Part using Workaround from Page for Transform WebPartId: faeba7df-6467-4a94-b9f9-6af4639c22f7
02/10/2021 5:01:58 PM | Content Transform | Source page contains web part `Comments` of type `Microsoft.SharePoint.Portal.WebControls.SocialCommentWebPart`
02/10/2021 5:01:58 PM | Content Transform | Source page contains web part `Related Information` of type `Microsoft.SharePoint.Publishing.WebControls.SummaryLinkWebPart`
02/10/2021 5:01:58 PM | **Content Transform** | **Not Supported, Non Exportable or Unidentified Web Part**
02/10/2021 5:01:58 PM | Content Transform | Source page contains web part `Related Articles` of type `Unsupported Web Part Type`
02/10/2021 5:01:58 PM | **Content Transform** | **Not Supported, Non Exportable or Unidentified Web Part**
02/10/2021 5:01:58 PM | Content Transform | Source page contains web part `Social Web Part` of type `Unsupported Web Part Type`
02/10/2021 5:01:58 PM | **Content Transform** | **Not Supported, Non Exportable or Unidentified Web Part**
02/10/2021 5:01:58 PM | Content Transform | Source page contains web part `Social Web Part` of type `Unsupported Web Part Type`
02/10/2021 5:01:58 PM | **Content Transform** | **Not Supported, Non Exportable or Unidentified Web Part**
02/10/2021 5:01:58 PM | Content Transform | Source page contains web part `Contact Us` of type `Unsupported Web Part Type`
02/10/2021 5:01:58 PM | Article page handling | Splitting images and videos from wiki text - as modern text web part does not support embedded images and videos
02/10/2021 5:01:58 PM | Set Page Title | Setting the modern page title: Advocacy Protocols
02/10/2021 5:01:58 PM | _Article page handling_ | _Preparing content transformation_
02/10/2021 5:01:58 PM | Article page handling | Transforming content
02/10/2021 5:01:58 PM | Content Transform | Transforming web parts
02/10/2021 5:01:58 PM | Web Part Mapping | Web Part:'WikiText' of type 'SharePointPnP.Modernization.WikiTextPart' is being transformed
02/10/2021 5:01:58 PM | _Web Part Mapping_ | _Processing selector functions_
02/10/2021 5:01:58 PM | _Web Part Mapping_ | _Combining mapping data_
02/10/2021 5:01:58 PM | Adding Web Parts to Target Page | Added 'Client Side Text Web Part' to target page
02/10/2021 5:01:58 PM | Web Part Mapping | Web Part:'Comments' of type 'Microsoft.SharePoint.Portal.WebControls.SocialCommentWebPart' is being transformed
02/10/2021 5:01:58 PM | **Web Part Mapping** | **Skipping this web part's transformation - cross site not supported**
02/10/2021 5:01:58 PM | Web Part Mapping | Web Part:'Related Information' of type 'Microsoft.SharePoint.Publishing.WebControls.SummaryLinkWebPart' is being transformed
02/10/2021 5:01:58 PM | _Web Part Mapping_ | _Processing selector functions_
02/10/2021 5:01:58 PM | Web Part Mapping | Processing mapping functions
02/10/2021 5:01:58 PM | _Web Part Mapping_ | _Combining mapping data_
02/10/2021 5:01:58 PM | Adding Web Parts to Target Page | Using 'QuickLinks' modern web part
02/10/2021 5:01:58 PM | Adding Web Parts to Target Page | Added 'Quick links' Client Side Web Part to target page
02/10/2021 5:01:58 PM | Web Part Mapping | Web Part:'Related Articles' of type 'Unsupported Web Part Type' is being transformed
02/10/2021 5:01:58 PM | _Web Part Mapping_ | _Combining mapping data_
02/10/2021 5:01:58 PM | Adding Web Parts to Target Page | Added 'Client Side Text Web Part' to target page
02/10/2021 5:01:58 PM | Web Part Mapping | Web Part:'Social Web Part' of type 'Unsupported Web Part Type' is being transformed
02/10/2021 5:01:58 PM | _Web Part Mapping_ | _Combining mapping data_
02/10/2021 5:01:58 PM | Adding Web Parts to Target Page | Added 'Client Side Text Web Part' to target page
02/10/2021 5:01:58 PM | Web Part Mapping | Web Part:'Social Web Part' of type 'Unsupported Web Part Type' is being transformed
02/10/2021 5:01:58 PM | _Web Part Mapping_ | _Combining mapping data_
02/10/2021 5:01:58 PM | Adding Web Parts to Target Page | Added 'Client Side Text Web Part' to target page
02/10/2021 5:01:58 PM | Web Part Mapping | Web Part:'Contact Us' of type 'Unsupported Web Part Type' is being transformed
02/10/2021 5:01:58 PM | _Web Part Mapping_ | _Combining mapping data_
02/10/2021 5:01:58 PM | Adding Web Parts to Target Page | Added 'Client Side Text Web Part' to target page
02/10/2021 5:01:58 PM | Content Transform | Transforming web parts complete
02/10/2021 5:01:58 PM | Article page handling | Transforming content complete
02/10/2021 5:01:58 PM | Page Layout Manager | Page uses newsarticle as page layout, no mapping was provided so auto generating a mapping
02/10/2021 5:01:58 PM | Page Layout Manager | Page uses newsarticle as page layout, mapping that will be used is hig-newsarticle
02/10/2021 5:01:58 PM | **Asset Transfer** | **Asset was not transferred. Asset: /PublishingImages/TestImage_0003_Layer%2013.jpg**
02/10/2021 5:01:58 PM | Publishing Page header transformation | Header image set to /PublishingImages/TestImage_0003_Layer%2013.jpg
02/10/2021 5:01:58 PM | _User Transform_ | _Principal Input:
02/10/2021 5:01:58 PM | User Transform | Not remapping user
02/10/2021 5:02:00 PM | Article page handling | Saved page in cross-site collection: Do.aspx
02/10/2021 5:02:00 PM | Item level permissions | Item level permissions read
02/10/2021 5:02:03 PM | Page Creation | Transformation Complete

**Comment by jansenbe** [comment]
@Thien73 : can you cross check if images without special characters in them are also not copied over?

**Comment by jansenbe** [comment]
Hey @Thien73 , just checking in on how things are going?

**Comment by Thien73** [comment]
Hey Bert thanks for checking in we just realized that there is a new PNP
powershell do you think we need to install this to move forward?

**Comment by jansenbe** [comment]
@Thien73 , yes that's recommended. I did fix an issue with handling special chars in the new PnP PowerShell, so might be related to your issue as well. Anyhow, the old versions of PnP PowerShell will not be updated, so if there's a fix needed it will be added to the latest version of PnP Framework and PnP PowerShell.

If some images are copied from the root site then the special chars might be the problem, if nothing is copied at all then this most likely is a bug we need to reproduce and fix

**Comment by jansenbe** [comment]
Closing per no feedback. If the problem still persists please ensure you're using the latest version and open a new issue
