### ISSUE TITLE
When using Get-PnPSiteTemplate, can't extract a site logo unless it was applied the "classic" way

### ISSUE THREAD

**Issue by joshtransient** [pnp/pnpframework#172]
Scenario: create a site and change the site logo through Settings > Change the look > Header > Site logo > Change. Next, run the following:
````
Get-PnPSiteTemplate -Out template.pnp -Handlers PageContents,Pages,SiteFooter,SiteHeader,Files,WebSettings
````
Behavior: outputs template.pnp, but does not include the site logo in the Files folder, or as a `<pnp:File />` element in the XML

Workaround: change the site logo through Settings > Site information > View all site settings > Title, description, and logo > Insert Logo > From computer

Suggestion: `Get-PnPSiteTemplate` should support modern theme configurations.

**Comment by jansenbe** [comment]
What type of site you're working on? For group connected sites the logo lives in the Microsoft 365 Group and I don't think we're handling the extraction. You can however manually update your template, see the source folder of the LookBook templates in here https://github.com/SharePoint/sp-dev-provisioning-templates/tree/master/tenant for some inspiration.

**Comment by jansenbe** [comment]
Closing per no feedback for weeks.
