### ISSUE TITLE
The "Theme" handler doesn't appear to work

### ISSUE THREAD

**Issue by joshtransient** [pnp/pnpframework#173]
Scenario: create a site and change the theme through Settings > Change the look > Theme. Next, run the following:
````
Get-PnPSiteTemplate -Out theme.xml -Handlers Theme
````
Behavior: outputs theme.xml, which has an empty `<pnp:ProvisioningTemplate />` element

Suggestion: `Get-PnPSiteTemplate` should support modern theme configurations

**Comment by jansenbe** [comment]
The modern themes live at tenant level, to extract them you can use PnP PS, we're not extracting these by default.

```powershell
// list all themes
Get-PnPTenantTheme

// get the json definition from a theme
$theme = Get-PnPTenantTheme -Name "myCompanyTheme" -AsJson
```

**Comment by jansenbe** [comment]
Closing per no feedback anymore

**Comment by asith-w** [comment]
> The modern themes live at tenant level, to extract them you can use PnP PS, we're not extracting these by default.
> 
> ```powershell
> // list all themes
> Get-PnPTenantTheme
> 
> // get the json definition from a theme
> $theme = Get-PnPTenantTheme -Name "myCompanyTheme" -AsJson
> ```

but how do we get the applied theme name of a Site such as 'https://contoso.sharepoint.com/sites/mysite' ?
