### ISSUE TITLE
Azure Storage Connector missing, (un)intentional?

### ISSUE THREAD

**Issue by YannickRe** [pnp/pnpframework#18]
Hi team!

I've been kicking the tires of this package for the last week or so, since I am sick and tired of Azure Functions v1 😃. I'm very impressed thus far, as everything seems to behave as expected and no issues encountered!

Is there a reason why the AzureStorageConnector didn't make the transition from .NET to .NET Core? I assumed it was because it's still using the old, deprecated Microsoft.WindowsAzure.Storage packages.
If that's the case (and not some other reason), I can do a PR with an AzureStorageConnector that uses the new Azure.Storage.Blobs packages, since I needed it for my project.

Let me know what you think!

**Comment by jansenbe** [comment]
Hi @YannickRe , this was intentional as we wanted to lower the amount of nuget packages + this was not really a highly used feature. We can absolutely take a PR that makes the needed changes (if any) that are needed to allow you to code up an Azure Storage Connector in your own code base, in the PnP Framework we only plan to ship the file and SharePoint connectors

**Comment by YannickRe** [comment]
Understandable, and not an issue for me. I have my working version (adapted from the .NET implementation with the newer packages), and I didn't have issues with the current base class.
GetConnectionString() and GetContainer() are declared internal but their implementation was easy enough to recreate in my own code base (and it's not necessary to have this as a method anyways).

If you ever think about starting repo's with "extensions" or "example implementations" of Connectors or other stuff for PnP.Framework that is "bloated" for the core package, let me know and I'll happily share my AzureFileStorageConnector implementation.

Thank you for the response!

**Comment by lukju** [comment]
> Understandable, and not an issue for me. I have my working version (adapted from the .NET implementation with the newer packages), and I didn't have issues with the current base class.
> GetConnectionString() and GetContainer() are declared internal but their implementation was easy enough to recreate in my own code base (and it's not necessary to have this as a method anyways).
> 
> If you ever think about starting repo's with "extensions" or "example implementations" of Connectors or other stuff for PnP.Framework that is "bloated" for the core package, let me know and I'll happily share my AzureFileStorageConnector implementation.
> 
> Thank you for the response!

Hi YannickRe.
May I ask you to share your AzureFileStorageConnector class? I would be highly interested... 
Lukas

**Comment by YannickRe** [comment]
@lukju I'm sorry for the late reaction. Yes, I had a plan to share this externally, turn it into a nugget package but it hasn't happened yet. How long can you wait?  It might take some time until I can turn it into something stable and tested and released.
If you are pressed for time, I can maybe share it privately for now.

**Comment by rodionboroviy** [comment]
> Hi @YannickRe , this was intentional as we wanted to lower the amount of nuget packages + this was not really a highly used feature. We can absolutely take a PR that makes the needed changes (if any) that are needed to allow you to code up an Azure Storage Connector in your own code base, in the PnP Framework we only plan to ship the file and SharePoint connectors

I think it is needed very much. You are not able to provision template that references assets from the blob storage.

**Comment by YannickRe** [comment]
I have this released on our company's Nuget feed: https://www.nuget.org/packages/Qubix.PnPFramework.AzureStorageConnector
Feel free to let us know if you need anything, or submit your own PR at https://github.com/Qubix365/pnpframework-azurestorageconnector

It does look as if we need to do some package version updates tho 😀
