### ISSUE TITLE
Not able to find Get-PnPProvisionTemplate, Apply-PnPProvisioningTemplate documentation 

### ISSUE THREAD

**Issue by ymihir** [pnp/pnpframework#180]
**Question**
I am not able to find  Get-PnPProvisionTemplate, Apply-PnPProvisioningTemplate in [PnP Commands Documentation](https://pnp.github.io/powershell/cmdlets/Add-PnPAlert.html). Something got changed in provision engine?

**Comment by jansenbe** [comment]
Use `Get-PnPSiteTemplate` and `Invoke-PnPSiteTemplate`. The old names still work (due to aliases), but these are the officially recommended cmdlets to use and these are documented.

**Comment by ymihir** [comment]
But is there any documentation about this? Not only these two commands, any other changes in commands

**Comment by jansenbe** [comment]
See https://pnp.github.io/powershell/articles/upgrading.html
