### ISSUE TITLE
ConvertTo-PnPPage Embedded Text (Not content editor webpart) is not getting copied of to Modern Page. 

### ISSUE THREAD

**Issue by PrasadMadhavan** [pnp/pnpframework#182]
I am using below command to copy content from a classic SharePoint site collection to modern site collection. It works fine when there are content added inside Content Editor Webpart. But if there is an embedded HTML page content on a classic page,  that's not copying across. We have over 1000 pages like this to be migrated.  Can you please advise on the steps to take care of this?  Thanks. 

Command: 
ConvertTo-PnPPage -Identity "SourcePage.aspx" -PublishingPage -TargetWebUrl <TargetModernSiteUrl> -OverWrite -LogType File -LogFolder c:\temp -LogVerbose

**Comment by jansenbe** [comment]
@PrasadMadhavan : Please share the log file of a transformation + share what get's added to the target page. Also check the referenced HTML pages, where do they live and do they contain JavaScript (presence of a <script> tag). If there's script in the HTML then this can only be translated using a custom 3rd party script editor solution, see https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-webparts#enabling-the-use-of-the-community-script-editor-web-part-to-be-used-during-transformation and  https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-webparts#contenteditorwebpart-web-part

**Comment by PrasadMadhavan** [comment]
Thank you, I have emailed you the details.

**Comment by jansenbe** [comment]
@PrasadMadhavan : Are you really sure you're using a content editor web part? Put the source page in edit mode and check if it's a content editor web part pointing to a file. Also please share the locations of the page **and** the location of the file loaded by the content editor web part + a copy of such a file loaded by the content editor web part

**Comment by PrasadMadhavan** [comment]
Hi Bert, it is not a content editor webpart. This is a page where I can add html directly on to the page content section of a page. I guess it is called a page content control. Users have embedded html directly in there.  We do have Content editor web parts and those gets copied over with no trouble.  

I see the page is associated with a custom content type. And I can see the content I am looking for under "page properties" as shown below.

![image](https://user-images.githubusercontent.com/25071227/108332081-5301f580-71c7-11eb-8d60-6c9e1a3ad485.png)

**Comment by jansenbe** [comment]
This is a publishing page field with content and should transform just fine, might be there's something wrong in the page layout mapping you're using. Would recommend generating the page layout mappings for the page layouts in your portal and then cross check them (e.g. on the used field names). When doing publishing page transformation the page layouts allow you to control how to transform things, check out https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-model-publishing to learn more about the mapping file

**Comment by jansenbe** [comment]
Also worth while doing is just adding a new source page with a simple piece of text in the page content section and try to transform that one, this way we can rule out something specific in the content to transform.

**Comment by PrasadMadhavan** [comment]
That did the trick! the mapping file helped resolve the issue. There were custom page layouts for which the webpart mappings were not present. I have updated those sections manually on the mapping file and then run the script against that one.  It worked like a charm! I really appreciate your help. Thank you.
