### ISSUE TITLE
GetWebLogin with .NET 4.8

### ISSUE THREAD

**Issue by DenisRouge** [pnp/pnpframework#184]
Hello,
Few weeks ago I about a probleme with a WebLogin problem. Our application try to load a file from sharepoint using the current user credential. As we don't manage the Sharepoint site, we can't use authentication with Azure Application Client Id.
As the old Weblogin method is not available in PnPFramework, you advised to use the one in PnPPowershell. We were able to make it work with this sample program. It is working with NET 5.0 but not with .NET 4.8 (that we use in our application). The error is 403 Unauthorized. 
As far as I checked, it seems that in the GetRequestDigestAsync method a new thread is created in .NET 4.8 (None with .NET 5.0) and that with .NET 5.0 the login windows appears twice (it appears once with .NET 4.8 ).
Could you advise?
[Program.txt](https://github.com/pnp/pnpframework/files/6004978/Program.txt)

**Comment by jansenbe** [comment]
Why are you having this in your code?

```csharp
thread.SetApartmentState( ApartmentState.STA );
thread.Start();
thread.Join();
```

**Comment by DenisRouge** [comment]
It comes from PnP Powershell (WebloginClientContext method in Commands/Utilities/BrowserHelper.cs )

**Comment by jansenbe** [comment]
Don't think that's needed for regular .NET code

**Comment by DenisRouge** [comment]
I tried but a WebBrowser is created and it should be in within STA ApartmentState thread.

**Comment by jansenbe** [comment]
Maybe better to use this syntax in your console app

[STAThread]
static void Main()
{

}

**Comment by DenisRouge** [comment]
I added the STAThread attribute and removed the 3 lines you highlighted. I still have the 403 error.

**Comment by DenisRouge** [comment]
Hello, 
I am just checking if by any chance you have more idea about my problem.

**Comment by DenisRouge** [comment]
Hello,
Did you have the time to check about my problem?

**Comment by jansenbe** [comment]
@DenisRouge : sorry, but I've not. I've been too busy with my day to day job and have not had time to debug your code. Maybe someone else in the community has some more bandwidth?

**Comment by Dr-Oli** [comment]
Similar problem here. Randomly, when using GetWebLogon, I am getting different error messages like 403 Forbidden,  Cannot invoke HTTP DAV request. There is a pending query, ... in my case under .NET 4.6.1
