### ISSUE TITLE
New-PnPSite errors that a suffix is required when the user has rights to create groups without a suffix  

### ISSUE THREAD

**Issue by marcgoff** [pnp/pnpframework#187]
I'm new to the PnP.Powershell module so I might be misunderstanding the issue. 

The user account I am using to provision a new Team site has the Azure user admin role required to not require a group prefix or suffix.
The following command works with no issues.
`New-AzureADMSGroup -Description "Marc Goff test group 002" -DisplayName "Marc Goff Test Group002" -GroupTypes "Unified" -MailEnabled $True -MailNickname "MarcGofftestGroup002" -SecurityEnabled $False`

The group and site are created.

When I try and use New-PnPSite with the folllwing code:
`New-PnPSite -Type TeamSite -Title "USM - Marcs PnP Test Site" -Alias "USM-MarcsPnPTestSite2" -Description "Test site"`
I get the following error:

`New-PnPSite: {"error":{"code":"-1, System.Data.Services.Client.DataServiceClientException","message":"{\"odata.error\":{\"code\":\"Request_BadRequest\",\"message\":{\"lang\":\"en\",\"value\":\"The property is missing a required prefix/suffix per your organization's Group naming requirements.\"},\"requestId\":\"50fb98f6-48fd-4648-91e1-d8662b3b9ac7\",\"date\":\"2021-02-22T23:18:58\",\"values\":[{\"item\":\"PropertyName\",\"value\":\"displayName\"},{\"item\":\"PropertyErrorCode\",\"value\":\"MissingPrefixSuffix\"},{\"item\":\"SuggestedPropertyValue\",\"value\":\"USM - Marcs PnP Test Site 2_O365\"}]}}"}}`

Adding "_O365" to the display name and alias per our naming policy allows New-PnPSite to work.

I am on PnP.Powershell version 1.3.0 running on Powershell 7.1.2 on Windows 10.

**Comment by jansenbe** [comment]
Hi @marcgoff, we're not doing any specific prefix/suffix checking, this error comes from the API call that creates the site. If you're allowed to create sites bypassing the naming policy and SharePoint is not respecting that I would advise to log a bug with Microsoft via your regular support channel.

**Comment by marcgoff** [comment]
What API call are you making? I expect I would need to provide that to MS.

**Comment by jansenbe** [comment]
_api/GroupSiteManager/CreateGroupEx
