### ISSUE TITLE
[Bug] ConvertTo-PnPPage hidden webparts

### ISSUE THREAD

**Issue by FredrikEkstroem** [pnp/pnpframework#194]
### Expected behavior 
Hidden webparts should not be visible/included after converting the page

### Actual behavior 
Hidden webparts are visible on new page after running the ConvertTo-PnPPage command
**SP 2016 publishing page**
![image](https://user-images.githubusercontent.com/17882290/109274871-478c7b00-7814-11eb-9bb8-fd0fe70ac127.png)
**SP Online after running ConvertTo-PNPPage**
![image](https://user-images.githubusercontent.com/17882290/109275014-74409280-7814-11eb-93d8-453568642b22.png)

The webpart xml setting determining if it's hidden
```xml
<IsVisible>true</IsVisible>
```

### Steps to reproduce behavior

- Add a SP2016 Publishing page
- Add a CEWP to a webpart zone
- Hide the webpart under WP Settings/Layout/Hidden
- Publish the page
- Run conversion

```powershell
$Global:Target = Connect-PnPOnline -Url $targetAbsolute -ReturnConnection -Credentials "migrationaccount";
$Global:Source = Connect-PnPOnline -Url $sourceAbsolute -TransformationOnPrem -ReturnConnection -Credentials "sourcecred";
$newPage = ConvertTo-PnPPage -Identity hidden.aspx -ErrorAction Stop -TargetPageName hidden.aspx -PublishingPage -Overwrite -TargetConnection $global:target -Connection $global:source;
```

### What is the version of the Cmdlet module you are running?
PnP.Powershell 1.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows

**Comment by jansenbe** [comment]
@FredrikEkstroem : think the best way forward is offering an option to skip hidden web parts. I've added this to the backlog, since this is a fairly simple one I think I can get it done soon.

**Comment by FredrikEkstroem** [comment]
@jansenbe That would be great solution. Ping me here when it's included in nightly build and I'll test it

**Comment by jansenbe** [comment]
@FredrikEkstroem : implemented, next nightly version of PS supports the -SkipHiddenWebParts parameter for this purpose.
