### ISSUE TITLE
Invoke-PnPSiteTemplate adds blank line above Heading 1 text in Text Web Parts

### ISSUE THREAD

**Issue by ericpskl** [pnp/pnpframework#197]
**Summary of issue:**  

When creating or updating a SharePoint Online page using Invoke-PnPSiteTemplate, an extra line of whitespace is added above "Heading 1" text.

Version:

```
Get-InstalledModule -Name PnP.Powershell

Version    Name                                Repository           Description                                                                                                                                                             
-------    ----                                ----------           -----------                                                                                                                                                             
1.3.0      PnP.PowerShell                      PSGallery            Microsoft 365 Patterns and Practices PowerShell Cmdlets                                                                                                                 

```

**Steps to reproduce:**

Create a new Modern page in SharePoint online.  Add a single Text web part, with one line of text formatted as Heading 1.  

![initial](https://user-images.githubusercontent.com/15313023/109421881-32942100-79a7-11eb-9ce6-a17f0b502720.png)

Export this page to XML:
`Export-PnPPage -Identity Test-Page-12345.aspx -Out Test-Page-12345.xml -Force
`

Inspect the XML template and confirm that there is no extra blank line present in the webpart's XML:

`<pnp:CanvasControlProperty Key="Text" Value="&lt;h2&gt;There is no whitespace before this sentence (Heading 1)&lt;/h2&gt;&lt;p&gt;&lt;br&gt;&lt;/p&gt;" />`

Apply  the XML as a template (this will overwrite the page):
`Invoke-PnPSiteTemplate -Path .\Test-Page-12345.xml
`

Load the page and observe that a blank line has been inserted above the "Heading 1" formatted text.  (It is easier to see the extra space by going into Edit mode on the page)

![after2](https://user-images.githubusercontent.com/15313023/109422207-9539ec80-79a8-11eb-9d0f-1ed65e15ea78.png)

Any suggestions appreciated!

**Comment by jansenbe** [comment]
Known bug that I need to fix. All text are wrapped in a P element when being added via the API, but when there a H then that's not needed. The extra P causes the line break you see I think

**Comment by ericpskl** [comment]
Thanks @jansenbe

**Comment by jansenbe** [comment]
@ericpskl : just fixed this one, will be part of the next nightly of PnP Framework and PnP PowerShell

**Comment by ericpskl** [comment]
Thanks @jansenbe !!!
