### ISSUE TITLE
Where is/equivalent to Microsoft.SharePoint.Client.TenantExtensions.GetOneDriveSiteCollections?

### ISSUE THREAD

**Issue by christophwille** [pnp/pnpframework#2]
We decided to take an early plunge and try to port our codebase over to PNP Framework (from 3.17.2001.2). We have the following code:

`tenant.GetOneDriveSiteCollections();`

This uses the mentioned extension method in the "old" PnP-Sites-Core. Is this an intentional change / omission, how to properly replace this? (is there a Wiki/something else with "breaking changes" or "you should use y instead of x going forward"?)

**Comment by jansenbe** [comment]
That one used the old ASMX web services, so not a future proof model. The `Tenant.GetSiteCollections` method is better suited for this need. You need to set the optional `includeOD4BSites` parameter to true to also get OneDrive site collections

**Comment by christophwille** [comment]
Thanks, I will give that a try (it is a dead code path in our current implementation, but I saw that it was missing on porting so I reported it).
