### ISSUE TITLE
Modernization: webpartmapping.xml File not created

### ISSUE THREAD

**Issue by mmohamedbasith** [pnp/pnpframework#200]
After installing Install-Package PnP.Framework -Version 1.2.0 , webpartmapping.xml and webpartmapping_latestfrompackage.xml are not created in the solution.

**Comment by jansenbe** [comment]
@mmohamedbasith : That's correct, please get the latest webpartmapping.xml from source code: https://github.com/pnp/pnpframework/blob/dev/src/lib/PnP.Framework/Modernization/webpartmapping.xml
