### ISSUE TITLE
PnP.Framework 1.2.19.0 has no strong name

### ISSUE THREAD

**Issue by EA12** [pnp/pnpframework#201]
Getting a warning in VS 2019:
Warning	CS8002 The referenced Assembly "PnP.Framework, Version=1.2.19.0, Culture=neutral, PublicKeyToken=null" does not have a strong name.

I am using the latest nuget package

**Comment by jansenbe** [comment]
@EA12 : we moved away from strong naming our assemblies, the official releases are signed but none of the releases are strong named anymore. I've not yet bumped into this warning, are you using the default code analysis settings?

**Comment by EA12** [comment]
yes, default settings from a fresh install of VS 2019.
Unhandled Exception occurs, if I start the console application, complaining about assembly with strong name is mandatory.
Code Analysis outputs the mentioned warning. See Screenshots:

![pnpframework](https://user-images.githubusercontent.com/22025808/109792591-f44f6980-7c13-11eb-8612-518303775c6c.png)

**Comment by jansenbe** [comment]
Is your application using PnP Framework strong named?

**Comment by EA12** [comment]
no, strong name porperty of PnP.Framework is False

**Comment by jansenbe** [comment]
Are you somehow blocked by not having this strong named? We'll re-evaluate whether we should strong name PnP Framework and PnP Core SDK. Thanks for raising this issue @EA12

**Comment by EA12** [comment]
no, I don't think so:

![notstronglynamed](https://user-images.githubusercontent.com/22025808/109806973-9e83bd00-7c25-11eb-8871-af462102a9b1.png)


Thanks for diggin into it.

**Comment by jansenbe** [comment]
Did some checking and for now we're not going to strong name our binaries...since we've internal dependencies it would imply that  everything will need to be strong named, which is not something we can do right now.

**Comment by dohly** [comment]
Hello! Recently I migrated my desktop app (.net 4.7.2) from SharepointPnpCoreOnline to PnP.Framework. Now I have to solve this issue, because at runtime I'm always getting "Could not load file or assembly 'PnP.Framework'....A strongly named assembly is required'
I tried [StrongNamer ](https://github.com/dsplaisted/strongnamer) nuget package, but it doesn't solve the issue.
My application is strong named and signed.
Please, help me. Thanks!

**Comment by sambetts** [comment]
I have got a solution with a strong name & this change from the previous library has meant I've had to turn it off. Not a biggie, but still unexpected. Strong-naming is a good practise if you can implement it.

**Comment by jansenbe** [comment]
@EA12, @sambetts , @dohly : the next nightly build of PnP Framework will be strong named
