### ISSUE TITLE
Get-PnPSiteTemplate crashes on ampersand in Client Side Page filename: An error occurred while parsing EntityName. Line 1, position 1729.

### ISSUE THREAD

**Issue by mpiederiet** [pnp/pnpframework#202]
Get-PnPSiteTemplate crashes on ampersand in Client Side Page filename

**Expected behavior**
Execute without issue, exporting the Client Side Page to the template (which worked in the, now deprecated, Get-PNPProvisioningTemplate)

**Actual behavior**
1. Error message:
Get-PnPSiteTemplate: An error occurred while parsing EntityName. Line 1, position 1729
2. No template was exported

**Steps to reproduce behavior**
1. Create a client side page, containing an ampersand (e.g. _Tips&Tricks.aspx_)
2. Invoke the Get-PnPSiteTemplate cmdlet, including the Client Side Pages
`Get-PnPSiteTemplate -Out .\test.pnp -Connection $SourceConnection -IncludeAllClientSidePages`
3. The command will crash with an error message (progress screen screenshot made just before the crash):
![image](https://user-images.githubusercontent.com/11026359/109675483-23180200-7b78-11eb-9367-4511108cd9aa.png)
Error message:
**_Get-PnPSiteTemplate: An error occurred while parsing EntityName. Line 1, position 1729._**

**What is the version of the Cmdlet module you are running?**
```
Get-Module PnP.PowerShell -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending

Name           Version
----           -------
PnP.PowerShell 1.3.16
PnP.PowerShell 1.3.0

```

**Which operating system/environment are you running PnP PowerShell on?**
Windows

**Exception**
```
Get-PnPException

Message          : An error occurred while parsing EntityName. Line 1, position 1729.
Stacktrace       :    at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in D:\a\powershell\powershell\src\Commands\Base\PnPSharePointCmdlet.cs:line 70
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 1
```

**Comment by jansenbe** [comment]
Thanks for reporting this @mpiederiet , I'll have a look

**Comment by jansenbe** [comment]
@mpiederiet : Bug has been fixed, next nightly of PnP Core SDK, PnP Framework and PnP PowerShell will have the fix included.

**Comment by mpiederiet** [comment]
Thanks @jansenbe. I was reviewing this change:
https://github.com/pnp/pnpcore/blob/7ffd3838e5093595d3e4584efabf17bfb816fbab/src/sdk/PnP.Core/Model/SharePoint/Pages/Internal/Page.cs#L1805
`return pageName.Replace(" ", "-").Replace("#", "-");`
How is this going to handle "&" differently? Shouldn't this be:
`return pageName.Replace(" ", "-").Replace("#", "-").Replace("&", "-");`

**Comment by jansenbe** [comment]
No, the & wil just appear in the filename. The issue was in the code that we used to lookup the page

**Comment by mpiederiet** [comment]
OK, thanks for the swift response!
