### ISSUE TITLE
Cannot get ClientContext with the error "The request body must contain the following parameter: 'client_assertion' or 'client_secret'"

### ISSUE THREAD

**Issue by tvkien** [pnp/pnpframework#203]
Hi team,

I've tried to create a modern site connection using PnP.Framework, but I always got the error in the method GetContext
"The request body must contain the following parameter: 'client_assertion' or 'client_secret'". Look like I miss passed the Client Secret into request, but I don't see any constructor init the AuthenticationManager have the ClientSecret property

I used the method below to authenticate
var authManager = new AuthenticationManager("<Azure AD client id>", "joe@contoso.onmicrosoft.com", "Pwd as SecureString");

using (var context = authManager.GetContext("https://contoso.sharepoint.com"))
{
    
}

The issue here
![image](https://user-images.githubusercontent.com/63444197/109771981-0808c900-7c30-11eb-9ac8-d64e636bc9ce.png)

Anyone can help me and feel free to let me know the wrong. Thanks

**Comment by jansenbe** [comment]
Hi @tvkien , please check this: https://github.com/pnp/pnpframework/blob/dev/docs/MigratingFromPnPSitesCore.md

**Comment by jansenbe** [comment]
Closing this one, user name + pwd auth should work. If not please open a new issue after you've followed the shared guidance
