### ISSUE TITLE
Missing WebPartType Stream

### ISSUE THREAD

**Issue by MattiaBonanni** [pnp/pnpframework#207]
Hello,

I'm trying to build a new SharePoint page through a netcore5.0 console application with PnP.Framework 1.1.0 but I can't find a way to add a WebPart of type Stream, since PnP WebPartType enum contains only VideoEmbed.

For what I've seen Stream and VideoEmbed share the same GUID, so even with a WebPartType.Custom and the GUID I'm ending up with a VideoEmbed.

I'm missing something? If not, there's a way workaround?
Thanks

**Comment by jansenbe** [comment]
Hi @MattiaBonanni,

You need to use the VideoEmbed webpart type for Stream:
![image](https://user-images.githubusercontent.com/7451219/110146743-3676d780-7ddb-11eb-8019-c8c624b2b97e.png)

This corresponds with GUID 275c0095-a77e-4f6d-a2a0-6a7626911518 in our code, I don't see any duplicate GUIDs here. See https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core/Model/SharePoint/Pages/Internal/Page.cs#L2228 for the used code.

**Comment by MattiaBonanni** [comment]
Hi @jansenbe,

thanks for the reply.
I probably didn't express myself correctly. 

If I use the WebPartType.VideoEmbed the results on my SharePoint Page is this:
![image](https://user-images.githubusercontent.com/18743919/110149579-84410f00-7dde-11eb-868e-c6ee2d1d8ad7.png)

But, if I understand correctly, this WebPart will be retired soon.

The WebPart I want to add is the following:
![image](https://user-images.githubusercontent.com/18743919/110149735-af2b6300-7dde-11eb-9619-81411487feba.png)

With "same GUID", I didn't mean a duplicate in the code base, but that inspecting the SharePoint page with a tool (React Develop Tool for FireFox) I can see that both WebPart share the same GUID:
![image](https://user-images.githubusercontent.com/18743919/110150082-16491780-7ddf-11eb-8dc3-2bf3a484e437.png)
![image](https://user-images.githubusercontent.com/18743919/110150128-26f98d80-7ddf-11eb-8722-d8ef46b26f3f.png)

**Comment by jansenbe** [comment]
@MattiaBonanni :  this is not actually a bug, SharePoint will automatically pick the web part based upon the configuration date provided...if no configuration data provided the old video embed is selected, but when you create a configured default stream web part it shows up as stream web part. See this test for a sample: https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Test/SharePoint/PagesTests.cs#L766. Also see https://pnp.github.io/pnpcore/using-the-sdk/pages-webparts.html#working-with-web-parts to learn more on how you can work with web parts on pages

**Comment by MattiaBonanni** [comment]
@jansenbe thank you so much!
