### ISSUE TITLE
Future of On Prem SharePoint?

### ISSUE THREAD

**Issue by fowl2** [pnp/pnpframework#21]
I'm not really sure if this is the right place for this, but here goes...

* [SharePoint 2019 will still be supported until at least 2026](https://docs.microsoft.com/en-gb/sharepoint/product-servicing-policy/updated-product-servicing-policy-for-sharepoint-2019).
* Microsoft [hasn't](https://techcommunity.microsoft.com/t5/sharepoint/is-sharepoint-server-2019-final-version/td-p/400546) announced that SharePoint 2019 is the last version of SharePoint on-prem
* "PnP-Sites-Core" aka SharePointPnPCore is going to completely stop development in December 2020

Now I understand that the CSOM libraries have effectively forked into Online and OnPrem versions and whether this is permanent, just until a hypothetical next version of SharePoint on-prem is released, or something else is unknown. However the on-prem CSOM remains a viable target for development and supporting existing development given the sizable installed base and investments.

I'd really like to understand the intended path forward here. 

Could I humbly suggest that instead of a full shutdown, the project go into a "community only" mode so that bugfixes aren't siloed and workarounds ossified. It's already a separate repo on github, which can help keep the effort from interfering with the "new hotness" pnpframework.

**Comment by waaromikniet** [comment]
We also use 2019 on-prem. Why is the support for on-prem discontinued?

**Comment by jansenbe** [comment]
Hi @fowl2 , @waaromikniet ,

SharePoint On-Premises is indeed still supported and if you need that for your business than there's absolutely nothing wrong with that. We're not planning to take away the versions that support SharePoint On-Premises, both the PnP-Sites-Core nuget packages for on-premises and the PnP PowerShell versions for on-premises will stay available for you to use. 

The key difference is that we'll not be actively maintaining these going forward, in ideal world we should do that but reality has taught us that we have limited resources to support all of this. By switching to SPO only, we do enable our customers to use the current library (PnP Framework = PnP Sites Core) on .NET core supported platforms which was the top community ask. This switch also enables us to renew our .NET based components and tools via a seamless transitioning from PnP Framework to PnP Core SDK. We've carefully considered this decision as we knew it would impact on-premises customers, but given our current working model the PnP team has chosen this path as our way forward.

Above explains the why, but does not help you if you're still on on-premises, so what options do you have:

- First of all the on-premises API's don't change with SP's and cumulative updates: so things that work today with PnP will stay working. So if PnP Sites Core does the job for you today then it should do as well tomorrow
- If you want to add something new or fix a bug, you can always fork the PnP-Sites-Core repository and create your private build

Hope this helps clarify things.

**Comment by jansenbe** [comment]
Closing this one as the question has been answered
