### ISSUE TITLE
[BUG] ConvertTo-PnPPage : Index was out of range. Must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by wbrown0389** [pnp/pnpframework#210]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Problem Area

[x ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Modernize classic page Home.aspx. 

#### Observed Behavior

Modernization fails with error:

ConvertTo-PnPPage : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
At line:1 char:1
+ ConvertTo-PnPPage -Identity "Home.aspx" -Overwrite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPPage], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.ConvertToClientSidePage

#### Steps to Reproduce

Files attached.

[debug.txt](https://github.com/pnp/sp-dev-modernization/files/6109956/debug.txt)
[powershelloutput_030921.txt](https://github.com/pnp/sp-dev-modernization/files/6109958/powershelloutput_030921.txt)

**Comment by jansenbe** [comment]
@wbrown0389 : this error typically happens because the wiki html was manually crafted resulting in an error detecting the actual used layout. The code that detects the layout is here: https://github.com/pnp/pnpframework/blob/dev/src/lib/PnP.Framework/Modernization/Pages/WikiPage.cs#L166. Looking into the wiki content you've shared I see definitions for a three columns with header page and a two columns with header page...remove the span that's wrong and that should fix your issue.

![image](https://user-images.githubusercontent.com/7451219/110558286-7d99fb00-8142-11eb-8d5a-21be999ec295.png)

**Comment by wbrown0389** [comment]
Thanks for the feedback. We have several pages that experienced this same error, but I'm working through them to identify if all are actually the same problem. Is there a way to edit the wiki HTML for a SPO site without using SP Designer? The affected sites happen to be in the Government cloud, which doesn't allow execution of custom scripts, so SP Designer cannot be used to connect to them.

**Comment by jansenbe** [comment]
You can use PnP PowerShell, below snippet copies the content from your clipboard and then populates the wikifield with that content:

```powershell
# Check the id of your home.aspx page first
$p = Get-PnPListItem -List sitepages -Id 1
# copy contents into clipboard
$p.FieldValues["WikiField"] | clip

# edit content

# push content back into list item
$content = Get-Clipboard -Raw
Set-PnPListItem -List sitepages -Identity 1 -Values @{"WikiField"=$content}

```

**Comment by jansenbe** [comment]
If you put the page in edit mode in SP, what kind of layout do you see?

**Comment by wbrown0389** [comment]
Sensitive info obscured. Two images since the page is longer. This page
reflects the lower span tag being removed.

[image: image.png][image: image.png]

**Comment by jansenbe** [comment]
Don't see the images, but if you can describe that's good as well (like 2 column + header , or 3 column + header and footer,...)

**Comment by wbrown0389** [comment]
![image](https://user-images.githubusercontent.com/80348256/110677511-dc8b5e80-819a-11eb-934b-756a4a2ee19e.png)
![image (1)](https://user-images.githubusercontent.com/80348256/110677512-dc8b5e80-819a-11eb-8175-15e9227f888e.png)

**Comment by jansenbe** [comment]
@wbrown0389 : I see what happened...that page got manually edited resulting in a layout model that's not an "official" wiki page layout. You'd need to update this layout to match a known one (https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-layout#wiki-page-layout-mapping) which you can do in above sample by choosing the "Three columns with header and footer" layout and then moving the QMS listview web part to the footer section. Once that's done ensure that in the raw html there's "true,true,3" as value in the span indicating the chosen layout.

Alternative approach would be to migrate these pages by hand.

**Comment by wbrown0389** [comment]
Did that and confirmed the span tag reflects true,true,3, but issue persists, unfortunately. New files attached. Anything else jump out at you?

[powershelloutput_031121.txt](https://github.com/pnp/pnpframework/files/6124671/powershelloutput_031121.txt)
[debug3.txt](https://github.com/pnp/pnpframework/files/6124672/debug3.txt)

**Comment by jansenbe** [comment]
Manually fixing the html is quite hard...probably it's easier to recreate this home page as a new modern page and put the web parts on them with the needed configuration. Sometimes the issues in the source HTML are minimal, but here fixing the source HTML outweighs the work to manually create the page as modern page in my view.

**Comment by jansenbe** [comment]
Hi @wbrown0389 : I'm closing this issue as there's nothing more we can do from our side besides the given recommendations.
