### ISSUE TITLE
[BUG] When adding SearchNavigationNodes with a template via Invoke-PnPSiteTemplate, existing nodes are being removed

### ISSUE THREAD

**Issue by Ralmenar** [pnp/pnpframework#213]
Summary of issue:

When applying a template than contains something like this: 
![image](https://user-images.githubusercontent.com/38034925/110614728-ead57c80-8192-11eb-89ba-915e911b5093.png)

The following message appears in the PowerShell console: 
![image](https://user-images.githubusercontent.com/38034925/110615246-84049300-8193-11eb-8868-a200a2e8aa8e.png)

Which is removing old existing navigation nodes despite the parameter RemoveExistingNodes is set to false and the Switch parameter "-ClearNavigation" is not present when running the command, and also is duplicating the new node like this:

![image](https://user-images.githubusercontent.com/38034925/110615765-0c833380-8194-11eb-92b9-f21178d44260.png)

Version:
![image](https://user-images.githubusercontent.com/38034925/110615945-42c0b300-8194-11eb-8161-3f17e3b05b97.png)

**Comment by jansenbe** [comment]
Looking at the code there indeed was a bug, I've updated the code to follow the same 'delete' logic as for structural navigation. Please retest with tomorrow's nightly version of PnP PowerShell and if the problem still persists re-open this issue
