### ISSUE TITLE
Using CredentialManager to authenticate

### ISSUE THREAD

**Issue by waaromikniet** [pnp/pnpframework#22]
Will it remain possible to use credentials in the CredentialManager to connect to SharePoint online to use with the provision engine? 
And what about when basic authentication is turned of for SharePoint online?

**Comment by jansenbe** [comment]
Hey @waaromikniet ,

Using credential manager is still supported, the code is still in PnP Framework and the new PnP PowerShell also supports that. Since we're only using OAuth based flows (no cookie auth) we're not impacted anymore by how basic auth is configured in a tenant.

**Comment by waaromikniet** [comment]
I am asking this because currently I am using the latest version of PnP-PowerShell with the credential manager I see these requests

![image](https://user-images.githubusercontent.com/16294209/98937594-e8b22880-24e6-11eb-952d-9d810bbd6d54.png)

This is still cookie based or not? The same as when I build a clientcontext using SharePointOnlineCredentials (SharePoint Online Active Authentication) So I don't see the oauth flow back in Fidler and that's why I am concerned about the legacy authentication with the new framework

**Comment by jansenbe** [comment]
So you're using https://github.com/pnp/powershell? You can easily see if this is cookie based or not, in the requests have an authorization header and no cookie then they're using OAuth

**Comment by waaromikniet** [comment]
Yes I am using the latest version from https://github.com/pnp/powershell
I see this cookie being send: "SPOIDCRL" And no authorization header.
So this is cookie based when using credential manager? Or can also oauth flow be used when using credential manager?

**Comment by jansenbe** [comment]
That's strange...can you add the -verbose statement to your `connect-pnponline` cmdlet and check the outputted version. Feels like you're still using an older version. 

Adding @erwinvanhunen

**Comment by waaromikniet** [comment]
I'm using version 3.26.2010.0 (October 2020 release)
And executing Connect-PnpOnline -Url <myurl.sharepoint.com>
And it gets the credentials from the credential manager.

This results in 

![image](https://user-images.githubusercontent.com/16294209/98962659-258e1780-2507-11eb-96a5-e7bfeeea40c1.png)

This gives me the SPOIDCRL authentication cookie.

**Comment by waaromikniet** [comment]
To test if it has something to do with PNP I tested with SPO Management shell
When I connect with the SPO Management shell (Connect-SPOService -url <my admin url> -Credentials (Get-Credential)) I see exactly the same request being made to rst2.srf and idcrl.svc

**Comment by jansenbe** [comment]
You're still using the wrong PS version, the new one is the 0.x range: https://www.powershellgallery.com/packages/PnP.PowerShell/0.2.4-nightly

**Comment by waaromikniet** [comment]
I wasn't aware of this new version. I'm going to test it.
When we disable legacy authentication does cookie authentication stop working?

**Comment by jansenbe** [comment]
Yes

**Comment by waaromikniet** [comment]
On my personal development tenant the new PowerShell module works fine and as expected. Is using the PnPManagement app registration the only way it can be used? On my company tenants I'm not allowed by the security department to add this registration to my account.
