### ISSUE TITLE
Logs on the modern page after running the PNP PowerShell transformation script

### ISSUE THREAD

**Issue by ayadagir** [pnp/pnpframework#224]
We see some logs saying "Webpart was not transformed" on the modern page after the transformation.

Is there anyway that we can restrict that not to write anything on page as we have the information in logs.

Regards,
Anil

**Comment by jansenbe** [comment]
Hi @ayadagir ,

In the default web part mapping non mapped web parts are put on the page like that. You can update the mapping to work around and not show anything for unmapped web parts, what you need to do is define an empty mapping for these web parts that you do not want to be transformed and not show up.

Defining an empty mapping means adding this:

```xml
<Mappings>
          <!-- Empty mapping as this feature does not work anymore in SPO -->
          <Mapping Default="true" Name="default"></Mapping>
        </Mappings>
```

Here's an example:

```xml
<!-- UserCode web part (sandbox web part)-->
      <WebPart Type="Microsoft.SharePoint.WebPartPages.SPUserCodeWebPart, Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" CrossSiteTransformationSupported="true">
        <Properties>
          <Property Name="AssemblyFullName" Type="string" />
          <Property Name="SolutionId" Type="string" />
          <Property Name="TypeFullName" Type="string" />
        </Properties>
        <Mappings>
          <!-- Empty mapping as this feature does not work anymore in SPO -->
          <Mapping Default="true" Name="default"></Mapping>
        </Mappings>
      </WebPart>  
```

You  can find the latest mapping file here: https://github.com/pnp/pnpframework/blob/dev/src/lib/PnP.Framework/Modernization/webpartmapping.xml

**Comment by ayadagir** [comment]
Got it Thanks.

Do we need to provide all the details(Version,Publickeytoken,culture) from source? and How can we get those details from source.

**Comment by jansenbe** [comment]
All the existing OOB web parts should already be listed in the web part mapping, if it's a custom built web part you can get the exact name from the binary/source code

**Comment by jansenbe** [comment]
@ayadagir : are you good, if so please close this issue

**Comment by jansenbe** [comment]
Closing this one, please re-open if you're still blocked
