### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ayadagir** [pnp/pnpframework#225]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Problem Area

[* ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ *] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

The page should be transferred as modern page including images after running the ConvertTo-PnPPage script we should get the 

#### Observed Behavior

Images are breaking and Not getting copied from PublishingImages library to Site Assets library after the transformation

#### Steps to Reproduce

We will be able to reproduce this issue only when we try to transform to root site of SPO. We were able to transform successfully to any other site collection except root site

Transform successfully including images : https://company.sharepoint.com/sites/Test
Transforming the pages without images : https://company.sharepoint.com

[Log.txt](https://github.com/pnp/sp-dev-modernization/files/6151683/Log.txt)

#### Submission Guidelines

_Delete this section after reading_

- All suggestions or bugs are welcome, please let us know what's on your mind.
- If you checked the **"Page Transformation: Error during the use of page transformation from PnP PowerShell"** checkbox then please provide:
  - The output you see in your PowerShell session
  - The output generated by calling `Get-PnPException`
  - The PnP PowerShell version. Run `get-module -Name SharePointPnPPowerShellOnline` and copy the version info
- If you checked the **"Page Transformation: Error during the use of page transformation from .Net"** checkbox then please provide:
  - The exact error message you get
  - The stack trace of the error
  - The version of the **SharePointPnP.Modernization.Framework.dll** assembly

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
@ayadagir : is the source site collection a root site collection of the web application? Do you see similar behavior for pages living in other, non root, publishing portals?

**Comment by ayadagir** [comment]
Yes. Source is the root site collection of the web application. We tried even with non root site collections also with the same issue.

We have a requirement to move the pages from root site collection from source to root site collection in target with no luck.

Please advise.
