### ISSUE TITLE
AuthenticationManager: GetSharePointOnlineAuthenticatedContextTenant no longer supported?

### ISSUE THREAD

**Issue by waaromikniet** [pnp/pnpframework#23]
I have some console applications that I use for analyse purposes that used the method GetSharePointOnlineAuthenticatedContextTenant in the AuthenticationManager class. This uses SharePoint Online Active Authentication Flow I think https://docs.microsoft.com/nl-nl/archive/blogs/sharepointdevelopersupport/sharepoint-online-active-authentication

This one is missing in the new framework. What should I use as an alternative?

**Comment by jansenbe** [comment]
GetSharePointOnlineAuthenticatedContextTenant uses cookie based auth, which is not allowed anymore with the .Net Standard CSOM libraries, hence we dropped it.  You can use https://github.com/pnp/pnpframework/blob/dev/src/lib/PnP.Framework/AuthenticationManager.cs#L109, you however need to trust the PnP Management shell Azure AD app or alternatively create your own Azure AD Application and use that. OAuth only works when there's an Azure AD app.

**Comment by waaromikniet** [comment]
Thanks for the explanation. I will investigate further. I have created Azure AD app before so I think that will be my way to go.
