### ISSUE TITLE
ConvertTo-PnPPage  Custom Column mapping is not working

### ISSUE THREAD

**Issue by PrasadMadhavan** [pnp/pnpframework#235]
I am trying to run below command. The page gets copied over successfully. However, the associated metadata columns are not getting copied.

ConvertTo-PnPPage -Identity "File.aspx" -PublishingPage -TargetWebUrl https://*****.sharepoint.com/sites/modernuat/****-OverWrite -PageLayoutMapping "custompagelayoutmapping.xml" -LogType File -LogFolder c:\temp -LogVerbose 

There are custom content types at source. And I did create columns at modern site and mentioned the column mapping on the xml file as shown below. But it didn't work.

<MetaData>
 <Field Name="StarsWWWQualityManager" TargetFieldName="Quality_x0020_Manager" Functions="" />
 <Field Name="StarsWWWRiskOfFinancialLoss" TargetFieldName="Risk_x0020_of_x0020_Financial_x0020_Loss" Functions="" />
</MetaData>

On the page transformation report, this is what I get to see. 

29/03/2021 16:30:06  |  /****/Pages/File.aspx  |   Copying page metadata  |  Skipped copying field:  Quality_x0020_Manager
29/03/2021 16:30:06  |  /****/Pages/File.aspx  |   Copying page metadata  |  Skipped copying field:  Risk_x0020_of_x0020_Financial_x0020_Loss
29/03/2021 16:30:06  |  /****/Pages/File.aspx  |   Copying page metadata  |  Skipped copying field:  Quality_x0020_Manager
29/03/2021 16:30:06  |  /****/Pages/File.aspx  |   Copying page metadata  |  Skipped copying field:  

I have tested against following four column types so far.
1. Single line of text
2.  Choice
3.  Person or Group
4. Managed metadata 

Can you please have a look?

**Comment by PrasadMadhavan** [comment]
Quick update.  -ClearCache did solve the issue for first three column types. Now it is not working only for one column type "Managed Metadata"

**Comment by PrasadMadhavan** [comment]
Quick update. The issue is managed metadata is also identified. It happened due to a multi value settings mismatch between source and destination site. Once i updated the column settings, it started working now. I will continue to test against other column types and close this case if there are no further issues identified.

**Comment by jansenbe** [comment]
Note that there's also term mapping in case that would be needed: https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-termmapping

**Comment by PrasadMadhavan** [comment]
Thank you
