### ISSUE TITLE
Duplicate field name was found

### ISSUE THREAD

**Issue by Kerokk** [pnp/pnpframework#240]
Version: 3.13.1909.0

Starting Monday (10/5/20) whenever a provisioning template (model1) is applied to a new site we get the following error:

A duplicate field name "mee9ebbf66b2406b9f94b5a339e27d1d" was found

I dug into the template (model1) and found that the column the error was referencing was a managed metadata site column.  Something important to note about this column is that it's in our content type hub. After trying to apply the template (model1) a few more times, I would continue to get the duplicate field name error but for different fields, all of which were managed metadata columns in the content type hub.  

So I extracted a model (model2) of the new site and compared it to the model file (model1) I was using and noticed that any column that threw the error had the same StaticName and Name in both files, but different ID's.  What's weird is that other site columns coming from the content type hub in both models, continue to use the same ID, some of which are managed metadata fields.

Finally I extracted a model (model3) of the most recent new site which had the model (model1) applied successfully (9/30/20), and found that the ID's were different between these two model files (model1 v model3) as well.  So sometime between 9/30/20 - 10/5/20 "something" decided to care that the ID's were different.  What that something is, I have no idea : (

So I was wondering if anyone was experiencing the same issue?  Or if someone knew of a solution?

Thanks!
Matt

**Comment by jansenbe** [comment]
Closing this issue as it was created a long time ago while testing against PnP Sites Core. If the issue still persists in PnP Framework and is relevant for you then please create a new issue with updated information.
