### ISSUE TITLE
Reapply template - reorder Content Types

### ISSUE THREAD

**Issue by sympmarc** [pnp/pnpframework#241]
We have a PnP Provisioning Template we are applying to multiple sites. We occasionally make IA changes and want to reapply the template to the existing sites.

One of the things we want to be able to do is reorder the Content Types in a list or library. It appears that in subsequent applications of the template, the order of the Content Types stays the same as when there were first added.

For example, I apply the template, which creates List A with CTs A3, A5, A1 - in that order. (That order made sense with only 3 CTs.) Later, we've added a bunch of new CTs to the template, and we reapply it to List A. Regardless what the order of the CTSs is in the prototype sites we use to export the new template, the CTs in List A stay in the order  A3, A5, A1, with new CTs A2 and A4 added after them. In the new template, we have them in the order A1, A2, A3, A4, A5, but after application, we end up with A3, A5, A1, A2, A4.

Is this something which could be fixed in the engine?

**Comment by jansenbe** [comment]
Closing this issue as it was created a long time ago while testing against PnP Sites Core. If the issue still persists in PnP Framework and is relevant for you then please create a new issue with updated information.

**Comment by sympmarc** [comment]
Seems reasonable. Sure took you a while, though. :)
