### ISSUE TITLE
Apply provisioning template doesn't include Site Pages document library custom field 

### ISSUE THREAD

**Issue by Mykie89** [pnp/pnpframework#242]
Hi,

I have site, where I use Site Pages document library with Category column and I created provisioning template with the following command: 
`Get-PnPProvisioningTemplate -out met-news-template.xml -IncludeAllClientSidePages -IncludeSiteGroups -PersistBrandingFiles -Force`
XML file generated and contains Category column, but if I want to apply template in other site with the following command: 
`Apply-PnPProvisioningTemplate -Path .\met-news-template.xml`
the new Site Pages document library contains the site pages, but Category field is empty and If I create new site page then page properties is empty: "There are no custom properties available to add. Site owners can create properties by adding columns in the Pages library."
Under Library settings Category field is appear.

What could be the problem?
Please help!

Thanks,
Mykie

**Comment by jansenbe** [comment]
Closing this issue as it was created a long time ago while testing against PnP Sites Core. If the issue still persists in PnP Framework and is relevant for you then please create a new issue with updated information.
