### ISSUE TITLE
Taxonomy Fields Customization is not supported

### ISSUE THREAD

**Issue by Laul0** [pnp/pnpframework#244]
# Summary

In the case where we need to configure the advanced properties of Taxonomy Field, the command `Get-PnpProvisioningTemplate` is getting effectively all `Customization` from the `ArrayOfProperty` but the `Apply-PnPProvisioningTemplate` does not take in count this properties.

## Current behavior

When the Taxonomy field is configured to display the full path to the term, the property in accordance with this parameter is correctly exported to the XML file:

```xml
<Customization>
  <ArrayOfProperty>
    ...
    <Property>
      <Name>IsPathRendered</Name>
      <Value xmlns:q7="http://www.w3.org/2001/XMLSchema" p4:type="q7:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">true</Value>
    </Property>
  ...
```

When the Template is applied to the target site, this property is not take in count

## Expected behavior

After applied the Template, all properties should be take in count and configured on the target site

**Comment by jansenbe** [comment]
Closing this issue as it was created a long time ago while testing against PnP Sites Core. If the issue still persists in PnP Framework and is relevant for you then please create a new issue with updated information.
