### ISSUE TITLE
Optional values in TeamTemplate provisioning to create a Team from existing Group

### ISSUE THREAD

**Issue by simonagren** [pnp/pnpframework#245]
Hi, 
I tried to create a Team based on an exisiting Office 365 group using the TeamTemplate option. I used a parameter for the groupId (see the image)
![image](https://user-images.githubusercontent.com/16558321/85697562-2fd78280-b6da-11ea-8b32-e389481943dd.png).
The problem is that since properties Displayname etc are required, I get a 400-error since you cannot supply any of those properties while creating from an Office 365 group.

It would be cool if you found a solution to have the properties as optional. In that scenario I could use my parameter and provision the Team.
Another solution would be to use "MailNickName" (as you have in other places), and then the user doesn't have to add ```"group@odata.bind": "https://graph.microsoft.com/v1.0/groups('{parameter:O365GrpId}')",```. You instead do that from the backend.

So maybe if you are using "MailNickName", you don't have to use any of the other properties?

Just thinking out loud :)

**Comment by jansenbe** [comment]
Closing this issue as it was created a long time ago while testing against PnP Sites Core. If the issue still persists in PnP Framework and is relevant for you then please create a new issue with updated information.
