### ISSUE TITLE
Column Formatting not included for _ModerationStatus (Approval Status)

### ISSUE THREAD

**Issue by AdamAndersson** [pnp/pnpframework#246]
Hi,

On a document library with Content Approval enabled you will get a few new columns such as the Approval Status (_ModerationStatus). Adding Column Formatting on this column I have found that the JSON is not included in the generated PnP Template XML. 

<pnp:FieldRef ID="fdc3b2ed-5bf2-4835-a4bc-b885f3396a61" Name="_ModerationStatus" Required="true" DisplayName="Approval Status" />

On a field which I have created the custom formatting is included in the CustomFormatter section.

**Comment by jansenbe** [comment]
Closing this issue as it was created a long time ago while testing against PnP Sites Core. If the issue still persists in PnP Framework and is relevant for you then please create a new issue with updated information.
