### ISSUE TITLE
Error message when creating team using template

### ISSUE THREAD

**Issue by TazzyMan** [pnp/pnpframework#247]
When I create a team using a provisioning template, and a logger is attached (Log4Net) The following error is reported:

ERROR  Exception while archiving/unarchiving Team with ID ae...16d. Details: Exception while invoking endpoint https://graph.microsoft.com/beta/teams/ae...16d/unarchive..

Since we use the same logging for our system, we identify this as an alert, It doesn't seem to matter which value we supply for the Archived property, the error always seems to appear.

**Comment by jansenbe** [comment]
Closing this issue as it was created a long time ago while testing against PnP Sites Core. If the issue still persists in PnP Framework and is relevant for you then please create a new issue with updated information.
