### ISSUE TITLE
i found a bug

### ISSUE THREAD

**Issue by quantrpeter** [pnp/pnpframework#248]
Hi, i create a communication site, added some text on it, then use pnp provision engine in c# to provision to another clean communication site. After that, all assets cloned successfully except the nav menus become like thiese {res:NavigationNode_0_1031_Title}. Any idea?

![image](https://user-images.githubusercontent.com/50471577/82974510-bed67980-a00c-11ea-9fe0-10fdf4380151.png)

**Comment by jansenbe** [comment]
Closing this issue as it was created a long time ago while testing against PnP Sites Core. If the issue still persists in PnP Framework and is relevant for you then please create a new issue with updated information.
