### ISSUE TITLE
Deploying Teams App no error 

### ISSUE THREAD

**Issue by natpdeee** [pnp/pnpframework#249]
Hi, 

I tried to deploy an app to Teams application catalog by using PnPTenantTemplate and Provisioning Schema 2020/02. The xml template is below:

`<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2020/02/ProvisioningSchema" Author="John Smith" Generator="Human being" Version="1.0" Description="A sample Provisioning document" DisplayName="Sample Provisioning" ImagePreviewUrl="https://sharepointpnp.com/ImagePreview.png">
    <pnp:Teams>
        <pnp:Apps>
            <pnp:App AppId="27d2bec7-2237-486f-87e8-efez7a6c697b" PackageUrl=".\myApp.zip" />
        </pnp:Apps>
    </pnp:Teams>
</pnp:Provisioning>`

There is no error message being thrown but the application is not in the app catalog yet. Even when I tried to change the PackageUrl into something else that doesn't exist, it will still proceed and did not throw any error message. 

I already tried PackageUrl=
"myApp.zip"
"./myApp.zip"
 
When I add the .zip file directly in the teams admin centre/upload custom app, it works fine.

Is there any error handling for deploying teams? How can I deploy the app to the app catalog successfully using the schema?

**Comment by PaoloPia** [comment]
Hi,
In the current version of the provisioning engine we handle apps for Teams. As such I'll file your issue as a bug to investigate.

**Comment by jansenbe** [comment]
Closing this issue as it was created a long time ago while testing against PnP Sites Core. If the issue still persists in PnP Framework and is relevant for you then please create a new issue with updated information.
