### ISSUE TITLE
pnp:Directory cannot apply multiple metadata values to a document

### ISSUE THREAD

**Issue by shurick81** [pnp/pnpframework#250]
I'm trying to use pnp:Directory with a json file that is specified in MetadataMappingFile attribute. when a json file contains just one value for metadata field, it works properly.

```json
{
    "testfolder\\demodoc.pdf":  {
        "VL_KnowledgeTopic":  "7743cc6a-5ddb-4ee3-add0-2748ca39d637"
    }
}
```

it works just fine.
The column settings are configured so that user can select multiple values for any document. However, when I try to use array of values in json,

```
{
    "testfolder\\demodoc.pdf":  {
        "VL_KnowledgeTopic":  ["7743cc6a-5ddb-4ee3-add0-2748ca39d637", "5aecf30d-df84-49d3-ad63-8a6d8e6fc917"]
    }
}
```

it throws an error:

```
Apply-PnPProvisioningTemplate : Unexpected character encountered while parsing value: [. Path '['testfolder\\demodoc.pdf'].VL_Knowled
geTopic', line 9, position 75.
At line:1 char:1
+ Apply-PnPProvisioningTemplate -Path C:\projects\contoso-virtual-libra ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], JsonReaderException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate
```

I also tried like this:

```
{
    "testfolder\\demodoc.pdf":  {
        "VL_KnowledgeTopic":  "7743cc6a-5ddb-4ee3-add0-2748ca39d637,5aecf30d-df84-49d3-ad63-8a6d8e6fc917"
    }
}
```

In this case it does not throw any error but neither sets it any value to this column.

**Comment by jansenbe** [comment]
Closing this issue as it was created a long time ago while testing against PnP Sites Core. If the issue still persists in PnP Framework and is relevant for you then please create a new issue with updated information.
