### ISSUE TITLE
<pnp:SiteCollection /> wait time

### ISSUE THREAD

**Issue by jackpoz** [pnp/pnpframework#251]
As the creation of a site collection by default calls WaitForProvisioningIsComplete with 80 retries and 15 seconds between each try, I would suggest to add a new attribute "Wait = true/false" to <pnp:SiteCollection /> element https://github.com/SharePoint/PnP-Sites-Core/blob/c09e0f0590aada578d6b958b532b396e044ffcd4/Core/OfficeDevPnP.Core/Sites/SiteCollection.cs#L510

This would give the same control to the user that New-PnPSite -Wait switch paramater gives (it's still confusing to people upgrading from PnP September 2019 to November 2019+ that what took a few seconds before now can take up to 20 minutes)

**Comment by jansenbe** [comment]
Closing this issue as it was created a long time ago while testing against PnP Sites Core. If the issue still persists in PnP Framework and is relevant for you then please create a new issue with updated information.
