### ISSUE TITLE
PNP Section type TwoColumnLeftVerticalSection and TwoColumnRightVerticalSection inverted

### ISSUE THREAD

**Issue by moudhafersalhi** [pnp/pnpframework#252]
Hi all,
i was struggling with provisionning the homepage of a communication site.
The generated page had always the wrong section.
It turned out that the provisionning will always create the opposite(between TwoColumnRightVerticalSection and TwoColumnLeftVerticalSection).

`<pnp:Section Order="1" Type="TwoColumnLeftVerticalSection" VerticalSectionEmphasis="Neutral">`
this will generate this : 
`PS C:\SRC\GURU\Prov\GuruOnline\Scripts\Company> $homepage.Sections[0].Type
TwoColumnRightVerticalSection
`
and this : 
`<pnp:Section Order="1" Type="TwoColumnRightVerticalSection" VerticalSectionEmphasis="Neutral">`
will generate this : 
`PS C:\SRC\GURU\Prov\GuruOnline\Scripts\Company> $homepage.Sections[0].Type
TwoColumnLeftVerticalSection
`
Could you please fix this ? it is confusing.

Thank you

**Comment by jansenbe** [comment]
Hi @moudhafersalhi ,

Can you reproduce this issue with the latest bits? If so then please specify a repro template

**Comment by jackpoz** [comment]
Tried with a template with
```xml
<pnp:Section Order="1" Type="TwoColumnRightVerticalSection" VerticalSectionEmphasis="Neutral">
```

and the sections look correct:
![image](https://user-images.githubusercontent.com/1153754/116790118-fbc7ad80-aab2-11eb-8e0c-7053e7419291.png)

and powershell shows the same type as the one defined in the template:
```
[/sites/TestCommunicationSiteBlank] C:\temp> $page = get-pnppage home.aspx
[/sites/TestCommunicationSiteBlank] C:\temp> $page.Sections[0].Type
TwoColumnRightVerticalSection
```

**Comment by jansenbe** [comment]
Thanks for testing this @jackpoz !
