### ISSUE TITLE
Modern page is not renamed when -TakeSourcePageName is used

### ISSUE THREAD

**Issue by KiranTalikoti** [pnp/pnpframework#253]
#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell

#### Expected or Desired Behavior
Post executing script I was, expecting Classic page is expected to be renamed as "Previous_Pagename.aspx" and the modern to be "Pagename.aspx"  after setting the parameter (-TakeSourcePageName) true

#### Observed Behavior
Classic page is named as "Home.aspx" and modern page as "Migrated_Home" after conversion

#### Steps to Reproduce
[
I am trying to execute page transformation script for entire site page library. 
Step1: Entering the Site URL
Step2 :Entering the value for parameter (-TakeSourcePageName) as Previous or Old

Attaching the script used for reproducing this issue. Thank you so much in advance. Your help would be much appreciated.
]

[TransformPageScript_Issue.zip](https://github.com/pnp/sp-dev-modernization/files/6221602/TransformPageScript_Issue.zip)

**Comment by jansenbe** [comment]
@KiranTalikoti : what version of PnP PowerShell are you using? Can you try the operation with logging enabled and share the created log file

**Comment by KiranTalikoti** [comment]
@jansenbe : Sorry for the delayed response. Here is the version of PnP installed in my Win 10 machine..

![image](https://user-images.githubusercontent.com/35056488/113658929-a7512e00-96be-11eb-9beb-351c432ae0ec.png)

**Comment by divya-akula** [comment]
@KiranTalikoti  Update the PowerShell Module , it should help.

**Comment by KiranTalikoti** [comment]
> @KiranTalikoti Update the PowerShell Module , it should help.

yes, updated pnp module and it worked. 
thank you @divya-akula  and @jansenbe  for your help.
