### ISSUE TITLE
Get-PnPSiteTemplate throws SPWeb.ServerRelativeUrl with a renamed site URL

### ISSUE THREAD

**Issue by Vighough** [pnp/pnpframework#257]
I was trying to get a template from a communication site with `Get-PnPSiteTemplate` but it throws the following error when trying to grap the home.aspx:  `Get-PnPSiteTemplate: Server relative urls must start with SPWeb.ServerRelativeUrl`. 

![image](https://user-images.githubusercontent.com/11834321/113305613-83c76580-9303-11eb-9bb3-f97fd4f0d6ed.png)

It probably has to do with a name and URL changing that I did on the site. When adding the `-ExcludeHandlers PageContents` it works:

![image](https://user-images.githubusercontent.com/11834321/113305756-a5c0e800-9303-11eb-8123-fef4edbd21ee.png)

I expected the `Get-PnPSiteTemplate` to still work after a name and site renaming. I have a solution for myself because I can easily add the pages manually. But it would be a problem with a large site. Renaming the site and URL back to original wouldn't work. Is there a solution to this?

Versions and systems used:
PnP.Powershell - 1.5.0
PowerShell - 7.1.3
Windows

**Comment by jackpoz** [comment]
Could you please run `Get-PnPException` and post the result ? it might show something useful in the callstack.

Can you reproduce the issue with a brand new communication site that gets renamed ? I tried creating a communication site, creating a page, changing the URL of the site, running `Get-PnPSiteTemplate` but I didn't get any error.

**Comment by jansenbe** [comment]
Closing per no feedback from the original asker
