### ISSUE TITLE
PnP Framework - Creating a team site with access token fails

### ISSUE THREAD

**Issue by sandeepvootoori** [pnp/pnpframework#264]
Hello,

I am trying to create a Modern Team site using PnP Framework, Azure Function with MSI but it fails with the below error.

I have assigned the below permissions to the Azure Function

![image](https://user-images.githubusercontent.com/40895430/113788226-87475c00-970a-11eb-9c04-cd66ac0f8a53.png)

This works locally when i try to debug but not when deployed as an Azure Function

```
 var azureServiceTokenProvider = new AzureServiceTokenProvider();
string accessToken = await azureServiceTokenProvider.GetAccessTokenAsync("https://tenant.sharepoint.com");
SecureString str = ConvertToSecureString(accessToken);
var authManager = new AuthenticationManager(str);
var context = authManager.GetContext("https://tenant.sharepoint.com");
var teamContext = await context.CreateSiteAsync(
new TeamSiteCollectionCreationInformation
{
Alias = "alias", // Mandatory
DisplayName = "displayName", // Mandatory
Description = "description", // Optional
Classification ="classification", // Optional
IsPublic = false
});
teamContext.Load(teamContext.Web, w => w.Url);
teamContext.ExecuteQueryRetry();
Console.WriteLine(teamContext.Web.Url);
```

System.Exception: App-Only is currently not supported, unless you provide a Microsoft Graph Access Token. at PnP.Framework.Sites.SiteCollection.CreateAsync(ClientContext clientContext, TeamSiteCollectionCreationInformation siteCollectionCreationInformation, Int32 delayAfterCreation, Int32 maxRetryCount, Int32 retryDelay, Boolean noWait, String graphAccessToken, AzureEnvironment azureEnvironment) at Microsoft.SharePoint.Client.ClientContextExtensions.CreateSiteAsync(ClientContext clientContext, TeamSiteCollectionCreationInformation siteCollectionCreationInformation) at resourcerequest_functions.createsitewithtemplate.CreateSite(ClientContext context, ProcessRequest item, ILogger log)

**Comment by jansenbe** [comment]
@sandeepvootoori : app-only based creation of SharePoint sites will go via Microsoft Graph as that's the only option. We'll  create a Microsoft 365 group and as part of the group creation the SharePoint Site is created as well. This then implies you provide a token for graph.microsoft.com...whereas your code seems to request a token for tenant.sharepoint.com

**Comment by jansenbe** [comment]
@sandeepvootoori : you need to specify the graph access token in addition to the context you've created, see the graphAccessToken  parameter below

```csharp
 public static async Task<ClientContext> CreateAsync(ClientContext clientContext, TeamSiteCollectionCreationInformation siteCollectionCreationInformation,
            int delayAfterCreation = 0,
            int maxRetryCount = 12, // Maximum number of retries (12 x 10 sec = 120 sec = 2 mins)
            int retryDelay = 1000 * 10, // Wait time default to 10sec,
            bool noWait = false,
            string graphAccessToken = null,
            AzureEnvironment azureEnvironment = AzureEnvironment.Production
            )
        {
            if (siteCollectionCreationInformation.Alias.Contains(" "))
            {
                throw new ArgumentException("Alias cannot contain spaces", "Alias");
            }

            await new SynchronizationContextRemover();
            if (clientContext.IsAppOnly() && string.IsNullOrEmpty(graphAccessToken))
            {
                throw new Exception("App-Only is currently not supported, unless you provide a Microsoft Graph Access Token.");
            }
```

**Comment by jansenbe** [comment]
Closing per no recent feedback

**Comment by SergiyKostenko** [comment]
Hello,

I am having same issue.
I use PnPFramework 1.6.0.
I get client context via certificaite and clientid,

CreateSiteAsync accepts only one parameter, TeamSiteCollectionCreationInformation. How can I pass graph access token?

Please suggest.
