### ISSUE TITLE
ConvertTo-PnPPage transformation, how do I add OOB page properties webpart to the target page?

### ISSUE THREAD

**Issue by PrasadMadhavan** [pnp/pnpframework#265]
I am doing classic to modern page transformation of over 1000 pages using the command ConvertTo-PnPPage.  I have a customised webpart at source to display page properties. Since I can't migrate that one, I hope to use OOB Page Properties web part at the target page. But I don't know how to specify that on my custompagelayoutmapping file?  Can you please advise?

**Comment by PrasadMadhavan** [comment]
I would really appreciate any input on this one, thank you

**Comment by jansenbe** [comment]
@PrasadMadhavan : see https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-model-publishing#metadata-element. 

![image](https://user-images.githubusercontent.com/7451219/115267634-b19d0e80-a139-11eb-970c-62f61f5483f1.png)

**Comment by PrasadMadhavan** [comment]
That worked! I am now able to display page properties. Thank you once again.
