### ISSUE TITLE
[BUG] ClientSidePage Header always have TextAlignment set to "Center"

### ISSUE THREAD

**Issue by Swampen** [pnp/pnpframework#266]
When I use `Get-PnPSiteTemplate` and include ClientSidePages the, the TextAlignment of the Header is always set to "Center".

The header text is set to align left in SharePoint, and the `Get-PnPClientSidePage` also return left

```powershell
(Get-PnPClientSidePage -Identity Column-Description).PageHeader.TextAlignment
# Left
```

**Comment by jackpoz** [comment]
I created a PR at https://github.com/pnp/pnpframework/pull/297 . Basically the TextAlignment property was exported "flipped", so pages with Left would have Center and pages with Center would have Left (or no value at all, with Left being the default)
