### ISSUE TITLE
Get-PnPSiteTemplate -Out template.xml -PersistBrandingFiles  is not including site logo

### ISSUE THREAD

**Issue by Sagar1213** [pnp/pnpframework#273]
Hi Team,

Get-PnPSiteTemplate -Out template.xml -PersistBrandingFiles.  I am using this commnad to get the PnP template and then applied the template using Invoke-PnPSiteTemplate.

There are 3 scenarios:

1) Modern Team Site with O365 groups- I generated the template using the above command and then I applied the template.  Site logo and site theme not applied.

2) Modern Team Site Without O365 groups:  Site logo applied but site theme not applied.

Please help me why site theme is not getting applied and why site logo not updating in case of team site with O365 groups.

Thanks

Sagar Sharma

**Comment by ArijitCloud** [comment]
I had the same issue, and for now using a work around, after using Invoke command,
Set-PnPWebTheme and Set-PnPWeb to set logo separately.
