### ISSUE TITLE
Get-PnPSiteTemplate takes too long for TEAMCHANNEL#0, SRCHCENTERLITE#0, POINTPUBLISHINGTOPIC#0, POINTPUBLISHINGHUB#0 template types

### ISSUE THREAD

**Issue by sathya-bhat** [pnp/pnpframework#277]
Backing up simple site template of types TEAMCHANNEL#0, SRCHCENTERLITE#0, POINTPUBLISHINGTOPIC#0, POINTPUBLISHINGHUB#0 takes around an hour with 'Handlers=All'. These sites do not have much data. Looking at progress reported, each field appears to take a long time. If I specify 'Handlers=None', it backs up fast, with smaller template size, but this template may not be usable to recover the site in its original form.

Any solution to this slowness without compromising data fields?

`
# Test program to backup Sharepointonline site PnP file.
$AppGuid = ""
$AppSecret = ""
$SiteUrl = "https://x.sharepoint.com/sites/y"  # 'TEAMCHANNEL#0' template type.

# PnP.PowerShell version 1.5.0
Import-Module PnP.PowerShell

$PnPSiteConn = Connect-PnpOnline -url $SiteUrl -ClientId $AppGuid -ClientSecret $AppSecret -ReturnConnection -ea Stop

$Options =@{
  Connection = $PnPSiteConn
  Out = 'c:\temp\sitetemplate.pnp'
  ErrorAction = 'Stop'
  Verbose = $True
  Force = $True
  Handlers = 'All'
  #Handlers = 'None'
 }

$val = Get-PnPSiteTemplate @Options

Write-Host "All Done"
`

**Comment by jansenbe** [comment]
@sathya-bhat : what happens if you only select the fields handler? Is the export then still very slow? 

Note: PnP templates are not designed for full fidelity backups of sites, meaning we export/import quite a lot but not everything.

**Comment by sathya-bhat** [comment]
Interesting observation. I tested against a team channel site: 

If I set following, its fast.

**Handlers = 'Fields'**

If I set the following, its again slow.

  **Handlers = 'All'
  ExcludeHandlers = 'Fields'**
 
 So the slowness is due to some other type.
 
 The slowness is observed in fields like the following:
  _ComplianceTag, TaskOutcome, CompatibleManagedProperties, TemplateId, ManagedPropertyMapping, SMTotalFileCount, TagEventDate, BannerUrl, etc...

**Comment by jansenbe** [comment]
@sathya-bhat : you can use `Set-PnPTraceLog` to enable logging, this will give you a better view on what goes slow. First step to a possible improvement is pinpointing what exactly goes too slow

**Comment by sathya-bhat** [comment]
Unfortunately PnP trace does not give any additional clue. It gets stuck at [Fields] when Handlers= 'All' is specified. The progress report shows each field being extracted.

@jansenbe could you please try to test against following site templates with Handlers='All' from your end? Are you seeing this behavior?

  - team channel
  - https://<tenant>.sharepoint.com/portals/Community 
  - https://<tenant>.sharepoint.com/portals/hub

 
PnP Trace:
`Information: 0 : 2021-04-20 13:21:02.8065	[Extraction]	[9]	[Debug]	Code execution scope started	0ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:02.8065	[Extraction]	[9]	[Debug]	ProgressDelegate registered	0ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:02.8065	[Extraction]	[9]	[Debug]	MessagesDelegate registered	0ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:02.8065	[Extraction]	[9]	[Debug]	PersistBrandingFiles is set to true	0ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:06.3317	[Regional Settings]	[9]	[Debug]	Code execution scope started	0ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:06.8571	[Regional Settings]	[9]	[Debug]	Code execution scope ended	512ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:06.8727	[Supported UI Languages]	[9]	[Debug]	Code execution scope started	0ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:07.3853	[Supported UI Languages]	[9]	[Debug]	Code execution scope ended	507ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:07.4166	[Audit Settings]	[9]	[Debug]	Code execution scope started	0ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:07.9322	[Audit Settings]	[9]	[Debug]	Code execution scope ended	514ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:07.9486	[Site Security]	[9]	[Debug]	Code execution scope started	0ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:10.0092	[Site Security]	[9]	[Debug]	Skipping OOTB role definition Full Control	2066ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:10.0092	[Site Security]	[9]	[Debug]	Skipping OOTB role definition Design	2066ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:10.0092	[Site Security]	[9]	[Debug]	Skipping OOTB role definition Edit	2066ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:10.0092	[Site Security]	[9]	[Debug]	Skipping OOTB role definition Contribute	2066ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:10.0092	[Site Security]	[9]	[Debug]	Skipping OOTB role definition Read	2066ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:10.0092	[Site Security]	[9]	[Debug]	Skipping OOTB role definition Limited Access	2066ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:10.2748	[Site Security]	[9]	[Debug]	Processing Role Assignment Microsoft.SharePoint.Client.RoleAssignment	2328ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:10.2904	[Site Security]	[9]	[Debug]	Processing Role Assignment 

Microsoft.SharePoint.Client.RoleAssignment	2340ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:10.2904	[Site Security]	[9]	[Debug]	Processing Role Assignment Microsoft.SharePoint.Client.RoleAssignment	2340ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:21:10.2904	[Site Security]	[9]	[Debug]	Code execution scope ended	2340ms	c22e8b44-fb00-41fe-a118-356207692a85

**Information: 0 : 2021-04-20 13:21:10.3217	[Fields]	[9]	[Debug]	Code execution scope started	0ms	c22e8b44-fb00-41fe-a118-356207692a85

Information: 0 : 2021-04-20 13:56:50.3426	[Fields]	[9]	[Debug]	Code execution scope ended	2140010ms	c22e8b44-fb00-41fe-a118-356207692a85**

Information: 0 : 2021-04-20 13:56:50.3738	[Content Types]	[9]	[Debug]	Code execution scope started	0ms	c22e8b44-fb00-41fe-a118-356207692a85
`

When I run individual Handlers included in Handlers enum as defined in the document
https://docs.microsoft.com/dotnet/api/officedevpnp.core.framework.provisioning.model.handlers

the template extraction finished fast (103 seconds). With 'All' handlers, it took 4188 seconds.
That means 'All' bitfields includes more that what is defined in the doc. 

Below is the timing when I tried individual handlers and 'All'

 `                                                                                                                                                                                                                                                                                                                                                                                                                                                                  04/20/2021 09:50:07 Getting site template with handler ApplicationLifecycleManagement ... 
                                                                                                                                                 
04/20/2021 09:50:12 Completed site template with handler ApplicationLifecycleManagement . TotalTimeSec = 4.9499144                                                                                                                         

04/20/2021 09:50:12 Getting site template with handler AuditSettings ...                                                                                                                                                                   

04/20/2021 09:50:14 Completed site template with handler AuditSettings . TotalTimeSec = 2.3320598                                                                                                                                          

04/20/2021 09:50:14 Getting site template with handler ComposedLook ...                                                                                                                                                                    

04/20/2021 09:50:17 Completed site template with handler ComposedLook . TotalTimeSec = 2.2434947                                                                                                                                           

04/20/2021 09:50:17 Getting site template with handler ContentTypes ...                                                                                                                                                                    

04/20/2021 09:50:21 Completed site template with handler ContentTypes . TotalTimeSec = 4.3224435                                                                                                                                           

04/20/2021 09:50:21 Getting site template with handler CustomActions ...                                                                                                                                                                   

04/20/2021 09:50:24 Completed site template with handler CustomActions . TotalTimeSec = 3.506886                                                                                                                                           

04/20/2021 09:50:25 Getting site template with handler ExtensibilityProviders ...                                                                                                                                                          

04/20/2021 09:50:26 Completed site template with handler ExtensibilityProviders . TotalTimeSec = 1.8232536                                                                                                                                 

04/20/2021 09:50:26 Getting site template with handler Features ...                                                                                                                                                                        

04/20/2021 09:50:29 Completed site template with handler Features . TotalTimeSec = 2.6329656                                                                                                                                               

04/20/2021 09:50:29 Getting site template with handler Fields ...                                                                                                                                                                          

04/20/2021 09:50:32 Completed site template with handler Fields . TotalTimeSec = 3.1321322                                                                                                                                                 

04/20/2021 09:50:32 Getting site template with handler Files ...                                                                                                                                                                           

04/20/2021 09:50:34 Completed site template with handler Files . TotalTimeSec = 1.80326                                                                                                                                                    

04/20/2021 09:50:34 Getting site template with handler ImageRenditions ...                                                                                                                                                                 

04/20/2021 09:50:37 Completed site template with handler ImageRenditions . TotalTimeSec = 3.0323647                                                                                                                                        

04/20/2021 09:50:37 Getting site template with handler Lists ...                                                                                                                                                                           

04/20/2021 09:51:06 Completed site template with handler Lists . TotalTimeSec = 28.9948105                                                                                                                                                 

04/20/2021 09:51:06 Getting site template with handler Navigation ...                                                                                                                                                                      

04/20/2021 09:51:12 Completed site template with handler Navigation . TotalTimeSec = 6.5010137                                                                                                                                             

04/20/2021 09:51:12 Getting site template with handler PageContents ...                                                                                                                                                                    

04/20/2021 09:51:19 Completed site template with handler PageContents . TotalTimeSec = 6.4624331                                                                                                                                           

04/20/2021 09:51:19 Getting site template with handler Pages ...                                                                                                                                                                           

04/20/2021 09:51:21 Completed site template with handler Pages . TotalTimeSec = 1.9456069                                                                                                                                                  

04/20/2021 09:51:21 Getting site template with handler PropertyBagEntries ...                                                                                                                                                              

04/20/2021 09:51:24 Completed site template with handler PropertyBagEntries . TotalTimeSec = 2.6485657                                                                                                                                     

04/20/2021 09:51:24 Getting site template with handler Publishing ...                                                                                                                                                                      

04/20/2021 09:51:27 Completed site template with handler Publishing . TotalTimeSec = 2.96215                                                                                                                                               

04/20/2021 09:51:27 Getting site template with handler RegionalSettings ...                                                                                                                                                                

04/20/2021 09:51:29 Completed site template with handler RegionalSettings . TotalTimeSec = 2.1563246                                                                                                                                       

04/20/2021 09:51:29 Getting site template with handler SearchSettings ...                                                                                                                                                                  

04/20/2021 09:51:31 Completed site template with handler SearchSettings . TotalTimeSec = 1.8753353                                                                                                                                         

04/20/2021 09:51:31 Getting site template with handler SitePolicy ...                                                                                                                                                                      

04/20/2021 09:51:33 Completed site template with handler SitePolicy . TotalTimeSec = 2.1317509

04/20/2021 09:51:33 Getting site template with handler SiteSecurity ...

04/20/2021 09:51:37 Completed site template with handler SiteSecurity . TotalTimeSec = 3.9848517

04/20/2021 09:51:37 Getting site template with handler SupportedUILanguages ...

04/20/2021 09:51:39 Completed site template with handler SupportedUILanguages . TotalTimeSec = 2.102243

04/20/2021 09:51:39 Getting site template with handler Tenant ...

04/20/2021 09:51:41 Completed site template with handler Tenant . TotalTimeSec = 2.0234836

04/20/2021 09:51:41 Getting site template with handler TermGroups ...

04/20/2021 09:51:43 Completed site template with handler TermGroups . TotalTimeSec = 1.8170087

04/20/2021 09:51:43 Getting site template with handler WebApiPermissions ...

04/20/2021 09:51:45 Completed site template with handler WebApiPermissions . TotalTimeSec = 1.8473321

04/20/2021 09:51:45 Getting site template with handler WebSettings ...

04/20/2021 09:51:48 Completed site template with handler WebSettings . TotalTimeSec = 3.4783797

04/20/2021 09:51:48 Getting site template with handler Workflows ...

04/20/2021 09:51:51 Completed site template with handler Workflows . TotalTimeSec = 3.0027806

Done with individual handlers. TotalSec Taken = 103

04/20/2021 09:51:51 Getting site template with handler All ...

04/20/2021 11:01:40 Completed site template with handler All . TotalTimeSec = 4188
`
