### ISSUE TITLE
Best way to Cache App only token or clientcontext 

### ISSUE THREAD

**Issue by anomepani** [pnp/pnpframework#279]
In dotnetcore core web api we are using apponly token with appid and appsecret. 
 Thousands of request will hitting the api to get some data using app only token.

As for each request it will generating new token and context every time. 
What is best way to cache token or clientcontext? 

What needs to handle to achieve this?

**Comment by jansenbe** [comment]
@anomepani : You'd best cache the tokens (token is per tenant / scope) and only renew then when necessary. https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache/tree/master/1-Integrated-Cache/1-2-WebAPI-BgWorker and https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/token-cache-serialization are good starting points

**Comment by jansenbe** [comment]
MSAL/Microsoft.Identity.Web (as used in above mentioned samples) will handle the caching for you. Closing this issue now

**Comment by fowl2** [comment]
I think my PR #274 might help, what do you think?
