### ISSUE TITLE
ConvertTo-PnPPage transformation, Some pages fails with "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by PrasadMadhavan** [pnp/pnpframework#283]
When I run the above command against some of the pages, it fail with "Object reference not set to an instance of an object". I have attached. I am not able to identify the root cause from the page transformation report.  Attaching the same here for your reference.  Can you please help?  I have attached the page transformation report below.

The command is given below.
ConvertTo-PnPPage -Identity "DRAFT---Issue-TQ-Response.aspx" -PublishingPage -TargetWebUrl https://********sharepoint.com/sites/modernuat/WayWeWork -OverWrite -PageLayoutMapping "custompagelayoutmapping-waywework.xml" -LogType File -LogFolder c:\temp -LogVerbose

Even though it fails, I see the page is created at the destination site, but a summary links web part failed to get copied over.

**Comment by PrasadMadhavan** [comment]
# Modernization Summary Report

Date  |  Duration  |  Source Page  |  Target Page Url  |  Status
-------------  |  -------------  |  -------------  |  -------------  |  -------------
26/04/2021 09:20:08  |  00:00:12  |  [/WayWeWork/Pages/DRAFT---Issue-TQ-Response.aspx](https://******.sharepoint.com/sites/uat/WayWeWork/Pages/DRAFT---Issue-TQ-Response.aspx)  |  []()  |  A issue prevented successful transformation
## Critical Errors during transformation

### 26/04/2021 09:20:20 - [/WayWeWork/Pages/DRAFT---Issue-TQ-Response.aspx](https://******.sharepoint.com/sites/uat/WayWeWork/Pages/DRAFT---Issue-TQ-Response.aspx)

_Object reference not set to an instance of an object.   at PnP.Framework.Modernization.Publishing.PublishingMetadataTransformator.Transform()
   at PnP.Framework.Modernization.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation)_ 

# Individual Page details
## Transformation Details: /WayWeWork/Pages/DRAFT---Issue-TQ-Response.aspx

- Report date: 26/04/2021 09:20:08
- Transform duration: 00:00:12
- Transforming from site: https://******.sharepoint.com/sites/uat/WayWeWork
- Cross-Site transfer mode to site: https://********.sharepoint.com/sites/modernuat/WayWeWork
- Transforming page: /sites/uat/WayWeWork/Pages/DRAFT---Issue-TQ-Response.aspx
- Source SharePoint version:  Online (16.0.0.21207)
- Mode:  Publishing Page Transformation Mode
-  A critical error occurred - transformation did not complete

### Page Transformation Settings

Property  |  Setting
-------------  |  -------------
Engine version   |   1.2.0.0
Overwrite   |   True
Target Page Name   |   
Target Page Folder   |   
Target Page Folder Overrides Default Folder   |   False
Keep Page Specific Permissions   |   True
Remove Empty Sections And Columns   |   True
Handle Wiki Images And Videos   |   True
Add Table List Image As Image Web Part   |   True
Keep Page Creation Modification Information   |   False
Publish Created Page   |   True
Post As News   |   False
Disable Page Comments   |   False
Skip Url Rewrite   |   False
Skip Default Url Rewrite   |   False
Url Mapping File   |   
Term Mapping File   |   
Skip Term Store Mapping   |   False
Skip User Mapping   |   False
User Mapping File   |   
L D A P Connection String   |   
Skip Telemetry   |   False
### Transformation Operation Details

Date  |  Operation  |  Actions Performed
-------------  |  -------------  |  ------------- 
26/04/2021 09:20:08  |  _Input Validation_  |  _Validation checks complete_
26/04/2021 09:20:08  |  _SharePoint Connection_  |  _Loading client context objects_
26/04/2021 09:20:08  |  _SharePoint Connection_  |  _Loading target client context object_
26/04/2021 09:20:08  |  _Page Creation_  |  _Detect if the page is living inside a folder_
26/04/2021 09:20:08  |  Page Creation  |  In Cross-Site transform mode the original source file name is used
26/04/2021 09:20:08  |  _Page Creation_  |  _Just try to load the page in the fastest possible manner, we only want to see if the page exists or not_
26/04/2021 09:20:10  |  Load  |  Page does not exist in current web
26/04/2021 09:20:10  |  Page Creation  |  Checking Page Exists
26/04/2021 09:20:10  |  Page Creation  |  Modern page created 
26/04/2021 09:20:10  |  Article page handling  |  Transforming source page as Article page
26/04/2021 09:20:10  |  Article page handling  |  Recognized source page as a Publishing Page - Analyzing web parts and page layouts
26/04/2021 09:20:10  |  Page Layout Manager  |  Page uses ContentWwW as page layout, mapping that will be used is ContentWwW
26/04/2021 09:20:16  |  Article page handling  |  Splitting images and videos from wiki text - as modern text web part does not support embedded images and videos
26/04/2021 09:20:16  |  Set Page Title  |  Setting the modern page title: DRAFT - Issue TQ Response
26/04/2021 09:20:16  |  _Article page handling_  |  _Preparing content transformation_
26/04/2021 09:20:16  |  Article page handling  |  Transforming content
26/04/2021 09:20:16  |  Content Transform  |  Transforming web parts
26/04/2021 09:20:16  |  Web Part Mapping  |  Web Part:'WikiText' of type 'SharePointPnP.Modernization.WikiTextPart' is being transformed
26/04/2021 09:20:16  |  _Web Part Mapping_  |  _Processing selector functions_
26/04/2021 09:20:16  |  _Web Part Mapping_  |  _Combining mapping data_
26/04/2021 09:20:16  |  Adding Web Parts to Target Page  |  Added 'Client Side Text Web Part' to target page
26/04/2021 09:20:16  |  Web Part Mapping  |  Web Part:'WikiText' of type 'SharePointPnP.Modernization.WikiTextPart' is being transformed
26/04/2021 09:20:16  |  _Web Part Mapping_  |  _Processing selector functions_
26/04/2021 09:20:16  |  _Web Part Mapping_  |  _Combining mapping data_
26/04/2021 09:20:16  |  Adding Web Parts to Target Page  |  Added 'Client Side Text Web Part' to target page
26/04/2021 09:20:16  |  Web Part Mapping  |  Web Part:'' of type 'SharePointPnP.Modernization.PageProperties' is being transformed
26/04/2021 09:20:16  |  _Web Part Mapping_  |  _Processing selector functions_
26/04/2021 09:20:16  |  _Web Part Mapping_  |  _Combining mapping data_
26/04/2021 09:20:16  |  Adding Web Parts to Target Page  |  Using 'PageFields' modern web part
26/04/2021 09:20:16  |  Adding Web Parts to Target Page  |  Added 'Page properties' Client Side Web Part to target page
26/04/2021 09:20:16  |  Content Transform  |  Transforming web parts complete
26/04/2021 09:20:16  |  Article page handling  |  Transforming content complete
26/04/2021 09:20:16  |  Page Layout Manager  |  Page uses ContentWwW as page layout, mapping that will be used is ContentWwW
26/04/2021 09:20:16  |  _User Transform_  |  _Principal Input:ranslc@********companyname.co.uk_
26/04/2021 09:20:16  |  User Transform  |  Not remapping user ranslc@********companyname.co.uk
26/04/2021 09:20:16  |  Remove Empty Text Parts  |  Removing empty text web part
26/04/2021 09:20:18  |  Article page handling  |  Saved page in cross-site collection: DRAFT---Issue-TQ-Response.aspx
26/04/2021 09:20:19  |  Copying page metadata  |  Copying field:  wwwProcesses
26/04/2021 09:20:19  |  Copying page metadata  |  Copying field:  wwwDirectorates

**Comment by jansenbe** [comment]
@PrasadMadhavan : It seems to go wrong when copying metadata from the source page to the target page. You've mentioned that some pages in the pages library work, others in that same library fail. This makes me assume that you've correctly setup the fields on the target pages library to receive the metadata. Would recommend checking the metadata in the source page and compare the metadata of a failing page with a working page. Alternatively you could also consider commenting out fields from the MetaData section in your page layout mapping as a way to identify the failing field. Note that you'd need to restart your PS session after updating the page layout mapping as stuff is cached.

**Comment by PrasadMadhavan** [comment]
Amazing, Thanks a lot. Issue was with a specific function that I used for field mappings. I updated the mappings and used -ClearCache. Now most of the pages are getting migrated. 

A few pages still fail with an a exception of a few where I see a lot of HTML content.  I don't see any special character in the page html as I see in the error message below.  Any suggestions?  I can close this and open another with details if you wish. Please let me know. 

# Modernization Summary Report

Date  |  Duration  |  Source Page  |  Target Page Url  |  Status
-------------  |  -------------  |  -------------  |  -------------  |  -------------
05/05/2021 14:58:21  |  00:00:24  |  [/*****/Pages/p2p1.aspx](https://*****.sharepoint.com/*****/Pages/p2p1.aspx)  |  []()  |  A issue prevented successful transformation
## Critical Errors during transformation

### 05/05/2021 14:58:46 - [/***/Pages/p2p1.aspx](https://*****.sharepoint.com/****/Pages/p2p1.aspx)

_'0x0A' is invalid within a JSON string. The string should be correctly escaped. LineNumber: 0 | BytePositionInLine: 83.   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(ReadOnlySpan`1 data, Int32 idx)
   at System.Text.Json.Utf8JsonReader.ConsumeString()
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()

**Comment by jansenbe** [comment]
@PrasadMadhavan : please create a new issue with needed data for the remaining problem

**Comment by jansenbe** [comment]
I'll close this one

**Comment by PrasadMadhavan** [comment]
Sure, Thank you for your help.
