### ISSUE TITLE
GetAppOnlyAuthenticatedContext in Azurre WebJob gives 401 Unauthorised

### ISSUE THREAD

**Issue by lvasiliou** [pnp/pnpframework#284]
Hi we are authenticating a webjob for a few years now using App Only authentication but all of the sudden it gives the error server returned 401 unauthorised when attempting to get an app only context. The client id/secret works just fine on a desktop PC. Tried spinning up a new web server to host the webjobs but no change.

**Comment by jansenbe** [comment]
@lvasiliou : SharePoint app-only works via certificates, might it be that there's an issue with the cert e.g. expired? Does the problem still repro?

**Comment by lvasiliou** [comment]
Hi I am sure our app only worked with client id and secret so far, is it something that was changed recently?

**Comment by jansenbe** [comment]
ah..guess you're still using Azure ACS for app-only purposes then. When using an app registered in Azure AD you need a certificate.
