### ISSUE TITLE
[BUG] "Hanging" request in CreateDocumentSetImplementation

### ISSUE THREAD

**Issue by YannickRe** [pnp/pnpframework#287]
Looking at the following code:
https://github.com/pnp/pnpframework/blob/ac4dc39f564fcaa55e140bd7d778149360a265f7/src/lib/PnP.Framework/Extensions/FileFolderExtensions.cs#L239-L242

The last call `GetByUrl` doesn't get executed, so it bleeds through to the client. The returning folder isn't fetched, and that seems to be inconsistent with how all other methods are implemented.

It's easily fixed by running an `ExecuteQueryAsync` on it BUT that has an issue in "BIG LISTS" (> 5000 items). Preferably, we run the fetch on Web as that doesn't trigger the list view threshold: `web..GetFolderByServerRelativeUrl(`
I'd create the PR but I cannot find a good way to get the parentWeb of the folder. Can't do `folder.ListItemAllFields.ParentList.ParentWeb` since that does not work for a root folder.

Any ideas?

**Comment by patrikhellgren** [comment]
@YannickRe How about the following, would that work? Did a quick test in LinqPad and it seems to do the job. Also better to use ResourcePath to support % and # in the url and ExecuteQueryRetryAsync() to take advantage of the retry logic.

``` CSHARP
var documentSetFolder = ((ClientContext) folder.Context).Web.GetFolderByServerRelativePath(ResourcePath.FromDecodedUrl(serverRelativeUrl));
await folder.Context.ExecuteQueryRetryAsync();
```

**Comment by YannickRe** [comment]
@patrikhellgren Maybe. The code itself will for sure work, we're using the same approach outside of PnP. I was trying to submit a PR in that direction, I'm just not sure if you can safely cast every `ClientRuntimeContext` to `ClientContext`.
Hierarchically, every `ClientContext` is a `ClientRuntimeContext` but not the other way around... Only I'm not sure if we'd ever run into that situation...
