### ISSUE TITLE
GetAppOnlyAuthenticatedContext Missing

### ISSUE THREAD

**Issue by christophwille** [pnp/pnpframework#3]
See also https://github.com/pnp/PnP-Sites-Core/issues/2040

The method GetAppOnlyAuthenticatedContext is MIA in the new library. What is the supposed correct replacement in our codebase? (is it GetACSAppOnlyContext?)

**Comment by jansenbe** [comment]
Yes, GetACSAppOnlyContext is the one you need

**Comment by christophwille** [comment]
Thanks for confirming. Our existing app authenticates like it did before, so works as advertised.
