### ISSUE TITLE
More examples about provisioning..

### ISSUE THREAD

**Issue by brittanyru** [pnp/pnpframework#30]
I spent few hours trying to make the provisioning template works, most of the examples aren't for the "sequence" part where you can provision sites, and the ones provided focus on Teams. 

I would like to create new communication sites using the templates, however whenever I do:

connect-pnponline "mysite"

and then apply-provisioningtemplate .. it is applied to the site I connected to in the first step, it's not applied to the site I am having in my provisioning template. Are there any examples and tutorials on how to create new sites? I saw the samples in the provisioning engine, but they all show the .xml nothing shows what I need to do from the Powershell side of things. Is it correct to use connect-pnponline [anysite] ?

thanks.

**Comment by jansenbe** [comment]
The templates used by the [provisioning service](https://lookbook.microsoft.com/) are publicly available: for example the NEO template is a template that creates 4 individual site collections: https://github.com/SharePoint/sp-dev-provisioning-templates/tree/master/tenant/NEO/source. This, and others in that repo, are good samples to build on.

**Comment by brittanyru** [comment]
hi @jansenbe but they don't show how to call them from PowerShell. For example, I am using this: 
`connect-pnponline -Url [siteurl]`

then I am doing this: 

`apply-provisioningtemplate ... `

When I do this, the template is applied to the site I used in `connect-pnponline` I don't want that. I want the template to create a new site that I have defined in the Sequence, and then apply the template to it. The samples are great and everything, but they're not showing me how to actually call them from PowerShell since they are getting applied to the same site I connect to with `connect-pnponline`.

**Comment by jansenbe** [comment]
Here's an example on how to install the NEO template via PnP PowerShell. In this case the url's are parameterized in the template and as such you need to specify them at apply time. Also important is to use `Apply-PnPTenantTemplate` if you want the template to trigger the creation of the site collection. 

```PowerShell
Apply-PnPTenantTemplate -Path .\NEO.pnp -Parameters @{"Company"="Contoso";"NewEmployeeOnboardingUrl"="/sites/NewEmployeeOnboarding";"NewEmployeePreOnboardingUrl"="/sites/NewEmployeePreOnboarding";"NewEmployeeSalesOnboardingUrl"="/sites/NewEmployeeSalesOnboarding";"NewEmployeeEngineeringOnboardingUrl"="/sites/NewEmployeeEngineeringOnboarding"}
```

**Comment by brittanyru** [comment]
Thanks. @jansenbe does it matter which site am connected to with connect-pnponline?

**Comment by brittanyru** [comment]
I just tried it on any site and it worked. Thanks @jansenbe

**Comment by brittanyru** [comment]
@jansenbe another question. I am trying to follow the schema available here to know what I can use: 
https://github.com/pnp/PnP-Provisioning-Schema/blob/master/OfficeDevPnP.ProvisioningSchema/ProvisioningSchema-2020-02.xsd

I have this in my file: 
```
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schema.dev.office.com/PnP/2020/02/ProvisioningSchema">

```
I am using vscode however I don't see the intellisense when I hit control + space. Shouldn't I be able to see all suggestions for a specific node?
