### ISSUE TITLE
How to add SPFx webpart to modern sharepoint page using C#?

### ISSUE THREAD

**Issue by DesireTusharG** [pnp/pnpframework#305]
- We are using both old and new library so there is error occurred. We are using both version of Pnp old and new at the same time

because we learn from other sources that client side page library is not compatible in new pnp version. 
At the same time we are using AngleSharp package which support new version >=0.14.0. 
In new version of Pnp, AngleSharp version supported is >=0.14.0 and in old version of Pnp, AngleSharp version supported is <0.14.0.

- We have installed SharePointPnpCoreOnline package and used following code to add SPFx webpart to modern page but error occured.

> OfficeDevPnP.Core.Pages.ClientSidePage page = OfficeDevPnP.Core.Pages.ClientSidePage.Load(clientContext, "4Mata.aspx");
> var components = page.AvailableClientSideComponents();
> string wpName = "4Mata";
> List<string> componentsnames = components.Select(k => k.Name).ToList();
> var webPartToAdd = components.Where(wp => wp.ComponentType == 1 && wp.Name == wpName).FirstOrDefault();
> if (webPartToAdd != null)
> {
> 	OfficeDevPnP.Core.Pages.ClientSideWebPart clientWp = new OfficeDevPnP.Core.Pages.ClientSideWebPart(webPartToAdd) { Order = -1 };
> 	page.AddControl(clientWp);
> }
> page.Save(pageName+".aspx");
> clientContext.ExecuteQuery();
> page.Publish(); 

> Error occurred in line of code: page.Save(pageName+".aspx");
> Error: 'Could not load type 'System.Web.UI.HtmlTextWriter' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.'

If we use older version of SharePointPnpCoreOnline package then following error occurred:

> Error occured in line of code: OfficeDevPnP.Core.Pages.ClientSidePage page = OfficeDevPnP.Core.Pages.ClientSidePage.Load(clientContext, "4Mata.aspx");
> Error: 'Could not load type 'AngleSharp.Parser.Html.HtmlParserOptions' from assembly 'AngleSharp, Version=0.15.0.0, Culture=neutral, 

 
Question
-> How we can create modern page because both pnp library not working correctly?
-> How we can add spfx webpart in modern page? 
 
Please let us know the solution for this if possible.

Thanks in advance

**Comment by jansenbe** [comment]
See https://pnp.github.io/pnpcore/using-the-sdk/pages-webparts.html to learn more about how to using the modern page API, see https://pnp.github.io/pnpcore/using-the-sdk/basics-pnpframework.html#using-pnp-core-sdk-when-pnp-framework-was-already-configured to get the needed PnP Core SDK context from a SharePoint ClientContext (as you need that one to work with the pages API).

**Comment by jansenbe** [comment]
@DesireTusharG : did above unblock you? If so, please close the issue

**Comment by DesireTusharG** [comment]
@jansenbe I just implemented successfully using PNP Core SDK .

Thanks a lot for your help
