### ISSUE TITLE
Object reference not set to an instance of the object on Invoke-PnPSiteTemplate

### ISSUE THREAD

**Issue by Martin-125** [pnp/pnpframework#307]
What im trying to do is copying one Site from one tenant to another. 
Im first running 

`Get-PnPSiteTemplate -Out "C:\temp\homepage.xml" -IncludeAllPages -IncludeNativePublishingFiles -PersistPublishingFiles -PersistBrandingFiles
`on the source tenant.

Then im connecting to the destination tenant with 
`Connect-PnPOnline -Url https://... -Interactive
`
and try to insert the Template with `Invoke-PnPSiteTemplate -Path "C:\temp\melos\ver5\homepage.xml" -ExcludeHandlers SiteSecurity -ClearNavigation`

The error i get is: 
![pnp](https://user-images.githubusercontent.com/83715083/117162759-5ae33600-adc3-11eb-879d-ae730e983451.png)

Also probably worth noting is that i tried to run 
`Set-PnPTraceLog -On -WriteToConsole` and `Set-PnPTraceLog -On -LogFile "C:\temp\log.txt"` but both didnt do anything.
So the error from "Get-PnPException" is all i can work with.

Looking at the site that i was trying to set the template on, i can see that all of the files are added and subsites  too but most of them are completely empty.

I tried to apply the Template on two different tenants and already reinstalled the PnP.Powershell Module, but now im out of things to try.

**Comment by jansenbe** [comment]
What version are you using? Did you try with the latest nightly and see the same issue? If you've a simplified template that reproduces the issue that will help as well.

**Comment by Martin-125** [comment]
Im using v1.5, do you mean a prerelease version with latest nightly?

**Comment by jansenbe** [comment]
yes
