### ISSUE TITLE
Theme not exported when retrieving provisioning template?

### ISSUE THREAD

**Issue by NickSevens** [pnp/pnpframework#312]
Exporting Theme doesn't seem to work with the provisioning engine?

`Get-PnPProvisioningTemplate -Out C:\temp\template.xml -Handlers Theme` results in an empty ProvisioningTemplate.

Is there a specific (technical/functional) reason this is not included?

**Comment by NickSevens** [comment]
<bump />

**Comment by asith-w** [comment]
is there reason for this issue ?. i am also getting same

**Comment by asith-w** [comment]
@NickSevens  is this issue Ok now ?
