### ISSUE TITLE
Where i can find tutorials?

### ISSUE THREAD

**Issue by quantrpeter** [pnp/pnpframework#314]
Hi, Where i can find tutorials?

**Comment by jansenbe** [comment]
@quantrpeter : we don't really have tutorials or extensive docs for PnP Framework but if you search on the web you'll find a lot of information. Alternatively you can ask via our issues/discussions. We're slowly rewriting PnP Framework into [PnP Core SDK](https://github.com/pnp/pnpcore) and for that one we do have [proper docs](https://pnp.github.io/pnpcore/using-the-sdk/readme.html).
