### ISSUE TITLE
When I provision modern team site with O365 Group , it creates site URL with random 3 digit number at the end.

### ISSUE THREAD

**Issue by Dipali-arup** [pnp/pnpframework#327]
I'm using PnP.Framework  to provision modern Team site. Code snippet is as below:
TeamSiteCollectionCreationInformation modernteamSiteInfo = new TeamSiteCollectionCreationInformation
  {
      Alias = aliasName,
      DisplayName = msg.Title,
      Description = msg.Title,
      IsPublic = true                        
  };
var createModernSite = await ctx.CreateSiteAsync(modernteamSiteInfo);

When I give Alias value as "bid-80425" then group primary address gets created as "bid-80425@tenant.onmicrosoft.com" but Site gets created with URL "https://tenant.sharepoint.com/sites/bid-p80425761".

This behaviour is very random and not happening all the time.

any pointers please will be appreciated.

Thank you.

**Comment by jackpoz** [comment]
do you have already a SPO site collection with the same url ? please check also the SPO deleted site collections at _layouts/15/online/AdminHome.aspx#/recycleBin of your SPO Admin Center.

The 3 digits are usually added by SPO itself when a site already exists and the recycle bin counts too.

**Comment by jansenbe** [comment]
Closing per no feedback anymore from the person asking the question
