### ISSUE TITLE
Navigation is duplicated using "Navigation" Handler

### ISSUE THREAD

**Issue by polar** [pnp/pnpframework#332]
When I create a `TeamSite` and use a `Get-PnPSiteTemplate` from an existing site using `-IncludeAllClientSidePages` and the `Navigation` handler I get duplicates in the Navigation Side bar for Home, Conversations, Notebook, Documents, and Site Contents. 

If I leave off the `Navigation` header in the `Get-PnPSiteTemplate`, I do NOT get duplicates, but I do not get any navigation item for Pages, and do not get any other nav items that was in the original site. It is basically just a basic, Home, Conversations, Notebook, Documents, Site Contents, Recycle bin, and that is it.

I'm using PnP.Powershell 1.5.44-Nightly, maybe a bit newer.

**Comment by polar** [comment]
bump?

**Comment by pkbullock** [comment]
Sorry we haven't got back to the query, please reopen if this is an issue.
