### ISSUE TITLE
Apply spfx field customizer to existing column with pnp provisioning

### ISSUE THREAD

**Issue by David74000** [pnp/pnpframework#333]
Hi all,
I am using the pnp core provisioning engine to apply custom templates when new sites are created. It works fine to deploy spfx webpart or command set to newly created site. Is it possible to deploy a field customizer (spfx extension) to a site using pnp provisioning engine ?
I have tried to include the attribute **ClientSideComponentId**="ID of my field customizer" in the <Field> tag but I get the error saying my XML template is not valid.
Thank you for your help !
David

**Comment by anthonywhite** [comment]
Hi @David74000, we are doing that on a site field and works ok.
