### ISSUE TITLE
PnP Template WebSettings HubSiteUrl should be tokenized

### ISSUE THREAD

**Issue by anthonywhite** [pnp/pnpframework#338]
### Reporting an Issue or Missing Feature
PnP Template WebSettings HubSiteUrl should be tokenized

### Expected behavior 
When generating a template using `Get-PnPSiteTemplate` for a site joined to a Hub, would expect the `<WebSettings HubSiteUrl>` attribute to be tokenized e.g.

`<WebSettings HubSiteUrl="{hosturl}/sites/hubsite">`

### Actual behavior 
Instead the `HubSiteUrl` is a fixed string like so:
`<WebSettings HubSiteUrl="https://<tenant>.sharepoint.com/sites/hubsite">`

### Steps to reproduce behavior
Generate a template for a hub-joined site

### What is the version of the Cmdlet module you are running?
1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows 10
- [x] PowerShell Core 7.1.3

### Other Info
The `SiteLogo` attribute processes as expected. I have a logo in the Portal site that is shared across hub sites and appears in the template like so:
`<WebSettings SiteLogo="{hosturl}/sites/hubsite/SiteAssets/logo.png">`

**Comment by jansenbe** [comment]
@anthonywhite : next nightly allows you to tokenize HubSiteUrl in the web settings, thanks @gautamdsheth  for creating the fix. As such I'm closing this issue

**Comment by anthonywhite** [comment]
Thanks @jansenbe @gautamdsheth 👍
