### ISSUE TITLE
Using <pnp:Folders> Enabling List Folder Creation in UI

### ISSUE THREAD

**Issue by anthonywhite** [pnp/pnpframework#339]
Related to [issue 238](https://github.com/pnp/pnpframework/issues/239), I am seeing the same behaviour.

It appears that if you use `<pnp:Folders>` to create folders for a list instance, it will enable folder creation for the list in the UI even if the `ListInstance` element in the template has attribute `EnableFolderCreation="false"`

**Comment by jackpoz** [comment]
Creating folders requires the setting EnableFolderCreation to be set to true, but the current code never restores it to the previous value.

I created a pull request at https://github.com/pnp/pnpframework/pull/358 that restores it.
