### ISSUE TITLE
Cannot generate a site template with cmdlet "get-pnpsitetemplate" when using pnp.powershell module

### ISSUE THREAD

**Issue by get-mrsmit** [pnp/pnpframework#36]
software + versions
VSCode version 1.51.1
Powershell Version 7.1
PnP.powershell module version 0.2.21

I try to generate a site template with the new cmdlet:
`$Global:TenantID = $appPrincipals.TenantID
$Global:ClientID = $appPrincipals.clientid
$Global:ClientSecret = $appPrincipals.clientSecret

# built up the connection
$adminURl = "https://my365devops-admin.sharepoint.com"
$connection = Connect-PnPOnline -Url $adminURl -ReturnConnection -ClientId $Global:ClientID -ClientSecret $Global:ClientSecret
$web = Get-PnPWeb -Connection $connection
$web

#generate a site template
$Siteurl = "https://my365devops.sharepoint.com/sites/MSTeamsTemplatesiteforSPOSite"
Connect-PnPOnline -Url $Siteurl -ReturnConnection -ClientId $Global:ClientID -ClientSecret $Global:ClientSecret
Get-PnPSiteTemplate -Out ".\Template.xml"
`
I get the error:
`PS C:\GITREPO\DEV_PnP.Powershell> Get-PnPSiteTemplate -Out ".\Template.xml" Get-PnPSiteTemplate: {"error_description":"Invalid issuer or signature."} PS C:\GITREPO\DEV_PnP.Powershell>`

Can some one tell me what is wrong?????

**Comment by gautamdsheth** [comment]
Looks like you are on one of the newer tenants, so you need to execute below command first:

`Set-PnPTenant -DisableCustomAppAuthentication $false`

After 5-10 mins, your code to connect using clientid/clientsecret should start executing.

Reference - https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs

https://www.koskila.net/literally-breaking-changes-to-app-authentication-on-sharepoint-%F0%9F%98%B5/

**Comment by jansenbe** [comment]
@get-mrsmit : did @gautamdsheth 's answer help you? If so please close this issue.

**Comment by jansenbe** [comment]
Closing per no feedback for more than 14 days, please create a new issue if the problem still exists
