### ISSUE TITLE
Set-PnPPropertyBagValue -Indexed does not get crawled

### ISSUE THREAD

**Issue by iloving** [pnp/pnpframework#365]
I am trying to set a property on a site (As per https://www.sharepointdiary.com/2018/03/sharepoint-online-get-set-property-bag-values-using-powershell.html and various other sources), but the value is never crawled.  I have tried both waiting and triggering a re-crawl using both the GUI and Request-PnPReIndexWeb.

I have tried on both Modern and classic sites.  The command nor the crawl log indicates any error occurred.  I have confirmed that I am the site owner.  I have confirmed that DenyAddAndCustomizePages is disabled.

If I use Get-PnPPropertyBag I can see the value exists.  I am at a loss as to what could be wrong.

**Comment by jackpoz** [comment]
is this issue about SPO not crawling Web properties ? or is it about a PnP cmdlet not working ?

**Comment by iloving** [comment]
I have no idea.  At first I thought it was the cmdlet not working, but now I'm wondering if it's SPO not working.  I've since opened a support call /w microsoft to troubleshoot.

**Comment by iloving** [comment]
Ok, I just got off a call /w Microsoft and they have confirm the indexing for our entire Tenant is somehow broken, so I will assume this has nothing to do with PnP.  I'll go ahead and close this for now.
