### ISSUE TITLE
NewDocumentTemplates no properly applied?

### ISSUE THREAD

**Issue by Luis-Art-Guerra** [pnp/pnpframework#366]
I have a Document Library that contains some modifications in the New Button in my source site for the template. When I obtain the template with GetProvisioningTemplate, these New menu is represented by the Tag "NewDocumentTemplates". From What I have seen, the properties are extracted as expected and as they were originally applied. However, when using "ApplyProvisioningTemplate", the items are not shown as the original:

- Menu items which are "visible": false, are visible anyway in the new site
- URL links not working. The source menu items work as expected. Template URL looks correct.

This is an example of two of the items

``` json
{
    "title": "Word document",
    "visible": true,
    "templateId": "Word document",
    "contentTypeId": "{listcontenttypeid:05\\. Other Related Documents,0x010100ACF722E9F6B0B149B0CD8BE2560A6672}",
    "isContentType": true,
    "url": "{site}/05 Basic Data/Forms/Word document.docx",
    "isUpload": true
},
{
    "title": "Link to a Document",
    "visible": false,
    "templateId": "{listcontenttypeid:05\\. Other Related Documents,0x01010A}",
    "contentTypeId": "{listcontenttypeid:05\\. Other Related Documents,0x01010A}",
    "isContentType": true,
    "url": null,
    "isUpload": null
}
```

For example, "Link to a Document" is not visible in the source site, however, is visible in the new site. The property visible is set as false.
As for "Word Document", the item should be able to create a new word document based on the contentType, but instead opens an empty tab, as if the URL was empty. 

I have checked the code and i only was able to identify that the information for NewDocumentTemplates is asigned directly as XML.
``` csharp
// PnP.Framework.Provisioning.ObjectHandlers, line 736 
var viewInnerXml = reader.ReadInnerXml(); // viewInnerXML contains the info for NewDocumentTemplates 
var createdView = createdList.Views.Add(viewCI);
createdView.ListViewXml = viewInnerXml;
if (hidden) createdView.Hidden = hidden;
createdView.Update();
createdView.EnsureProperties(v => v.Scope, v => v.JSLink, v => v.Title, v => v.Aggregations, v => v.MobileView, v => v.MobileDefaultView, v => v.ViewData, v => v.CustomFormatter);
web.Context.ExecuteQueryRetry();
```

**Comment by pkbullock** [comment]
Sorry we haven't got back to the query, we are closing due to its age, please reopen if this is an issue. The associated issue got transferred to PnP PoweShell repo.
