### ISSUE TITLE
IsAppOnly fails with FileNotFoundException

### ISSUE THREAD

**Issue by czullu** [pnp/pnpframework#37]
In a Azure Function based on dotNet 3.1 calling IsAppOnly gives me the Error
System.IO.FileNotFoundException for "System.IdentityModel.Tokens.Jwt, Version=6.7.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35". Strange thing is, that i see this Library with that Version in the dependencies of the azure Function but dll is not in /debug/bin folder while local debugging azure function.

I will try to further investigate in next days with separt AZFunc based on dotNet 2.1 - currently can reproduce this with 2 different projects with dotNet 3.1.

**Comment by jansenbe** [comment]
Does it also repro with our .NET 5 version?

**Comment by czullu** [comment]
finally found time to dig deeper - it works in Console Application for both dotNet Core 3.1 and dotNet 5.0.
It still fails for me in Azure Function Version 3 based on Microsoft.NET.Sdk.Functions Version 3.0.11 in ElasticPlan. Could still not figure out why but at least it narrows things down.

**Comment by jansenbe** [comment]
Could it be that the function host itself already loaded up another version of System.IdentityModel.Tokens.Jwt?

**Comment by czullu** [comment]
> Could it be that the function host itself already loaded up another version of System.IdentityModel.Tokens.Jwt?
The Issue is related to Azure Functions - at least - adding this line from here https://github.com/Azure/azure-functions-host/issues/5894
<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput> 
to my csproj file did solve the issue.
