### ISSUE TITLE
Invoke-PnPSiteTemplate -Path $siteTemplate returning Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)) error (see attcahed screenshot)

### ISSUE THREAD

**Issue by astatke** [pnp/pnpframework#375]
This line is giving me the above mentioned error message:
Invoke-PnPSiteTemplate -Path (where -Path refers to an .xml file generated using  the Get-PnPSiteTemplate command).

Attached are a screenshot of the error as well as a TraceLog file.
[error-Invoke-PnPSiteTemplate.txt](https://github.com/pnp/pnpframework/files/6646026/error-Invoke-PnPSiteTemplate.txt)
![error-screenshot png](https://user-images.githubusercontent.com/5934455/121848464-4722cd80-cca7-11eb-9fa3-9115fbda0710.png)

### Steps to reproduce behavior
PowerShell script attached
[complete-script.ps1.txt](https://github.com/pnp/pnpframework/files/6649736/complete-script.ps1.txt)

### What is the version of the Cmdlet module you are running? Version 1.6.1

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   1.6.1      nightly    PnP.PowerShell                      Core,Desk {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart…}

### Which operating system/environment are you running PnP PowerShell on?
Windows 2019

**Comment by M365Bass** [comment]
Hello,

Based on the error message, it seems like the site has NoScript enabled causing the error. You should be able to disbale NoScript via `Set-SPOSite -Identity https://tenant.sharepoint.com/sites/contoso -DenyAddAndCustomizePages 0` (make sure to connect to SPO using `Connect-SPOService` first).

Once you're done, you should re-enable NoScript on the site for good measures by running the same `Set-SPOSite` command with `-DenyAddAndCustomizePages` set to 1

More information can be found [here](https://sharepoint.handsontek.net/2018/10/28/enable-custom-script-on-modern-sharepoint-sites-using-powershell/) and [here](https://techcommunity.microsoft.com/t5/sharepoint-developer/how-do-i-set-denyaddandcustomizepages-for-sharepoint-2019/m-p/303980)

Hope that's helpful,

Bass

**Comment by astatke** [comment]
Thank you for your feedback @M365Bass. It turns out there were issues in my sample site (which has some lists with site columns). Unfortunately those site columns were never pushed from the Content Type gallery (a.k.a. CTH) into the new site.
