### ISSUE TITLE
web.ApplyProvisioningTemplate + Could not load file or assembly 'System.Buffers, Version=4.0.2.0,

### ISSUE THREAD

**Issue by Dipali-arup** [pnp/pnpframework#378]
I'm using PnPFramwork  in my project to provision a O365 group enabled team site and then I want to apply a PnP template on top of the site. 
when I call ApplyProvisioningTemplate on web and pass PnP Template, I get below exception:

{"Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.":"System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"}

I havent seen any issue coming in when using SharePointPnPCoreOnline and only occurs with PnPFramework.
Am I missing anything?
please help me fix the issue.
many thanks,

regards,

**Comment by jackpoz** [comment]
Hi, is this locally or in an Azure Function ? As Azure Functions have an issue described at https://github.com/pnp/pnpframework/issues/352 (and a workaround too)

**Comment by Dipali-arup** [comment]
hi there,

The issue has occured both locally and running in the Azure function. 
at present I have used biding redirects approach to resolve the assembley reference and it has worked.

would that be right approach do you think long term?

thank you

**Comment by jackpoz** [comment]
I would suggest to try applying the workaround explained at https://github.com/pnp/pnpframework/issues/352#issuecomment-850899908 to see if it fixes your issue. I'm using it already in production for every new Azure Function solution.

When you say "locally", do you mean a console application or the Azire Function local emulator ?

**Comment by Dipali-arup** [comment]
Hello, locally means debugging azure function locally via Visual Studio.

#352 says to use <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>.
let me try adding abouve in .csproj file and Ill get back on it.
thanks,

**Comment by Dipali-arup** [comment]
Hello , I tried adding <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput> in .csproj file and issue still remains the same.

**Comment by pkbullock** [comment]
Closing as old issue, if this is still a problem, please re-open.
