### ISSUE TITLE
Connect trough proxy with User / Password ? 

### ISSUE THREAD

**Issue by moelski** [pnp/pnpframework#383]
Hi @all, 
I´m searching now for several hours to get an idea how to connect to an SP Online behind a proxy. 
My appliaction uses `AuthenticationManager().GetAppOnlyAuthenticatedContext` from the OfficeDevPnP.Core project but I think it´s the same problem here. 

My console application uses the App.config with these entries: 
```
  <system.net>
    <defaultProxy
      enabled="True"
      useDefaultCredentials="True">
    </defaultProxy>
  </system.net>
```
But that didn´t help. As soon as GetAppOnlyAuthenticatedContext is called I got an "(407) Proxy Authentication Required". 

I tried to add the credentials for the proxy in the Windows Credential Manager / Windows Credentials. But that didn´t help either. Still getting error 407. 

Trying to add an ExecutingWebRequest Handler won´t work for me , too. 

So could anyone please give me some advice how to handle a connection to a SP Online system with a given Proxy which uses username + password as proxy authentication? 

Thx alot

Dominik

**Comment by jansenbe** [comment]
Hi @moelski , we don't have specific proxy support in PnP open-source components (applies to PnP Framework, PnP Core SDK and PnP PowerShell), nor do we test our components using a proxy. If the default proxy options (like you've tried) don't work, then there's no short-term solution for you. Adding proxy support would be nice but given the current bandwidth and the involved complexity that will not be soon. Sorry to disappoint you, but this project is running based upon free contributions from folks in the community and driven by the needs of the community. If you feel this is a showstopper for you can always implement proxy support in a forked version and share your implementation back for inclusion.
