### ISSUE TITLE
Expose ASPXPageIndexMode in Set-PnPWeb

### ISSUE THREAD

**Issue by iloving** [pnp/pnpframework#389]
Hi,  I recently asked the core team to expose the ASPXPageIndexMode property in SP.Web (https://github.com/pnp/pnpcore/issues/494#issuecomment-867823075), but apparently that still needs to be exposed in  pnpframework, hence this ticket.

**Comment by jansenbe** [comment]
As discussed in the mentioned issue ASPXPageIndexMode  is not exposed via client side APIs, hence there's no way to integrate it. Sorry, but from the PnP side we can't fix this, hence I'm closing this issue @iloving .
