### ISSUE TITLE
Invoke-PnPSiteTemplate is applying the site footer in reverse order

### ISSUE THREAD

**Issue by diver7** [pnp/pnpframework#40]
### Reporting an Issue or Missing Feature
If I export a site template using Get-PnPSiteTemplate the xml generated for the extended site footer is written left to right and top to bottom. If I then apply that xml template using Invoke-PnPSiteTemplate to another site, the footer is created in reverse order.

Example source footer:
Header 1     Header 2   Header 3
Link 1-1      Link 2-1     Link 3-1
Link 1-2      Link 2-2     Link 3-2

Get created on new site as:
Header 3   Header 2   Header 1
Link 3-2    Link 2-2     Link 1-2
Link 3-1    Link 2-1     Link 1-1

### Expected behavior 
When applying a footer template I am expecting it to be created exactly like the source site it was exported from.

### Actual behavior 
Footer is created in reverse order

### Steps to reproduce behavior
1. Connect-PnPOnline -Url https://[tenant name].sharepoint.com -Credentials(Get-Credential)
2. Get-PnPSiteTemplate -Out template.xml
3. Edit template.xml file and remove everything but the footer xml
4. Connect-PnPOnline -Url https://[tenant name].sharepoint.com/sites/targetsite
5. Invoke-PnPSiteTemplate -Path template.xml
6. View target site and footer will be reversed.

### What is the version of the Cmdlet module you are running?
PnP.Powershell 0.2.23
PS 7.0.3

**Comment by erwinvanhunen** [comment]
We can confirm this bug. We are currently investigating what causes it.

**Comment by erwinvanhunen** [comment]
We have committed a fix to the provisioning engine now, which will be available in the nightly build of tomorrow and the upcoming release of PnP Sites Core. The PnP.PowerShell module will have this change available in tomorrow's nightly build, The SharePointPnPPowerShellOnline module will have it available in the December 2020 release.

**Comment by diver7** [comment]
> 
> 
> We have committed a fix to the provisioning engine now, which will be available in the nightly build of tomorrow and the upcoming release of PnP Sites Core. The PnP.PowerShell module will have this change available in tomorrow's nightly build, The SharePointPnPPowerShellOnline module will have it available in the December 2020 release.

@erwinvanhunen I just installed the latest versions
SharePointPnPPowershellOnline 3.28.2012.0
PnP.Powershell 0.3.4 nightly

Using SharePointPnPPowershellOnline (Apply-PnPProvisioningTemplate) it as working as expected. The footer was created in the correct order.
Using PnP.Powershell (Invoke-PnPSiteTemplate) it is still creating the footer in reverse order. I used the same XML file for both commands.

I updated PnP.Powershell by executing "Install-Module -Name PnP.PowerShell -AllowPrerelease -Force". Is there anything else I need to do?

**Comment by jansenbe** [comment]
Can you cross check you're loading PnP.PowerShell? Add -verbose to the connect-pnponline cmdlet and it will tell you which version it's using

**Comment by diver7** [comment]
> 
> 
> Can you cross check you're loading PnP.PowerShell? Add -verbose to the connect-pnponline cmdlet and it will tell you which version it's using

@jansenbe That was the problem. It's using an old nightly build of PnP.Powershell. I have three versions (0.2.20, 0.2.23, 0.3.4) installed right now and it tries to use 0.2.23. I tried uninstalling one of the older versions but I get an error. I get this error no matter what version I try to uninstall. I am using Powershell v7.0.3. How do I get these older versions removed?

Uninstall-Module -Name "PnP.Powershell" -AllowPrerelease -RequiredVersion 0.2.20
Uninstall-Package: C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:12731
 Line |
12731 |  …        $null = PackageManagement\Uninstall-Package @PSBoundParameters
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | No match was found for the specified search criteria and module names 'PnP.Powershell'.

**Comment by diver7** [comment]
@jansenbe I removed the old versions via the brute force technique. I just went to the install folder and deleted them. :)  Now applying the footer template is working correctly.
