### ISSUE TITLE
Impossible to set ClientSidePages taxonomy fieldvalues with empty if we use parameters

### ISSUE THREAD

**Issue by magarma** [pnp/pnpframework#406]
Hi there,
We are having an issue when we are creating a ClientSidePage with taxonomy field values and those are comming from parameters and are empty... 
for example, 

```
...
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2020/02/ProvisioningSchema">
  <pnp:Preferences>
    <pnp:Parameters>
      <pnp:Parameter Key="parameterTest1"></pnp:Parameter>
    </pnp:Parameters>
  </pnp:Preferences>
...
<pnp:ClientSidePage PromoteAsNewsArticle="false" PromoteAsTemplate="false" Overwrite="true" EnableComments="false" Title="Home" ContentTypeID="0x010100...."  PageName="Home.aspx" Layout="Home">
...          
<pnp:FieldValues>
            <pnp:FieldValue Key="CPLocationGeography" Value="{parameter:parameterTest1}"/>
 <pnp:FieldValues>
 </pnp:ClientSidePage>
 ...
```
In ObjectClientSidePage.cs there is a call...

![image](https://user-images.githubusercontent.com/8925463/124926104-6e965d00-dffd-11eb-9468-2a5785f737ba.png)

This is giving an exception because the code is only checking by null and not by empty and when calling to the methdo GetTaxonomyItemByPath with an empty string is raising the exception.
_`"Activity failed with an error. Reason: System.ArgumentNullException: Value cannot be null. (Parameter 'path')"`_

![image](https://user-images.githubusercontent.com/8925463/124926349-b87f4300-dffd-11eb-9c66-5d9ca6386d0f.png)

I'm plannig to send PR #407  fixing that.

**Comment by jansenbe** [comment]
PR is merged, closing the issue
