### ISSUE TITLE
Files are checkout with Overwrite=false

### ISSUE THREAD

**Issue by roberAlb** [pnp/pnpframework#419]
Hi there,

Basically, we are deploying files with PnP framework and those files that are with Overwrite=false are checkout modifying the history. We were expecting that if overwrite=false those files will not be touched.

Is there a reason for that? Or is it a real bug?

PnP Framwork version used is 1.5.28-nightly

Thanks,

**Comment by pkbullock** [comment]
Sorry we haven't got back to the query, we are closing due to its age, please reopen if this is an issue.
