### ISSUE TITLE
Export-PnPPageMapping : Cannot bind parameter 'Connection'. Cannot convert the "PnP.PowerShell.Commands.Base.PnPConnection" 

### ISSUE THREAD

**Issue by ButtonWire** [pnp/pnpframework#435]
I'm following below link to Modernize classic pages from on-premises sites 
https://pnp.github.io/script-samples/modernize-classic-pages-from-publishing-sites/README.html?tabs=pnpps

Here is my script:

import-module "C:\Program Files\WindowsPowerShell\Modules\SharePointPnPPowerShell2013\3.29.2101.0\sharepointpnppowershell2013.psd1" -DisableNameChecking

$sp13Conn = Connect-PnPOnline -Url "http://onPremURL"  -ReturnConnection  -CurrentCredential

Export-PnPPageMapping  -CustomPageLayoutMapping -PublishingPage "testEntWikiPage.aspx" -Folder "C:\temp\Demo" -Connection $sp13Conn

Export-PnPPageMapping  -CustomPageLayoutMapping -Folder "C:\temp\Demo" -BuiltInWebPartMapping -Connection $sp13Conn

When it is trying to Export-PnPPageMapping, it throws below error, appreciate any inputs on this error 

Export-PnPPageMapping : Cannot bind parameter 'Connection'. Cannot convert the "PnP.PowerShell.Commands.Base.PnPConnection" 
value of type "PnP.PowerShell.Commands.Base.PnPConnection" to type "PnP.PowerShell.Commands.Base.PnPConnection".

**Comment by pkbullock** [comment]
Sorry we haven't got back to the query, we are closing due to its age, please reopen if this is an issue. 😊
