### ISSUE TITLE
Check "Enable pages and news to be translated" with provisioning engine

### ISSUE THREAD

**Issue by brittanyru** [pnp/pnpframework#44]
Is there a way to have the option "enable pages and news to be translated into multiple languages" by default within the provisioning engine? I know about the supported languages element in the xml schema, but this will not enable this option by default.

Is there a PnP Powershell cmdlet to enable it?

**Comment by jansenbe** [comment]
Just trying to understand the question: you want to generate translations for all the existing pages in a site? You can do this via API's in either [PnP Framework](https://github.com/pnp/pnpframework/blob/dev/src/lib/PnP.Framework/Pages/ClientSidePage.cs#L1655) or in the [new PnP Core SDK](https://pnp.github.io/pnpcore/articles/consumer/pages-multilingual.html#create-translations-of-a-given-page). 

Adding @erwinvanhunen for awareness.

**Comment by brittanyru** [comment]
@jansenbe no i don't want to add translation. When I use the SupportedLanguages tag in my provisioning template, it adds that language however the "Enable pages and news" checkbox remains unchecked. is there a way to "check it" by default in the template? When I check it manually, then I can see the languages I added in supportedlanguages tag. but I would like to check it automatically as part of the template. 

![image](https://user-images.githubusercontent.com/74309486/101928228-53688980-3ba3-11eb-89f3-4463172b0aad.png)

**Comment by jansenbe** [comment]
Got it, this can be done by enabling a web scoped feature 24611c05-ee19-45da-955f-6602264abaf8. So in PnP PowerShell this can be done using the [Enable-PnPFeature](https://pnp.github.io/powershell/cmdlets/released/Enable-PnPFeature.html?q=enable-pnpfe) cmdlet.

**Comment by brittanyru** [comment]
Thanks @jansenbe
