### ISSUE TITLE
Access denied to webpartmapping.xml in custom application for page modernization

### ISSUE THREAD

**Issue by bzinchenko** [pnp/pnpframework#456]
I created custom application for modernization of pages. It runs fine in my development environment. However, when deployed on client machine, there appears error like follows "Access to the path 'C:\Program Files (x86)\MyApp\webpartmapping.xml' is denied". How to specify custom location for this file in user folder to avoid such error? 

It is also not clear why extra access is required to this file. If it was opened by the framework for read-only, I do not expect such an error. Please advise. Thank you.

**Comment by jansenbe** [comment]
Hi @bzinchenko : If you're using the default web part mapping file then you do not need to ship webpartmapping.xml file, if you however want a custom one you need to tell your code to use that file. See https://github.com/pnp/powershell/blob/dev/src/Commands/Pages/ConvertToPage.cs#L264 for an example how we do this in PowerShell

**Comment by bzinchenko** [comment]
Hello @jansenbe Thank you for prompt reply. If you do not place 'webpartmapping.xml' next to the program binary, modernization fails with an error indicating that the file is absent. Thank you for the code reference. I will use it to pass location explicitly.

**Comment by bzinchenko** [comment]
Hello @jansenbe Additionally, I still don't understand why you open mapping in read/write mode. You only read the info. If you confine to read-only mode, no issue will ever appear.

**Comment by jansenbe** [comment]
@bzinchenko : Maybe you're using an older version of PnP Framework or the modernization framework, as shown in the code sample there's no need for providing the web part mapping file if you've not customized it. You can however do as shown in the PS example. I'm closing this issue for now, feel free to open a new one if you can't get things to work
