### ISSUE TITLE
Dynamics 365 CE online plugin error 

### ISSUE THREAD

**Issue by TkachouAndrej** [pnp/pnpframework#458]
## Category

- [x] Bug

## Describe the bug

> Trying to use PnP framework (PnP.Core, PnP.Core.Auth) in D365 CE online plugin, faced with issue:
> 1. Sign my custom assembly and rebuild the project.
> 2. See warnings: 
> Referenced assembly 'PnP.Core, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.	
> Referenced assembly 'PnP.Core.Auth, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.	
> 3. Try to run my custom assembly in debug mode via the plugin registration tool and see error:
> Could not load file or assembly 'PnP.Core, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. > A strongly-named assembly is required. (Exception from HRESULT: 0x80131044) 
> 4. Unsign my custom assembly and rebuild the project - no warnings. But we can't use unsigned assemblies as plugins. 

## Steps to reproduce

> Sign PnP assemblies with strong key. 

## Expected behavior

> Custom signed assembly could be used as CRM plugin. 

## Attachments

> Visual studio 2017 warnings :
<img width="731" alt="1" src="https://user-images.githubusercontent.com/46528729/132942541-1fb629da-9d48-400c-bc7a-7c6365d21b7b.png">

> Plugin registration tool error :
<img width="1383" alt="2" src="https://user-images.githubusercontent.com/46528729/132942543-cbe4424d-5f4a-4e8f-a6b0-d4e37076e4e8.png">

## Environment details (*development & target environment*)

- **SDK version**: [1.3.0]
- **OS**: [Windows 10]
- **SDK used in**: [.NET Assembly]
- **Framework**: [.NET Framework 4.6.1]
- **Tooling**: [Visual Studio 2017, Plugin Registration Tool]

**Comment by jansenbe** [comment]
@TkachouAndrej : the next nightly build of PnP Framework will be strong named
