### ISSUE TITLE
Adding managed properties as part of provisioning template

### ISSUE THREAD

**Issue by brittanyru** [pnp/pnpframework#46]
Is there a way to provision a managed property as part of pnp provisioning templates? for example I am provisioning a site where I have a document library with managed metadata column. I want to have a highlighted web part that I added on a page as part of the provisioning template where it pulls all documents of specific term across different sites. I already deploy the term set, sites, with libraries and their fields & content types as part of my template, but am not sure how to solve the managed metadata part. 

I know that the content has to be crawled first so I can create a managed property, but how do we handle this as part of the provisioning process?

**Comment by jansenbe** [comment]
There's no API or cmdlet to create managed properties...closest what you can do is import/export the search configuration via [Get-PnPSearchConfiguration](https://pnp.github.io/powershell/cmdlets/released/Get-PnPSearchConfiguration.html?q=property)

**Comment by brittanyru** [comment]
Thanks for pointing me to the right way @jansenbe

**Comment by brittanyru** [comment]
@jansenbe I tried using the command `Get-PnpSeachConfiguration` by connecting to my tenant admin site, and then running this: 

`Get-PnPSearchConfiguration -Scope Subscription -OutputFormat ManagedPropertyMappings`
It returns nothing.. I try with: 

`Get-PnPSearchConfiguration -Scope Subscription -OutputFormat CompleteXML`
It returns XML where ManagedProperties TotalCount = 0

I try connecting to a specific site with Connect-PnPOnline, then running: 
`Get-PnPSearchConfiguration -Scope Site -OutputFormat CompleteXML`
But I get same result with TotalCount=0

I couldn't find examples or any way to troubleshoot this. Any idea? 

I already have site columns of type taxonomy, and I can see in my tenant search schema that it auto generated a managed property.

**Comment by jansenbe** [comment]
Adding @wobba for his search insights

**Comment by wobba** [comment]
See my post and script referenced at https://www.techmikael.com/2020/11/mapping-or-clearing-crawled-property-to.html

If you use `Get-PnPSearchConfiguration -Scope Subscription` and have tenant admin rights, you should get mapping done at the tenant level. The cmdlet only output manual changes, not OOB mappings. This means you need to either manually do search config changes in the UI or upload a search config xml file for something to be returned.

As the PnP provisioning template already support search config xml files, the original question is already possible with the API's we have.

**Comment by brittanyru** [comment]
thanks @wobba I was not doing the mapping of properties manually. i thought it would pick up the auto created managed properties. i will submit a PR to [this page](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpsearchconfiguration?view=sharepoint-ps) to clear this

for the [script ](https://github.com/wobba/SearchConfiguration/blob/master/MapCrawledPropertyToManagedProperty.ps1) on your blog, where is the part that creates the crawled prop without it having content? i am trying to understand the script and see where that part is done but unable to.

what I did was changing the values in the xml generated by Get-PnPSearchConfig, rename the crawled property that existed there, and then run it with Set-PnPSearchConfig and it auto generated that crawled property for me, is it the right way to do so?

**Comment by wobba** [comment]
@brittanyru once you import the config file, the cp is created if not already present.
