### ISSUE TITLE
x64 target unavailable in nuget - strong name necessary

### ISSUE THREAD

**Issue by simiac** [pnp/pnpframework#468]
Following issue experienced when adding the PnP.Framework to a vs2019 based project:
During runtime a FileLoadException is thrown suggesting the file or some dependency cannot be loaded.
Dependency walker shows inconsistency in machine targets i.e. x86 for PnP.Framework and x64 the rest.
Donwloading the nuget directly and exploring the dll out of the archive using dumpbin shows also x86 in the header for the machine.
The nuget packaging seems to be missing the target machine x64.
This is true for 1.6.0 release as well as the latest nightly build.
Exception suggests issue with strong name is necessary.
Found the discussion on similar issue in previous versions here https://github.com/pnp/pnpframework/issues/201
As my project needs strong names, is there a possibility to add strong name signatures to the release of pnpframework dlls?

**Comment by jansenbe** [comment]
@simiac : this is something in progress, the underlying PnP Core SDK got strong named recently, PnP Framework will follow but is slightly more complicated as one of it's dependencies today is not strong named.

**Comment by jansenbe** [comment]
@simiac : the next nightly build from PnP Framework will be strong named
