### ISSUE TITLE
Throttling/CSOM issues on specific tenants

### ISSUE THREAD

**Issue by advdberg** [pnp/pnpframework#485]
We have 5 M365 tenants for internal dev/test/acceptance purposes. We run nightly regression tests for our provisioning PowerShell scripts, the same scripts on each tenant. Since about 5 weeks we experience lots of throttling/csom errors on 2 out of 5 tenants. 3 weeks ago the issues seemed to be gone but it started again 2 weeks ago on the same tenants. The other 3 keep running smoothly.

Microsoft support isn't very helpful because it are custom PowerShell scripts using PnP cmdlets.

Does anyone have experienced the same? Are there different throttling settings per tenant?

**Comment by pkbullock** [comment]
Sorry we haven't got back to the query, we are closing due to its age, please reopen if this is an issue. This sounds like a service issue if this can be reproduced outside of PnP.
