### ISSUE TITLE
Missing HeaderLayoutType

### ISSUE THREAD

**Issue by Bux42** [pnp/pnpframework#498]
Hello,

There are two out out of four HeaderLayoutTypes being handled in those switch statements:

https://github.com/pnp/pnpframework/blob/ac4dc39f564fcaa55e140bd7d778149360a265f7/src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectSiteHeaderSettings.cs#L27

https://github.com/pnp/pnpframework/blob/ac4dc39f564fcaa55e140bd7d778149360a265f7/src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectSiteHeaderSettings.cs#L60

"Extended" and "Minimal" (already present in HeaderLayoutTypes enum) are missing from those two switches

Could you add those?

Thanks in advance!

**Comment by jansenbe** [comment]
Nice catch @Bux42 . I've just pushed a fix for this, please test with the next nightly and re-open the issue if the problem still persists.
