### ISSUE TITLE
[BUG] Add-PnPApp Fails with access denied when connected using a global tenant administrator account (on Windows)

### ISSUE THREAD

**Issue by reidav** [pnp/pnpframework#52]
### Reporting an Issue 

Add-PnPApp **fails with access denied when connected using a tenant global administrator account**.
* Tested using sharepoint admin and tenant app catalog url (Connect-PnPOnline).
* Tenant global administrator is also a site collection administrator of the app catalog site (built-in principals are also available Company Administrator and SharePoint Service Administrators)
* Also tested using a new app catalog site (deleted the old one and recreated it)
* MFA is not enabled on the admin account
* Get-PnPApp is still working
* **It's also working with the latest version of "SharePointPnPPowerShellOnline" cmdlets**

### Expected behavior 
App should be uploaded into the tenant site app catalog

### Actual behavior 
<img width="670" alt="pnpissue" src="https://user-images.githubusercontent.com/29715747/102012470-ed1e6b00-3d4a-11eb-99d4-c51920c600d9.png">

<img width="670" alt="pnpissue1" src="https://user-images.githubusercontent.com/29715747/102012291-d4fa1c00-3d49-11eb-8df2-ddb57519e508.png">

### Steps to reproduce behavior
Connect-PnPOnline -Url 'siteUrl' -Credentials 'credentials'
Add-PnPApp -Path 'appPath'

### What is the version of the Cmdlet module you are running?
0.3.7 (Nightly) + Pswh 7.1.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by reidav** [comment]
> @reidav regarding monitoring on Windows: I use Fiddler. I found out that the order of Launching is important. Launch Fiddler first, then launch PowerShell core. It's important to do it in that order.

You made my day ! I've been through lots of details to get a trace ($env:http_proxy, wireshark sslkeylog and many more ..) Respecting the start order is really a key for success :) Thanks !

**Comment by erwinvanhunen** [comment]
We just merged a fix for this issue which will be available in the nightly release of tomorrow in both the PnP Framework and PnP PowerShell.
