### ISSUE TITLE
sharepoint 2019 - on premises feature bug

### ISSUE THREAD

**Issue by Odyss-eus** [pnp/pnpframework#524]
"
**When you run a search crawl for a Line of Business Data (BDC) type of content source that contains blob files, you receive an error message in the crawl and ULS-logs that contains:

CRobotThread::Thread failed to move BDC blob file.

The blob files don’t get indexed, and you cannot search for them.**"
This bug has been fixed in sharepoint 2013, 2016(https://support.microsoft.com/en-us/topic/description-of-the-security-update-for-sharepoint-enterprise-server-2016-january-9-2018-562f7215-a887-f152-f38c-0b329691fd40), could it be fixed in sharepoint 2019 also?

**Comment by jansenbe** [comment]
You'll have to open an official support ticket with Microsoft for that. In this repo we do support PnP Framework which only works for SharePoint Online.
