### ISSUE TITLE
[BUG] Invoke-PnPSiteTemplate: Could not load file or assembly 'OfficeDevPnP.Core, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by jimmywim** [pnp/pnpframework#54]
Trying to run `Invoke-PnPSiteTemplate`, am getting the above error.

### Expected behavior 
Template to be applied to the connected site

### Actual behavior 
Returns the error:

`Could not load file or assembly 'OfficeDevPnP.Core, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`

### Steps to reproduce behavior
Running `Invoke-PnPSiteTemplate` with a valid XML template

### What is the version of the Cmdlet module you are running?
0.3.8

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Thank for you reporting this one! It was an issue with the OpenXML file handling. It tried to instantiate an instance of the assembly mentioned in namespace of the manifest.xml file which is in the .pnp file root folder. We are rewriting that one now before the openxml code can handle the package filename. The fix will be available tomorrow in the PnP.Framework preview release and the 0.3.9-nightly release of PnP PowerShell.
