### ISSUE TITLE
Trace log are disabled since nightly build use Release configuration

### ISSUE THREAD

**Issue by ygrenier** [pnp/pnpframework#547]
Hi,

With the PnP.PowerShell project, I meet the issue [[BUG] Set-PnPTraceLog: log file is empty #1061](https://github.com/pnp/powershell/issues/1061).

After research, I found the problem: PnP.PowerShell use the PnP.Framework.Diagnostics.TraceLogger (from the PnP.Framework.dll) wich using the System.Diagnostic.Trace class. In the PnP.Framework project I see in the Release configuration the TRACE variable is not defined, so because the ConditionalAttribute on the Trace class, the code calling Trace methods is not generated.

When I look the Git history, I found this commit : [Updated nightly build to use release builds instead of debug builds](https://github.com/pnp/pnpframework/commit/9bd136b0ec1b24477fb335fd19c33b22ac0c1e49)

So since the build use the Release configuration (without TRACE variable defined) the PnP log file are empty.

Regards,

**Comment by gautamdsheth** [comment]
Thank you so much for this amazing investigation.
Will add this constant to the release as well.
Have sent a PR for this to fix it, when it is merged, PnP PowerShell will automatically be fixed as we always get the latest releases from PnP framework.

Much appreciated 🙏
