### ISSUE TITLE
Exporting ClientSidePage with thumbnail image within Guid in the name fails

### ISSUE THREAD

**Issue by magarma** [pnp/pnpframework#568]
Hi,
We've found a case when we have a client side page with a Guid being part of the thumbnail url and it's failing during the export template.
![image](https://user-images.githubusercontent.com/8925463/148732592-fc33b49f-aa5f-4d75-ba5f-3b7e570d8a17.png)

This would raise an exception in the line 172.

The page has as thumbnail the image URL 
https://xxxxxxxx.sharepoint.com/sites/WhateverTest/Library/761982578-pexels-stanislav-kondratiev-5379088_01D8B295-5963-47F3-B1F8-946AF2A635782021-08-12T10-16-06.jpg

As you can notice when the code is try to find a Guid pattern with Regex, is matching, but of course is not a valid file Id to be got with web.GetFileById

**Comment by magarma** [comment]
This will happen every time there is a thumbnail image added to a page from the O365 stock images.

**Comment by jansenbe** [comment]
Closing as the fix was merged
