### ISSUE TITLE
How can I manage WebParts on modern page with PnP Framework?

### ISSUE THREAD

**Issue by KamilPacanek** [pnp/pnpframework#608]
Hello,
I'm being referenced to this project as [PnP-Sites-Core](https://github.com/pnp/PnP-Sites-Core) is deprecated. However, I can't see the Load method in `ClientSidePage` class and `ClientSidePageContentsHelper` only allows to export the page.

I'd like to remove the web parts from the Home.aspx page, but obviously `LimitedWebPartManager.WebParts` for modern page returns zero elements. How can that be done?

**Comment by jansenbe** [comment]
@KamilPacanek : see the pages API implementation in PnP Core SDK: https://pnp.github.io/pnpcore/using-the-sdk/pages-intro.html. Also note that you cannot update an uncustomized home page, you can however programmatically create a new home page and set that as home page of your site.

**Comment by KamilPacanek** [comment]
Ahh, I think that was the issue because I was trying to modify `Home.aspx` on the new site, which means that was an uncustomized one. Thank you @jansenbe, I will use that knowledge next time (in this scenario I went with copying previously prepared page to new sites)!
