### ISSUE TITLE
Multilingual SharePoint site transformation issue

### ISSUE THREAD

**Issue by baharehesf** [pnp/pnpframework#609]
Hey folks,

I have 2 classic SharePoint sites in EN and FR. I don't know how I can transform these 2 sites into modern that I keep the connection between pages in EN and French. Do you guys have any ideas?

I use PnP PowerShell for transformation.

**Comment by pkbullock** [comment]
Hi @baharehesf, did you resolve this one? or do you need help?

**Comment by baharehesf** [comment]
Hi @pkbullock,

I solved this issue by these following steps:

1. Transforming English version
2. Creating French version from previous step
3. Transforming and overwriting French version on previous step

If you know better way, I'm open to it.

thanks for your time and follow up.

**Comment by jansenbe** [comment]
Thanks for the update @baharehesf , closing this issue now.
