### ISSUE TITLE
Unable to update AssociatedOwnerGroup

### ISSUE THREAD

**Issue by bajce** [pnp/pnpframework#619]
Im trying to update AssociatedOwnerGroup using this code:

```
using (var csomContext = PnPCoreSdk.Instance.GetClientContext(context))
 {
      var csomContextWeb = csomContext.Web;
      csomContext.Load(csomContextWeb,
                   w => w.Id,
                   w => w.Url,
                   w => w.SiteGroups,
                   w => w.AssociatedOwnerGroup,
                   w => w.RoleDefinitions);
                            
      csomContext.ExecuteQuery();
                            
      var ownerGroup = csomContextWeb.SiteGroups.GetById(ownerGroupId);
      
      // csomContextWeb.AssociatedOwnerGroup = new Group(csomContextWeb.Context, ownerGroup.Path); Also tried this
      // csomContextWeb.AssociatedOwnerGroup = null; Also tried this
      csomContextWeb.AssociatedOwnerGroup = ownerGroup;
      
      // ownerGroup.Update(); Also tried this
      
      csomContextWeb.Update();                  
      csomContext.ExecuteQuery();  
 }
```

I get following error:

Microsoft.SharePoint.Client.ServerUnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
 
 I tried to update some other Web properties (to make sure im privileged edit this Web) such as description and that works.
 
 For my approach im using certificate authentication for application.

**Comment by jansenbe** [comment]
@bajce : did you try creating  a group via the UI first and then connect that...trying to rule out something goes wrong in the group creation. Also, did you try with delegated permissions?

**Comment by bajce** [comment]
@jansenbe I was using some existing group, I also tried to set the AssociatedOwerGroup to null and error was same. I only tested certificate authentication for application and Basic (User Password) authentication with user I am able to edit AssociatedOwnerGroup on ...sitename/_layouts/15/permsetup.aspx page and for both a got same error.

**Comment by jansenbe** [comment]
@bajce , as you've tried using CSOM this does not seem to be an issue with PnP Framework or PnP Core SDK. As mentioned before, the reason why that feature was not ported to PnP Core SDK was because we had doubts about it. I'll be closing this issue and the one in PnP Core SDK for this ask. For the non working CSOM I would advise to open a support case using the regular channels.
