### ISSUE TITLE
Difference between PnP Core SDK and PnP Framework

### ISSUE THREAD

**Issue by web265p3** [pnp/pnpframework#620]
Today I [read an article ](https://practical365.com/how-the-new-wave-of-libraries-from-microsoft-365-pnp-will-change-the-way-you-modernize-sharepoint/) about the two PnP libraries "[PnP Core SDK](https://pnp.github.io/pnpcore/using-the-sdk/readme.html)" and "PnP Framework".

PnP Core SDK seems to be a framework that is totally abstracting CSOM, Graph or REST Apis of SharePoint/Teams.
So I can just use the Pnp-Context and dont have to care anymore if Graph or CSOM is actually used in the background.
This makes sense to me.

But PnP Framework is also a new library and it provides still access to the actual CSOM context.
This confuses me, because I dont know how to behave now as a developer.

Should I use only the PnP Core SDK? And the PnP Framework only if I need the site provisioning engine?

Or can I use PnP Framework also for typical operations like "Creating sites", "Updating list items" etc.?

The article states the following differences between both libraries:

> You might be wondering what the difference is between PnP Framework and PnP Core SDK. The PnP Core SDK is used by the PnP Framework and it’s been implemented with a mindset that is independent of CSOM of SharePoint. More and more new functionalities introduced in SPO are not necessarily available through CSOM; this was the impetus for Microsoft 365 PnP introducing a new SDK, which is under the cover of both PnP Framework and PnP PowerShell for some functionalities.

Yeah - but why do I still need Pnp Framework? This only explains what PnP SDK is...

Later he goes on:

> After reading this content, you might ask yourself: “What should I use and when?”
If you are a SharePoint developer, used to working with CSOM, or if you have an already existing project built on top of PnP Sites Core and CSOM, you should rely on PnP Framework and start building modern solutions leveraging the rich set of extensions and utilities provided by the new PnP Framework library.
> If you are a .NET developer, willing to create a new modern solution for SPO, start working with PnP Core SDK and enjoy consuming the Microsoft Graph and the SPO REST APIs with a high-level abstraction layer.

I am a SharePoint developer and also a .NET 5 developer. But this still does not answer my question.

When should I use PnP Framework? When the SDK?

For normal site, team, list, item operations etc. I could use the SDK and for the provisioning engine the Framework?
But is this correct?

**Comment by jansenbe** [comment]
@web265p3 : To fully understand the story you need to know a bit more about our history. 8 years ago we introduced our first .Net library named PnP-Sites-Core. This was mainly a set of CSOM extensions that grew to be a very large set of features to help SharePoint devs. This library was supported for both SPO as various SP on-premises versions. Given there were more and more non CSOM calls needed + the old library was not ready for modern .NET + the fact that on-prem usage was going down we decided on building a new library, which is PnP Core SDK. Given PnP-Sites-Core was so huge we'd never be able to in parallel build a new library will all features and then ship it to replace PnP-Sites-Core, this transformation is multi year journey given this is driven as an open source project. To enable that we did introduce PnP Framework, which started of as cleaned up version of PnP-Sites-Core (all on-prem code specific code was dropped, all 'legacy' stuff was dropped). Folks could migrate to PnP Framework and in parallel we developed PnP Core SDK and moved functionality from PnP Framework to PnP Core SDK. For example the pages API logic lives in PnP Core SDK, but you can still call it via PnP Framework as that acts as a proxy.

When you're starting a new project it's advised to use PnP Core SDK unless you've a dependency on the PnP provisioning engine (for creating and applying site templates). When using PnP Core SDK you can still bump into certain missing features, but we try to respond quicker on those and you can also make custom API calls to REST/Graph to get a quick fix (see https://pnp.github.io/pnpcore/using-the-sdk/basics-customapirequests.html)

**Comment by web265p3** [comment]
Perfect! So I will just use PnP Core SDK except if I need the provisioning engine. Then my guess was correct. Thanks for the explanation.
