### ISSUE TITLE
AddPageAcceptBanner does not have effect

### ISSUE THREAD

**Issue by remcodegroot** [pnp/pnpframework#631]
When running ConvertTo-PnPPage -Identity Home.aspx  -AddPageAcceptBanner -Overwrite -LogType Console -LogVerbose

I do not see any Page Header accept webpart on the resulting page Nor do I see any prove or error message  PNP.Powershell trying to process the banner. I have installed sharepointpnp-pagetransformation-client.sppkg in the environment. I have also tried changing the webpartmapping file. No result. 

Nowhere on the web I can find any example how the output is supposed to look.

<WebPart Type="SharePointPnP.Modernization.PageAcceptanceBanner" CrossSiteTransformationSupported="true">
        <Properties>
          <Property Name="SourcePage" Type="string"/>
          <Property Name="TargetPage" Type="string"/>
        </Properties>
        <Mappings>
          <Mapping Default="true" Name="default">
		  <ClientSideText Text="***A Header should be here ***" Order="10" /
          </Mapping>
        </Mappings>
      </WebPart>

**Comment by jansenbe** [comment]
@remcodegroot , sorry but this functionality has been deprecated. We used to have a banner concept allowing end users to trigger transformation etc...but the needed backend setup was too complex to setup/maintain, hence we've abandoned that idea.
