### ISSUE TITLE
Exception of type 'Microsoft.IdentityModel.Tokens.AudienceUriValidationFailedException' was thrown

### ISSUE THREAD

**Issue by brittanyru** [pnp/pnpframework#64]
i tried my provisioning template in one tenant, it worked perfectly, i tried to use it in another tenant, it gave me the error i mentioned. i turned on logging using `Set-PnPTraceLog -On` to see where it errors and it errors when it tries to check the spfx packages in the app catalog.

I checked that I am a site collection admin in the new tenant's app catalog and i am. I have Global Admin, Power platform admin and SharePoint admin on the new tenant, and site collection admin on the app catalog.

**Comment by jansenbe** [comment]
When you create a new tenant there's not an app catalog by default...did you confirm the app catalog was setup in the new tenant? If app catalog was present then can you share the snippet of the log containing the failure, please include some lines above as well.

**Comment by brittanyru** [comment]
Hi @jansenbe yes I am a site collection admin in the new tenants app catalog site collection. how do I get access to the logs?

**Comment by gautamdsheth** [comment]
@brittanyru - is this a "new" tenant, as in recently created one ? 
If so, then you need to execute this command first and wait for couple of mins before provisioning 

`Set-PnPTenant -DisableCustomAppAuthentication $false`

By logs, we mean the trace log that you see after you turn on the `Tracelog`.

**Comment by brittanyru** [comment]
@gautamdsheth  no it's not a new tenant, it's actually older than the dev tenant I created where it was working. I waited one more day and executed the same exact script and it worked. Not sure why there was a glitch.

**Comment by jansenbe** [comment]
If you've created a new app catalog that's not immediately usable from an API point of view, there are some background processes that need to do their thing. That might explain the delay.

**Comment by brittanyru** [comment]
@jansenbe the app catalog and the tenant were old ones, even older than the dev tenant I recently created. It's working now anyways.
