### ISSUE TITLE
"Versioning must be enabled" error

### ISSUE THREAD

**Issue by elvogel** [pnp/pnpframework#67]
We have a client with a site template that, as of late October, started throwing this error:

```
Versioning must be enabled and the number of major versions must be between 1 and 50000.
```

Any idea what might be causing this? This code had been working for a good 18 months. 

Thanks!

**Comment by jansenbe** [comment]
Which version of PnP Framework are you using or are you still using a older version of PnP Sites Core? I seems as versioning is set wrongly...maybe check in the template how versioning is set and extract for example a single list and try to apply that as a template to get a cleaner repro. Also would advice to move to PnP Framework if possible

**Comment by elvogel** [comment]
The version is 2.11.1701.1 for OfficeDevPnP.Core.  Everything worked fine until the end of October when we started getting this issue.

________________________________________

**Comment by jansenbe** [comment]
That's a very old version (from January 2017)...I would strongly encourage you to upgrade your solution to use a more recent build and verify if the problem still exists. Also please experiment with the settings in your pnp provisioning template: https://support.microsoft.com/en-us/office/how-versioning-works-in-lists-and-libraries-0f6cd105-974f-44a4-aadb-43ac5bdfd247?redirectsourcepath=%252fde-de%252farticle%252fintroduction-to-versioning-49e87cfa-1f18-427b-852b-7ff1612ef672&ui=en-us&rs=en-us&ad=us indicates that for document libraries the minimal version count is 50 for SPO...maybe your template is setting a lower number?

**Comment by jansenbe** [comment]
Closing issue. If you still have issues with the latest version then please open a new issue
