### ISSUE TITLE
The function "await PnPCoreSdk.Instance.GetPnPContextAsync" is returning a wrong pnpcontext instance

### ISSUE THREAD

**Issue by danielpastoor** [pnp/pnpframework#671]
Category
 Bug
Describe the bug
When i use the "await PnPCoreSdk.Instance.GetPnPContextAsync" with a clientcontext with as example the following url: "https://cosmos.sharepoint.com/sites/cosmos". Then the function returns a PnPContext with the sharepoint admin url ("https://cosmos-admin.sharepoint.com/").

Steps to reproduce
Create a client context with a site url.
Use the clientcontext to create a pnpcontext with the following function: "await PnPCoreSdk.Instance.GetPnPContextAsync"
2: try it with clientcontext.Web.Context

Create a client context with a site url.
Use the clientcontext.Web.Context to create a pnpcontext with the following function: "await PnPCoreSdk.Instance.GetPnPContextAsync(web.Context as ClientContext)"
Expected behavior
Expected behavior is a copy of the clientcontext to pnpcontext.

Environment details (development & target environment)
pnp.core: 1.6.0

Additional info
I get this problem in pnp.Framework when I'm trying to get a site template then we can't find any pages because the pnp.core is target to the sharepoint admin url

PageExtensions.cs line 874
public async static Task<IPage> LoadClientSidePageAsync(this Web web, string pageName) { using (var pnpContext = await PnPCoreSdk.Instance.GetPnPContextAsync(web.Context as ClientContext).ConfigureAwait(false)) { return (await pnpContext.Web.GetPagesAsync(pageName).ConfigureAwait(false)).FirstOrDefault(); } }

Work arround on the pnp.framework side:

` public async static Task LoadClientSidePageAsync(this Web web, string pageName)
{
using (var pnpContext = await PnPCoreSdk.Instance.GetPnPContextAsync(web.Context as ClientContext).ConfigureAwait(false))
{
var context = pnpContext;
Uri targetSiteUri = new Uri(web.Url);

            // Additional check because sometimes the PnPCoreSdk.Instance.GetPnPContextAsync used the wrong url
            if (pnpContext.Uri != targetSiteUri)
            {
                context = await pnpContext.CloneAsync(targetSiteUri);
            }

            return (await context.Web.GetPagesAsync(pageName).ConfigureAwait(false)).FirstOrDefault();
        }
    }`
But I think that is not the way to go because the problem is in pnp.core

**Comment by danielpastoor** [comment]
It is going wrong in the following function:
```
public async Task<PnPContext> GetPnPContextAsync(ClientContext context)
        {
            Uri ctxUri = new Uri(context.Url);
           
            var ctxSettings = context.GetContextSettings();
            
            if (ctxSettings!=null && ctxSettings.Type == Utilities.Context.ClientContextType.PnPCoreSdk && ctxSettings.AuthenticationManager!=null)
            {
            // returns the wrong PnPContext
                var pnpContext = ctxSettings.AuthenticationManager.PnPCoreContext;
                if (pnpContext != null)
                {
                    return pnpContext;
                }
                else
                {
                    var iAuthProvider = ctxSettings.AuthenticationManager.PnPCoreAuthenticationProvider;
                    if (iAuthProvider != null)
                    {
                        var factory0 = BuildContextFactory();
                        return await factory0.CreateAsync(ctxUri, iAuthProvider).ConfigureAwait(false);
                    }
                }
            }
            var factory = BuildContextFactory();
            return await factory.CreateAsync(ctxUri, AuthenticationProviderFactory.GetAuthenticationProvider(context)).ConfigureAwait(false);
        }```
       
       A fix would be to check if the Uri from the  `ctxSettings.AuthenticationManager.PnPCoreContext` and ctxUri  uri equals

**Comment by danielpastoor** [comment]
Fix is added to pull request:
https://github.com/pnp/pnpframework/pull/667

**Comment by jansenbe** [comment]
closing now
