### ISSUE TITLE
Default Values are not working propertly in Libraries with several content types

### ISSUE THREAD

**Issue by magarma** [pnp/pnpframework#674]
Hi,
there is an issue when creating a library with several content types and metadata fields and those metadata fields have default value at site column level. 

Only the default content type is getting default values when creating a new Word document.
![image](https://user-images.githubusercontent.com/8925463/171833743-bb64c842-9984-492f-9f72-ecbd6e82a0f0.png)

The last document created is the one with the default content type
![image](https://user-images.githubusercontent.com/8925463/171833907-24ba3f2b-da93-4e21-9742-9ea8d9c8f1c1.png)

As you can see the default column values are not set at folder level. The value should be got from the site column, but is only happening for some content types...
![image](https://user-images.githubusercontent.com/8925463/171834086-301e6c19-1076-4276-94e7-e12fc2cb3667.png)

Researching a investigating a bit the issue, I've found that there is a line in the ObjectListInstance handler, that is causing the issue...
![image](https://user-images.githubusercontent.com/8925463/171834312-2ed65755-3f20-4125-9d34-3f9d4d9c83e3.png)

Commenting that highlighted line, it's working fine... 
                           
However, I don't know why it's required that
<<< 
// To avoid error [Exception setting "Hidden": "Cannot change Hidden attribute for this field], add fields to list before adding the content type. #2407
>>>
I did some tests, but I couldn't find the reason of that line...
Any idea @jansenbe ? 

It's quite anoying, we have several site collections configured with default metadata and this is impacting us...

**Comment by magarma** [comment]
https://github.com/pnp/PnP-Sites-Core/issues/2407

I think that I've found the Issue and PR that added that... but commenting that line of code and provisioning that sample template is working fine for me... so maybe there was something more and now it's not required anymore.
@jansenbe

**Comment by magarma** [comment]
Found more people having the same issue, ... from 2020
https://techcommunity.microsoft.com/t5/sharepoint/issue-with-column-default-value-settings/m-p/1176590

**Comment by jansenbe** [comment]
@magarma : feel free to create PR with the proposed fix @magarma
