### ISSUE TITLE
Question about release schedule

### ISSUE THREAD

**Issue by tbithell** [pnp/pnpframework#7]
In the graphic that describes the release schedule for GA if says framework depends on the Core SDK GA release.  Please clarify if that means that the schedule depends on it or if that means the package is a dependency of framework.

**Comment by jansenbe** [comment]
Hey @tbithell ,

It's a package dependency, for example: we're planning to create a pages API in PnP Core SDK and then drop that part of the code in PnP Framework, but instead have PnP Framework consume the pages API from PnP Core SDK. This approach will allow us to gradually move over from PnP Framework into PnP Core SDK without impacting the PnP Framework users

**Comment by tbithell** [comment]
Sweet this looks like it addresses my question in the pnp core sdk repo.  Seems like the answer is use framework for add-in auth context calls, use core sdk for other stuff.  Does that sound right?

**Comment by jansenbe** [comment]
Well that depends what features you need. If you need PnP Framework then maybe it's easier to stick with that, we'll under the covers automatically call PnP Core SDK. The fact that you need PnP Framework also brings CSOM as a dependency, so you just as well can use CSOM to talk to SharePoint. If you don't want the CSOM dependency in your project you need to stick with PnP Core SDK.

**Comment by tbithell** [comment]
Until Graph can handle everything CSOM can AND doesn't require an app with blanket access all site collections in a tenant to run in the azure app auth context, we have to use CSOM for some things.  For a lot of enterprise security teams, an app with that level of access is a non-starter.

**Comment by jansenbe** [comment]
The auth story is not tied to CSOM as such: in both PnP Framework as PnP Core SDK we require to use Azure AD based authentication...this is not scoped to a single site collection. The old cookie based auth used by CSOM is not available anymore in the CSOM for .Net Standard, hence we also dropped that support from PnP Framework. 

If being able to only grant permissions for a given site, then you would have to stick to PnP Sites Core (the current mainstream library) for now...that one however depends on the .NET framework and only runs on Windows

**Comment by tbithell** [comment]
@jansenbe - fortunately, for me, that isn't quite accurate, I'm presently using a sharepoint add-in to auth to CSOM with the framework library.   

Making this call with an add-in ClientId and Secret has been working so far, and was working when I pulled the pnp site core code and built a package from the .net standard project a couple months ago while waiting for this package to come out.

authManager.GetACSAppOnlyContext(
                scUrl,
                CSOMClientId,
                CSOMClientSecret,
                AzureEnvironment.Production);

**Comment by jansenbe** [comment]
Azure acs indeed still works and is included in PnP Framework

**Comment by jansenbe** [comment]
Since ACS is still you're not blocked, closing this issue then.
