### ISSUE TITLE
Home.aspx doesn't get updated when applying PnP Template

### ISSUE THREAD

**Issue by YannickRe** [pnp/pnpframework#73]
Applying a template that is supposed to update the front page (Home.aspx) of a Communication Site fails with the latest version(s) of PnP.Framework. (0.1.101.0)
No error messages occur, but also no updates happen on the page.

Returning back to version 0.1.83.0 (before the switch to PnP.Core for handling ClientSidePages) makes the template work without a problem.

**Comment by jansenbe** [comment]
Thanks for reporting this @YannickRe , I'll have a look

**Comment by jansenbe** [comment]
@YannickRe : I can repro this, seems to be an issue in PnP Core SDK...working on a fix + test case that covers this scenario

**Comment by YannickRe** [comment]
@jansenbe Awesome, I'll give it a try tomorrow!

**Comment by joelfmrodrigues** [comment]
@jansenbe @YannickRe I can confirm that this is working.
Was having the same issue with a build from a few days ago, but just updated to the latest and it's now updating the page

**Comment by YannickRe** [comment]
@joelfmrodrigues Thanks for letting me/us know. I haven't had a chance to test yet, since I have "that other issue with authentication" which I need to solve first before I can get back on the latest version of the framework 🙂
