### ISSUE TITLE
Unable to save or publish pages created from page template with custom content type [BUG]

### ISSUE THREAD

**Issue by maps05** [pnp/pnpframework#74]
#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Provisioned **page templates, with custom content types**, should work as expected. I.e. create a page from a template and be able to save and publish it.

#### Observed Behavior
After I create a page from a template with custom content type, I'm not able to save it. I get the following error:

"Could not save your changes
REST error Error with code -2147024809, System.ArgumentException due to Inner-Message: Invalid data has been used to update the list item. The field you are trying to update may be read only. Exception-Message: [HTTP]:400 - Bad Request [CorrelationId]:3d429e9f-f011-2000-706a-987f530ad6ad [Version]:16.0.0.20802 at Error: Inner-Message: Invalid data has been used to update the list item. The field you are trying to update may be read only. Exception-Message: [HTTP]:400 - Bad Request [CorrelationId]:3d429e9f-f011-2000-706a-987f530ad6ad [Version]:16.0.0.20802 at new t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_699158f7fea868eb081b869967788f85.js:1:330395) at Function.e._getOdataRestApiError (https://spoprod-a.akamaihd.net/files/sp-client/chunk.sp-pages-statemanager_en-us_ad9e85c0fdab7a1e2d5d.js:1:20980) at https://spoprod-a.akamaihd.net/files/sp-client/chunk.sp-pages-statemanager_en-us_ad9e85c0fdab7a1e2d5d.js:1:23687"

This is resultant from failed request to https://<tenant>.sharepoint.com/sites/<site>/_api/sitepages/pages(<itemId>)/Copy, which return 400 with no additional data. I couldn't find anything relevant in the sent request.

Issue persists in several versions:

3.23.2007.1 (PnP PowerShell V3)
3.28.2012.0 (PnP PowerShell V3)
0.3.26 (PnP PowerShell VNext)

Also relevant to note that this happens not only to newly provisioned but also also to existent sites, from which I had not receive complaints until mid-December. I've found other users reporting the same issue in the same period: https://docs.microsoft.com/en-us/answers/questions/200333/sharepoint-online-modern-page-creation-failure-wit.html

Currently I'm comparing sites with SPO Client Browser to try to find the culprit but without success so far.

#### Steps to Reproduce

1. Create a custom content type, inheriting from Site Page (no further configuration needed)
2. Add custom content type to Site Pages content types
3. Create page from custom content type, publish it and promote to page template
4. Extract template and provision in new vanilla site

Get-PnPProvisioningTemplate -Out template.xml -Handlers Fields, ContentTypes, Pages, PageContents, Lists, Navigation -IncludeAllClientSidePages -PersistBrandingFiles
Apply-PnPProvisioningTemplate -Path .\template.xml

OR

Get-PnPSiteTemplate -Out template.xml -Handlers Fields, ContentTypes, Pages, PageContents, Lists, Navigation -IncludeAllClientSidePages -PersistBrandingFiles
Invoke-PnPSiteTemplate -Path .\template.xml

5. Create page from custom template page template (from step 3), add title and try to save it

I've attached zip files with the templates generating the issue, each extracted with the respective module version.
[issue-0.3.26.zip](https://github.com/pnp/pnpframework/files/5770151/issue-0.3.26.zip)
[issue-3.28.2012.0.zip](https://github.com/pnp/pnpframework/files/5770152/issue-3.28.2012.0.zip)

**Comment by gautamdsheth** [comment]
This looks similar to the issue here - https://github.com/pnp/pnpframework/issues/53 .
Can you try the workaround(s) mentioned in that issue, basically remove the extra OOTB fields from the template and try applying it again ?

**Comment by maps05** [comment]
@gautamdsheth thank you a lot for that, I overlooked that issue as the title didn't appear to relate to my problem. Although I'm facing a different error message, it is indeed the same behavior and root cause.

The user b00johst indicates the solution, both for new sites (removing OOB fields as you indicated) or already damaged provisioned sites (fix SelectedFilename and LinkTitle fields). I've confirm those workarounds and therefore close this one.
