### ISSUE TITLE
Custom Event content type missing categories

### ISSUE THREAD

**Issue by derhallim** [pnp/pnpframework#75]
**Environment:** 
SharePoint Online

**Expected Behavior**:
When deploying a custom event content type to the default events list, and assign it to be the default content type, it should work with the events web part when trying to add a new event. 

**Actual Behavior** 
When clicking on "Add Event" from the Events Web Part, I cannot choose a Category from the dropdown as shown below: 
![image](https://user-images.githubusercontent.com/7239963/103671375-d1247880-4f48-11eb-82af-73ffe71d1d3d.png)

**Steps to reproduce:** 

Create a content type and a list using this content type, and deploy through a Tenant Template. XML found in this gist: https://gist.github.com/derhallim/be1a994e7218213b37c81b321fc09079

**Comment by derhallim** [comment]
Note: Doing the same in the UI (creating content type, adding it to the library, setting the default content type, then using the Web Part to add a new event) will work fine without issues.

**Comment by jansenbe** [comment]
Hi @derhallim , can you try to update your content type without using the OOB fieldrefs (see #53) and see if that fixes the issue?

**Comment by jansenbe** [comment]
@derhallim : did my comment help to get things working? If so, please close this issue
