### ISSUE TITLE
401 Unauthorized Error When Using App Only Secret Authentication

### ISSUE THREAD

**Issue by Blaze147** [pnp/pnpframework#789]
When using an App Id & secret generated through Azure AD to authenticate for an AppOnly connection to SharePoint, a 401 Unauthorized error is returned regardless of the permissions given to the app in SharePoint or Azure AD Admin Center.
Issues occur when using the code outlined below:
```
using (ClientContext cc = new AuthenticationManager().GetACSAppOnlyContext(siteUrl, clientID, clientSecret))  
{      
   cc.Load(cc.Web, p => p.Title);
   cc.ExecuteQuery();
   Console.WriteLine(cc.Web.Title);
}

```
![image](https://user-images.githubusercontent.com/34349553/201562460-de0420b8-fc11-43aa-8901-5395f9c998e7.png)

However, when using Azure AD Certificate Authentication instead of Secret Auth, no exceptions or server errors occur as shown with the code below:
```
var authManager = new AuthenticationManager(clientID, "C:\\Documents\\Cert.pfx", certPass, "company.onmicrosoft.com");
using (var cc = authManager.GetContext("https://company.sharepoint.com/sites/Company"))
{
   cc.Load(cc.Web, p => p.Title);
   cc.ExecuteQuery();
   Console.WriteLine(cc.Web.Title);
};
```

**Comment by tbithell** [comment]
@plamber  my comment above should really be investigated... after upgrading from pnp core auth 1.7 to 1.8 and pnp framework 1.10 to 1.11 we are still getting some of these, but the number has dropped off a cliff, we went from 10s of thousands a day to 100s if that.  We dug through the code quite a bit and found that there are instances where null can be sent for the realm.  And given that we are seeing calls to auth that lack the sub guid it seems an awful lot that, under load, that is happening for some reason.

**Comment by Blaze147** [comment]
I should say that I never had any issues after moving to cert authentication. @tbithell If you can, I would do that as well. It never hurts to be more secure.

**Comment by pkbullock** [comment]
Sorry we haven't got back to the query, we are closing due to its age, please reopen if this is an issue. 😊
Just to say, the client/secret combination cannot be used with SharePoint APIs.

**Comment by johnguilbert1970** [comment]
Hi pkbullock.
I have been using the following code which has been working fine. I did upgrade to windows 11 about 6 months ago. The code is as follows:

 AuthenticationManager authenticationManager = new AuthenticationManager();

```
            using (ClientContext clientContext = authenticationManager.GetACSAppOnlyContext(_siteUrl, _clientId, _clientSecret))
            {
                User Requester = clientContext.Web.EnsureUser(emailAddress);
                clientContext.Load(Requester);
                clientContext.Load(clientContext.Web);
                clientContext.ExecuteQuery();
```

Every time I run this in Visual Studio 2022 in debug mode it fails now on Execute Query with "Failed Request Failed" and sometimes it will work OK if I wait long enough. Is this related to the above? Works fine on Live Azure App Service. Checked browser settings TLS 1.2/TLS 1.3 supported. .Net Core version is 6.

Help would be really appreciated.

Thanks.

John.

**Comment by johnguilbert1970** [comment]
> @plamber my comment above should really be investigated... after upgrading from pnp core auth 1.7 to 1.8 and pnp framework 1.10 to 1.11 we are still getting some of these, but the number has dropped off a cliff, we went from 10s of thousands a day to 100s if that. We dug through the code quite a bit and found that there are instances where null can be sent for the realm. And given that we are seeing calls to auth that lack the sub guid it seems an awful lot that, under load, that is happening for some reason.

Did you resolve?

**Comment by plamber** [comment]
hi @johnguilbert1970 ,
Sorry for my late reply. Just noticed the notification now. I am not actively working on this issue. Maybe someone else from the community is going to look into this.

Br

**Comment by johnguilbert1970** [comment]
> hi @johnguilbert1970 , Sorry for my late reply. Just noticed the notification now. I am not actively working on this issue. Maybe someone else from the community is going to look into this.
> 
> Br

No probs. Hopefully someone can help.
