### ISSUE TITLE
Getting Client Context from Sharepoint return null

### ISSUE THREAD

**Issue by DenisRouge** [pnp/pnpframework#79]
Hello,
We are trying to migrate from PnPCore.
We used the following code to get a Client Context
```
using ( var auth = new OfficeDevPnP.Core.AuthenticationManager() )
using ( var ctx = auth.GetWebLoginClientContext( "https://mycompany.sharepoint.com" ) )
{
    // Do something...
}
```
We tried to replace it by this code but the context returned is null
```
using ( var auth = new PnP.Framework.AuthenticationManager() )
using ( var ctx = auth.GetContext( "https://mycompany.sharepoint.com"  ) )
{
    // Do something...
}
```
Could you please advice?

**Comment by jansenbe** [comment]
We don't support the old weblogin anymore from PnP Framework, but you can use other login methods like an interactive login which allows one you to login using the default Microsoft 365 authentication UI. This does require you to create an Azure AD application and use that.

All the new auth methods are supported via AuthenticationManager, but you need to specify the needed options via the constructor. Here's an example of doing this for app-only cert auth:


```csharp
using (var clientContext = new AuthenticationManager("e5808e8b-6123-12a9-b123-9003db04a882",  certPath, certpwd, "contoso.onmicrosoft.com").GetContext("https://contoso.sharepoint.com/sites/TheLanding1"))
{
    // Use the context
}
```

**Comment by DenisRouge** [comment]
Our application use the current windows user credential to access to a file stored in Sharepoint. Do you have any clue of how to login without interactive neither use Azure AD application?

**Comment by jansenbe** [comment]
So you've a in house auth system that's connected to Azure AD then? I assume you're using SPO and not SharePoint on-premises?

**Comment by DenisRouge** [comment]
Exactly. We connect to Azure AD with a MFA using SPO.

**Comment by jansenbe** [comment]
Did you try the interactive auth option we have? Use this constructor (https://github.com/pnp/pnpframework/blob/dev/src/lib/PnP.Framework/AuthenticationManager.cs#L148) and provide your app id, redirect url (= http://localhost) and domain (e.g. contoso.onmicrosoft.com). You use these instructions to create an app that supports interactive auth: https://pnp.github.io/pnpcore/demos/Demo.Console/README.html#register-and-configure-an-aad-app

**Comment by DenisRouge** [comment]
Unfortunatly we cannot register our application in the Sharepoint where are the files we need to access, so we don't have any app Id. We didn't have to do this using the old GetWebLoginClientContext method which use the user credentials.

**Comment by jansenbe** [comment]
@DenisRouge : let me see if we can move the web login logic back from PowerShell to the AuthenticationManager class

**Comment by jansenbe** [comment]
@DenisRouge : given the weblogin code cannot be compiled in .NET Standard 2.0 we can't simply move it back from PowerShell into PnP Framework. We're discussing whether we can make an additional PnP.Framework.WebLogin package, but in the short term  your best solution will be copying the powershell implementation into your code base. See https://github.com/pnp/powershell/blob/4e8bc03ed3976c4bccb826da1f0892777f11fc6d/src/Commands/Utilities/BrowserHelper.cs for what to copy.

**Comment by DenisRouge** [comment]
Ok, I will check. Thank you

**Comment by jansenbe** [comment]
Closing issue

**Comment by Dr-Oli** [comment]
> @DenisRouge : given the weblogin code cannot be compiled in .NET Standard 2.0 we can't simply move it back from PowerShell into PnP Framework. We're discussing whether we can make an additional PnP.Framework.WebLogin package, but in the short term your best solution will be copying the powershell implementation into your code base. See https://github.com/pnp/powershell/blob/4e8bc03ed3976c4bccb826da1f0892777f11fc6d/src/Commands/Utilities/BrowserHelper.cs for what to copy.

Hi @jansenbe,

was there any progress on  PnP.Framework.WebLogin package? I would say that there will be probably a lot of people having issue to create app id.

Thx,
Oliver
