### ISSUE TITLE
Contribution Guidelines?

### ISSUE THREAD

**Issue by hugoabernier** [pnp/pnpframework#8]
I'm updating [my list of PnP repos](https://tahoeninjas.blog/2019/08/23/popular-pnp-repositories-and-how-to-get-started/) and I noticed that I didn't have this repo in it. 

You don't seem to have contribution guidelines, does that mean that you don't actively seek contributions from folks outside of this repo?

**Comment by jansenbe** [comment]
Hi @hugoabernier ,
We absolutely seek contributors from outside, this actually replaces PnP Sites Core. There just was not time to write proper contribution guidelines yet (or port what we have in PnP Sites Core, which most likely is very outdated)

**Comment by hugoabernier** [comment]
Thanks, I'll add the repo to the list and will revisit when the contribution guideline is added.
