### ISSUE TITLE
[BUG] NewDocumentTemplates not properly applied

### ISSUE THREAD

**Issue by Leviani** [pnp/pnpframework#812]
## Category

- [x] Bug

## Describe the bug
When trying to modify a Custom Content Type from the "New" Menu, the NewDocumentTemplates Tag value is missing the Token Replacement.

## Steps to reproduce
When I modify the New Menu via UI (Edit New Menu), I can see the modifications reflected in the Template File, once a template is extracted via _Get-PnPSiteTemplate_.
That Template has Token Values set inside the <NewDocumentTemplates> Tag.

> _{"contentTypeId":"{listcontenttypeid:Documents,0x01200048B976BE692FB4429EFD78FB3407496E}_

But when applying that Template with _Invoke-PnPSiteTemplate_, the "listcontenttypeid" Token is not replaced.

Reading the values from the SharePoint View via CSOM, after the _Invoke-PnPSiteTemplate_ Command, shows that it did submit the value _{listcontenttypeid:Documents,0x01200048B976BE692FB4429EFD78FB3407496E}_ instead of replacing it with the actual ID.

## Expected behavior
When the Tag <NewDocumentTemplates> is automatically created by the Get Template Command, and Tokens are added to its value, then the Invoke Command should also be able to replace those before submitting.

## Environment details (*development & target environment*)
PnP.PowerShell Version 1.10.0
SharePoint Online

**Comment by Leviani** [comment]
So I guess even after moving this issue, it is still unnoticed ? :(

Anyone else experiencing this issue ?

**Comment by pkbullock** [comment]
Sorry we haven't got back to the query, we are closing due to its age, please reopen if this is an issue. This was also transferred to PnP PowerShell
