### ISSUE TITLE
A connection attempt failed / Token request failed / The SSL connection could not be established  with GetACSAppOnlyContext

### ISSUE THREAD

**Issue by RubenHerrera86** [pnp/pnpframework#814]
Hello All,

From Nov 29, we are getting intermittent error messages at the moment to perform some operations such as update field values in  document libraries with GetACSAppOnlyContext (SharePoint App). 

Please find some messages down below:

1. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

2. Token request failed.
 
3. The SSL connection could not be established, see inner exception. Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Can you please help us to see what could be the issue? Since our solution has been working properly since Febrary 2022 without any issue.

**Comment by wtermini** [comment]
@RubenHerrera86 have you found a resolution?

**Comment by pkbullock** [comment]
Sorry we haven't got back to the query, we are closing due to its age, please reopen if this is an issue. 😊
