### ISSUE TITLE
Unable to render SharePoint online modern pages html content in to .net MVC pages

### ISSUE THREAD

**Issue by siva201926** [pnp/pnpframework#815]
Hi Team,
Unable to render SharePoint online modern pages html content in to .net MVC pages using pnp.framework(c#), unable to extract inline styles of tables, colors and styles and show in .net pages.

Using latest version of pnp.framework(1.10.pv)

**Comment by pkbullock** [comment]
Hi, sorry this is not a feature of this framework. Templates or pages methods do not include the rendering assets for standalone pages. Let us know if we have misunderstood the ask here.
