### ISSUE TITLE
"Additions to this website have been blocked" when updating a ClientSidePage

### ISSUE THREAD

**Issue by YannickRe** [pnp/pnpframework#84]
After I had #70 resolved, a new issue popped up when updating clientsidepages:
```
Additions to this Web site have been blocked.

Please contact the administrator to resolve this problem.
```
and that is triggered from
https://github.com/pnp/pnpframework/blob/2079cded410148a0d757f35f619d439b286a0396/src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectClientSidePages.cs#L913-L916

It doesn't occur when creating new pages, only when updating an existing page.
It also occurs when using username/password authentication through the AuthenticationManager, so it isn't my custom token acquisition that gives this issue.

_Originally posted by @YannickRe in https://github.com/pnp/pnpframework/issues/70#issuecomment-756439525_

**Comment by jansenbe** [comment]
Fixed

**Comment by YannickRe** [comment]
That was a quick fix! Hereby confirmed that it works when connecting to source code. Thus next week I can get back on the latest version of the nuget package 🙂.

Thank you!
