### ISSUE TITLE
Invoke-PnPSiteTemplate System.UnauthorizedAccessException Error applying default column values

### ISSUE THREAD

**Issue by anthonywhite** [pnp/pnpframework#846]
Scenario:
A PnP template that has been working for a long time and has been successfully applied to more than 50 sites, working yesterday at 5pm, suddenly (but consistently) since then now failing when running `Invoke-PnPSiteTemplate`. The output to the PowerShell console says `Error applying default column values` but the trace log says `System.UnauthorizedAccessException` (see below)

**The same template applies ok in a different non-production tenant**. Any ideas how I debug this?

Error from Set-PnPTraceLog:

pwsh Information: 0 : 2023-02-24 09:28:21.2563	[List instances]	[20]	[Debug]	Creating view Workspace	33258ms	79ac16c2-5903-4744-9cb1-7e66d20e6953
pwsh Information: 0 : 2023-02-24 09:28:21.7511	[List instances]	[20]	[Debug]	Creating view All Items	33753ms	79ac16c2-5903-4744-9cb1-7e66d20e6953
pwsh Information: 0 : 2023-02-24 09:28:22.2736	[List instances]	[20]	[Debug]	Creating view All Items	34275ms	79ac16c2-5903-4744-9cb1-7e66d20e6953
pwsh Information: 0 : 2023-02-24 09:28:22.7679	[List instances]	[20]	[Debug]	Creating view All Items	34770ms	79ac16c2-5903-4744-9cb1-7e66d20e6953
pwsh Error: 0 : 2023-02-24 09:28:24.1627	[PnP.Framework]	[0]	[Error]	ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerUnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
ServerErrorCode: -2147024891
ServerErrorTypeName: System.UnauthorizedAccessException
ServerErrorTraceCorrelationId: d64e99a0-60b2-6000-3b7f-0053ec780ba4
ServerErrorValue: 
ServerErrorDetails: 
.	0ms	
pwsh Information: 0 : 2023-02-24 09:28:24.1632	[List instances]	[20]	[Debug]	Code execution scope ended	36165ms	79ac16c2-5903-4744-9cb1-7e66d20e6953
pwsh Information: 0 : 2023-02-24 09:28:24.1633	[ProvisioningTemplate WebHook Call]	[20]	[Debug]	Code execution scope started	0ms	79ac16c2-5903-4744-9cb1-7e66d20e6953
pwsh Information: 0 : 2023-02-24 09:28:24.1633	[ProvisioningTemplate WebHook Call]	[20]	[Debug]	Code execution scope ended	0ms	79ac16c2-5903-4744-9cb1-7e66d20e6953
pwsh Information: 0 : 2023-02-24 09:28:24.1634	[Provisioning]	[20]	[Debug]	Code execution scope ended	102344ms	79ac16c2-5903-4744-9cb1-7e66d20e6953

**Comment by markgort86** [comment]
We got more or less the same error targeting SharePoint Online. Our template was working okay around 6pm yesterday. But where it's failing is isolated to the following part of the PnP template. See XML below: 
`<pnp:Lists>
<pnp:ListInstance Title="Team Documents 4" TemplateType="101" Url="TeamDocuments4" EnableFolderCreation="true">
</pnp:ListInstance>
</pnp:Lists>`

Removing this part our template is working fine. But using this within a PnP template the same error is throwing up after using this template with "Invoke-PnPSiteTemplate"
![image](https://user-images.githubusercontent.com/52573368/221179718-b8aa3c49-ea27-43d7-92b8-7bf60d824d03.png)

**Comment by amalitabose** [comment]
Facing same issue in LTS version. Tried by removing default values & and also the Default node in XML and then re applying the template , still no luck same error.

ERROR: System.Exception: Error applying default column values ---> Microsoft.SharePoint.Client.ServerUnauthorizedAccessException: Attempted to perform an unauthorized operation

**Comment by anthonywhite** [comment]
@markgort86 the explanation for this can be found in #840 and elsewhere in PnP issues. Probably this can be closed as duplicate, but just to say our issue was resolved by switching to:

```
PnP.PowerShell 2.0.25
PnP.Framework 1.11.109-nightly
```
both of which have the https://github.com/pnp/pnpframework/commit/c4fd1468aa54cd62404f5a6e4362cbf6778bddc6 fix.

But @amalitabose as @jackpoz points out, if you do have column values you need to set, unfortunately only a change by Microsoft will address that and you will need to raise a support ticket with them. Indications from our support ticket experience indicate this issue is gaining visibility and traction with them though.

**Comment by amalitabose** [comment]
But if i don't have any such column with default value in template xml, in that case it should work ? In my case it still gives same error.

**Comment by popoygaming** [comment]
@amalitabose @anthonywhite @markgort86 

 It was mysteriously fixed in our tenant just today. Wondering if the same happened to your tenants?
Is there a messaging from MSFT about this sudden fix? Just worried that this issue might happen again.

**Comment by amalitabose** [comment]
@popoygaming Just now checked, even in my tenant its now working. 

@anthonywhite @markgort86
