### ISSUE TITLE
The link to "Migrating from PnP Sites Core to PnP Framework guide" is 404 and I can't find Samples

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpframework#860]
[Migrating from PnP Sites Core to PnP Framework guide](https://github.com/pnp/pnpframework/blob/dev/docs/MigratingFromPnPSitesCore.md) 
is broken

I am looking for a basic starting with PnP Framework tutorial or sample.
anyone?
I only found [Provisioning console application sample ](https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-provisioning-framework) but it uses the old version.

**Comment by pkbullock** [comment]
Hi, we are improving the docs, under ref #864

**Comment by pkbullock** [comment]
I have fixed the link. Working on samples, this will take bit longer.

**Comment by Ofer-Gal** [comment]
Thanks
