### ISSUE TITLE
AADSTS900561: The endpoint only accepts POST requests. Received a GET request

### ISSUE THREAD

**Issue by Mastahh** [pnp/pnpframework#88]
Hello,
Last week all were working, but today I cannot do auth using API.
I'm trying to do Auth for Sharepoint.

`using( AuthenticationManager oAuthenticationManager = new AuthenticationManager( AuthenticationManager.CLIENTID_SPOMANAGEMENTSHELL, Login, Password ) )
				{
					return oAuthenticationManager.GetContext( SiteUrl );
				}`

**Comment by jansenbe** [comment]
Hi @Mastahh ,

Just tried below and that still works for my tenant:

```csharp
using (var clientContext = new AuthenticationManager(AuthenticationManager.CLIENTID_SPOMANAGEMENTSHELL, "joe@contoso.onmicrosoft.com", ConvertToSecureString("mypwd")).GetContext("https://contoso.sharepoint.com/sites/TheLanding1"))
{
                clientContext.Load(clientContext.Web, p => p.Title);
                clientContext.ExecuteQueryRetry();
}
```

Maybe this is an temp hiccup at the Azure AD side? Do you have other tenants to test against?

**Comment by Mastahh** [comment]
At the moment only one tenant, and GetContext() Throws following error
AADSTS900561: The endpoint only accepts POST requests. Received a GET request.

**Comment by Mastahh** [comment]
I found the problem, in config password was cleared, and this error occurs if password is null.
