### ISSUE TITLE
Why Office365Geography Enum is different than Geo location codes?

### ISSUE THREAD

**Issue by frankchen76** [pnp/pnpframework#90]
Hi, 

when I reviewed the PnP.Framework/Enums/Office365Geography.cs, why is there only 13 geo location? when I compared to [Geo location codes](https://docs.microsoft.com/en-us/microsoft-365/enterprise/multi-geo-add-group-with-pdl?view=o365-worldwide#geo-location-codes), there are Germany (DEU) and Norway (NOR) two geo not included in the Office365Geography Enum. anyone know the reason? 
when you looked at actually definition, the United Kingdom is define "**GRB**" in Office365Geography.cs which is different than "**GBR**" in the document. is it expected or typo?

**Comment by jansenbe** [comment]
Thanks for bringing this up @frankchen76 ! Fixed now.
