### ISSUE TITLE
Error after update nugget to 1.13.0 PnP.Framework

### ISSUE THREAD

**Issue by zapafta** [pnp/pnpframework#900]
## Category

- [x]  Create sites in sharepoint

## Describe the bug

> After updating this nugget, an error occurred when we use this method

Method not found: 'Microsoft.SharePoint.Client.ClientContext PnP.Framework.Sites.SiteCollection.Create(Microsoft.SharePoint.Client.ClientContext, PnP.Framework.Sites.TeamSiteCollectionCreationInformation, Int32, Boolean, System.String)

Could you help me, please?

**Comment by TiagoSantosOrbcom** [comment]
Hello,
I have the same issue, i'm trying to create the sharepoint site via powershell with c#.

**Comment by pkbullock** [comment]
What versions are you upgrading from?
A few months ago, the constructor included new parameter for Azure enviroments, check this commit: https://github.com/pnp/pnpframework/commit/cfb9e5f585bec3c1efa27f5f76ab8a2c12484b6f , try adding the default azure environment, AzureEnvironment.Production as a additiional parameter.

**Comment by pkbullock** [comment]
Have you updated PnP PowerShell to align? Wonder if there is a conflict here between the versions of C# + PnP PowerShell. Admittedly, not tried that combo before.

**Comment by zapafta** [comment]
Hello @pkbullock ,
Many thanks for your comment.
The problem is both modules don't align in version.
