### ISSUE TITLE
How do I trust the PnP managed app

### ISSUE THREAD

**Issue by waaromikniet** [pnp/pnpframework#93]
I have included the nuget package in my codebase and try to connect using the authenticationmanager and username/password. The account that I am using hasn't trusted the PnP managed app. In my Azure AD I don't see the app in my Enterprise Apps. How can I do this? Do I need to do this with PnP PowerShell?

**Comment by jansenbe** [comment]
See https://pnp.github.io/powershell/articles/authentication.html#setting-up-access

**Comment by waaromikniet** [comment]
Can I no longer use the built in PnP managed app that is already present like I use in PnP PowerShell

Connect-PnPOnline -Url https://contoso.sharepoint.com -PnPManagementShell

**Comment by jansenbe** [comment]
Closing as the question has been answered.
