### ISSUE TITLE
Azure Function Support

### ISSUE THREAD

**Issue by matsla** [pnp/pnpframework#99]
We have a lot of customizations using Azure Functions V1 in C# using PNP Sites Core. Azure Function V1 supports .NET Framework 4.7 NOT .NET Standard 2.0 and .NET 5.

How can we use this new pnpframework with Azure Functions?
Is all features for PnP Sites Core (sharePoint Online) migrated to pnpframework?

**Comment by jansenbe** [comment]
Yes, all features of PnP Sites Core are migrated to PnP Framework and PnP Framework ships as .NET Standard 2.0 and .NET 5 library. This enables you to run your code on a V3 Azure function. Do note that the auth model slightly changed, it's recommended to use the AuthManager class and use the relevant constructor for the auth pattern you need.

**Comment by matsla** [comment]
OK thanks for the information @jansenbe. Current available nuget version is 0.1.116-preview. When will the pnpframework be released in GA? So we can start migrating from PnP Sites Core ?

**Comment by jansenbe** [comment]
GA will be next week 🙂

**Comment by jansenbe** [comment]
Closing this issue since the questions are answered
